// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aps.proto

// Protobuf Java Version: 3.25.2
package com.aps.grpc.proto;

public final class ApsProto {
  private ApsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aps_v1_SolveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aps_v1_SolveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aps_v1_Job_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aps_v1_Job_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aps_v1_SolveParams_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aps_v1_SolveParams_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aps_v1_Weights_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aps_v1_Weights_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aps_v1_Limits_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aps_v1_Limits_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aps_v1_SolveResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aps_v1_SolveResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aps_v1_KpiSummary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aps_v1_KpiSummary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aps_v1_ScheduleItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aps_v1_ScheduleItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aps_v1_ShiftViolation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aps_v1_ShiftViolation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aps_v1_ConvergencePoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aps_v1_ConvergencePoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aps_v1_SubmitJobRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aps_v1_SubmitJobRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aps_v1_SubmitJobResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aps_v1_SubmitJobResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aps_v1_GetJobStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aps_v1_GetJobStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aps_v1_GetJobStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aps_v1_GetJobStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aps_v1_ListJobsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aps_v1_ListJobsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aps_v1_ListJobsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aps_v1_ListJobsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aps_v1_JobInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aps_v1_JobInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\taps.proto\022\006aps.v1\"\177\n\014SolveRequest\022\022\n\nr" +
      "equest_id\030\001 \001(\t\022\033\n\023plan_start_epoch_ms\030\002" +
      " \001(\003\022\031\n\004jobs\030\003 \003(\0132\013.aps.v1.Job\022#\n\006param" +
      "s\030\004 \001(\0132\023.aps.v1.SolveParams\"\210\002\n\003Job\022\013\n\003" +
      "vin\030\001 \001(\t\022\024\n\014due_epoch_ms\030\002 \001(\003\022\030\n\020stamp" +
      "ing_minutes\030\003 \001(\005\022\027\n\017welding_minutes\030\004 \001" +
      "(\005\022\030\n\020painting_minutes\030\005 \001(\005\022\030\n\020assemble" +
      "_minutes\030\006 \001(\005\022\021\n\tmold_code\030\007 \001(\t\022\027\n\017wel" +
      "ding_fixture\030\010 \001(\t\022\r\n\005color\030\t \001(\t\022\016\n\006con" +
      "fig\030\n \001(\t\022\024\n\014energy_score\030\013 \001(\001\022\026\n\016emiss" +
      "ion_score\030\014 \001(\001\"\211\001\n\013SolveParams\022\021\n\talgor" +
      "ithm\030\001 \001(\t\022\027\n\017time_budget_sec\030\002 \001(\005\022\014\n\004s" +
      "eed\030\003 \001(\003\022 \n\007weights\030\004 \001(\0132\017.aps.v1.Weig" +
      "hts\022\036\n\006limits\030\005 \001(\0132\016.aps.v1.Limits\"\224\001\n\007" +
      "Weights\022\021\n\ttardiness\030\001 \001(\001\022\024\n\014color_chan" +
      "ge\030\002 \001(\001\022\025\n\rconfig_change\030\003 \001(\001\022\025\n\renerg" +
      "y_excess\030\004 \001(\001\022\027\n\017emission_excess\030\005 \001(\001\022" +
      "\031\n\021material_shortage\030\006 \001(\001\"F\n\006Limits\022\034\n\024" +
      "max_energy_per_shift\030\001 \001(\001\022\036\n\026max_emissi" +
      "on_per_shift\030\002 \001(\001\"\343\002\n\rSolveResponse\022\022\n\n" +
      "request_id\030\001 \001(\t\022#\n\007summary\030\002 \001(\0132\022.aps." +
      "v1.KpiSummary\022,\n\020baseline_summary\030\003 \001(\0132" +
      "\022.aps.v1.KpiSummary\022\r\n\005order\030\004 \003(\t\022&\n\010sc" +
      "hedule\030\005 \003(\0132\024.aps.v1.ScheduleItem\022/\n\021de" +
      "tailed_schedule\030\006 \003(\0132\024.aps.v1.ScheduleI" +
      "tem\022*\n\nviolations\030\007 \003(\0132\026.aps.v1.ShiftVi" +
      "olation\022-\n\013convergence\030\010 \003(\0132\030.aps.v1.Co" +
      "nvergencePoint\022\026\n\016engine_version\030\t \001(\t\022\020" +
      "\n\010warnings\030\n \003(\t\"\340\001\n\nKpiSummary\022\014\n\004cost\030" +
      "\001 \001(\001\022\033\n\023total_tardiness_min\030\002 \001(\003\022\031\n\021ma" +
      "x_tardiness_min\030\003 \001(\003\022\025\n\rcolor_changes\030\004" +
      " \001(\005\022\026\n\016config_changes\030\005 \001(\005\022\025\n\renergy_e" +
      "xcess\030\006 \001(\001\022\027\n\017emission_excess\030\007 \001(\001\022\031\n\021" +
      "material_shortage\030\010 \001(\001\022\022\n\nelapsed_ms\030\t " +
      "\001(\003\"\361\001\n\014ScheduleItem\022\013\n\003seq\030\001 \001(\005\022\013\n\003vin" +
      "\030\002 \001(\t\022\024\n\014process_type\030\003 \001(\005\022\017\n\007line_id\030" +
      "\004 \001(\003\022\024\n\014seq_in_shift\030\005 \001(\005\022\026\n\016start_epo" +
      "ch_ms\030\006 \001(\003\022\024\n\014end_epoch_ms\030\007 \001(\003\022\024\n\014due" +
      "_epoch_ms\030\010 \001(\003\022\025\n\rtardiness_min\030\t \001(\003\022\r" +
      "\n\005color\030\n \001(\t\022\016\n\006config\030\013 \001(\t\022\020\n\010shift_i" +
      "d\030\014 \001(\t\"A\n\016ShiftViolation\022\020\n\010shift_id\030\001 " +
      "\001(\t\022\r\n\005vtype\030\002 \001(\t\022\016\n\006excess\030\003 \001(\001\"3\n\020Co" +
      "nvergencePoint\022\014\n\004t_ms\030\001 \001(\003\022\021\n\tbest_cos" +
      "t\030\002 \001(\001\"9\n\020SubmitJobRequest\022%\n\007request\030\001" +
      " \001(\0132\024.aps.v1.SolveRequest\"4\n\021SubmitJobR" +
      "esponse\022\016\n\006job_id\030\001 \001(\t\022\017\n\007message\030\002 \001(\t" +
      "\"%\n\023GetJobStatusRequest\022\016\n\006job_id\030\001 \001(\t\"" +
      "\264\001\n\024GetJobStatusResponse\022\016\n\006job_id\030\001 \001(\t" +
      "\022\016\n\006status\030\002 \001(\t\022\022\n\ncreated_at\030\003 \001(\003\022\022\n\n" +
      "updated_at\030\004 \001(\003\022%\n\006result\030\005 \001(\0132\025.aps.v" +
      "1.SolveResponse\022\025\n\rerror_message\030\006 \001(\t\022\026" +
      "\n\016engine_version\030\007 \001(\t\" \n\017ListJobsReques" +
      "t\022\r\n\005limit\030\001 \001(\005\"1\n\020ListJobsResponse\022\035\n\004" +
      "jobs\030\001 \003(\0132\017.aps.v1.JobInfo\"Q\n\007JobInfo\022\016" +
      "\n\006job_id\030\001 \001(\t\022\016\n\006status\030\002 \001(\t\022\022\n\ncreate" +
      "d_at\030\003 \001(\003\022\022\n\nupdated_at\030\004 \001(\0032\216\002\n\nApsSe" +
      "rvice\0224\n\005Solve\022\024.aps.v1.SolveRequest\032\025.a" +
      "ps.v1.SolveResponse\022@\n\tSubmitJob\022\030.aps.v" +
      "1.SubmitJobRequest\032\031.aps.v1.SubmitJobRes" +
      "ponse\022I\n\014GetJobStatus\022\033.aps.v1.GetJobSta" +
      "tusRequest\032\034.aps.v1.GetJobStatusResponse" +
      "\022=\n\010ListJobs\022\027.aps.v1.ListJobsRequest\032\030." +
      "aps.v1.ListJobsResponseB \n\022com.aps.grpc." +
      "protoB\010ApsProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_aps_v1_SolveRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_aps_v1_SolveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aps_v1_SolveRequest_descriptor,
        new java.lang.String[] { "RequestId", "PlanStartEpochMs", "Jobs", "Params", });
    internal_static_aps_v1_Job_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_aps_v1_Job_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aps_v1_Job_descriptor,
        new java.lang.String[] { "Vin", "DueEpochMs", "StampingMinutes", "WeldingMinutes", "PaintingMinutes", "AssembleMinutes", "MoldCode", "WeldingFixture", "Color", "Config", "EnergyScore", "EmissionScore", });
    internal_static_aps_v1_SolveParams_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_aps_v1_SolveParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aps_v1_SolveParams_descriptor,
        new java.lang.String[] { "Algorithm", "TimeBudgetSec", "Seed", "Weights", "Limits", });
    internal_static_aps_v1_Weights_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_aps_v1_Weights_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aps_v1_Weights_descriptor,
        new java.lang.String[] { "Tardiness", "ColorChange", "ConfigChange", "EnergyExcess", "EmissionExcess", "MaterialShortage", });
    internal_static_aps_v1_Limits_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_aps_v1_Limits_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aps_v1_Limits_descriptor,
        new java.lang.String[] { "MaxEnergyPerShift", "MaxEmissionPerShift", });
    internal_static_aps_v1_SolveResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_aps_v1_SolveResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aps_v1_SolveResponse_descriptor,
        new java.lang.String[] { "RequestId", "Summary", "BaselineSummary", "Order", "Schedule", "DetailedSchedule", "Violations", "Convergence", "EngineVersion", "Warnings", });
    internal_static_aps_v1_KpiSummary_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_aps_v1_KpiSummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aps_v1_KpiSummary_descriptor,
        new java.lang.String[] { "Cost", "TotalTardinessMin", "MaxTardinessMin", "ColorChanges", "ConfigChanges", "EnergyExcess", "EmissionExcess", "MaterialShortage", "ElapsedMs", });
    internal_static_aps_v1_ScheduleItem_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_aps_v1_ScheduleItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aps_v1_ScheduleItem_descriptor,
        new java.lang.String[] { "Seq", "Vin", "ProcessType", "LineId", "SeqInShift", "StartEpochMs", "EndEpochMs", "DueEpochMs", "TardinessMin", "Color", "Config", "ShiftId", });
    internal_static_aps_v1_ShiftViolation_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_aps_v1_ShiftViolation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aps_v1_ShiftViolation_descriptor,
        new java.lang.String[] { "ShiftId", "Vtype", "Excess", });
    internal_static_aps_v1_ConvergencePoint_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_aps_v1_ConvergencePoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aps_v1_ConvergencePoint_descriptor,
        new java.lang.String[] { "TMs", "BestCost", });
    internal_static_aps_v1_SubmitJobRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_aps_v1_SubmitJobRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aps_v1_SubmitJobRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_aps_v1_SubmitJobResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_aps_v1_SubmitJobResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aps_v1_SubmitJobResponse_descriptor,
        new java.lang.String[] { "JobId", "Message", });
    internal_static_aps_v1_GetJobStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_aps_v1_GetJobStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aps_v1_GetJobStatusRequest_descriptor,
        new java.lang.String[] { "JobId", });
    internal_static_aps_v1_GetJobStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_aps_v1_GetJobStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aps_v1_GetJobStatusResponse_descriptor,
        new java.lang.String[] { "JobId", "Status", "CreatedAt", "UpdatedAt", "Result", "ErrorMessage", "EngineVersion", });
    internal_static_aps_v1_ListJobsRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_aps_v1_ListJobsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aps_v1_ListJobsRequest_descriptor,
        new java.lang.String[] { "Limit", });
    internal_static_aps_v1_ListJobsResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_aps_v1_ListJobsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aps_v1_ListJobsResponse_descriptor,
        new java.lang.String[] { "Jobs", });
    internal_static_aps_v1_JobInfo_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_aps_v1_JobInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aps_v1_JobInfo_descriptor,
        new java.lang.String[] { "JobId", "Status", "CreatedAt", "UpdatedAt", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
