// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aps.proto

// Protobuf Java Version: 3.25.2
package com.aps.grpc.proto;

/**
 * Protobuf type {@code aps.v1.ConvergencePoint}
 */
public final class ConvergencePoint extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:aps.v1.ConvergencePoint)
    ConvergencePointOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ConvergencePoint.newBuilder() to construct.
  private ConvergencePoint(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ConvergencePoint() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ConvergencePoint();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_ConvergencePoint_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_ConvergencePoint_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.aps.grpc.proto.ConvergencePoint.class, com.aps.grpc.proto.ConvergencePoint.Builder.class);
  }

  public static final int T_MS_FIELD_NUMBER = 1;
  private long tMs_ = 0L;
  /**
   * <pre>
   * 时间点（毫秒）
   * </pre>
   *
   * <code>int64 t_ms = 1;</code>
   * @return The tMs.
   */
  @java.lang.Override
  public long getTMs() {
    return tMs_;
  }

  public static final int BEST_COST_FIELD_NUMBER = 2;
  private double bestCost_ = 0D;
  /**
   * <pre>
   * 当前最优成本
   * </pre>
   *
   * <code>double best_cost = 2;</code>
   * @return The bestCost.
   */
  @java.lang.Override
  public double getBestCost() {
    return bestCost_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (tMs_ != 0L) {
      output.writeInt64(1, tMs_);
    }
    if (java.lang.Double.doubleToRawLongBits(bestCost_) != 0) {
      output.writeDouble(2, bestCost_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (tMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, tMs_);
    }
    if (java.lang.Double.doubleToRawLongBits(bestCost_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, bestCost_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.aps.grpc.proto.ConvergencePoint)) {
      return super.equals(obj);
    }
    com.aps.grpc.proto.ConvergencePoint other = (com.aps.grpc.proto.ConvergencePoint) obj;

    if (getTMs()
        != other.getTMs()) return false;
    if (java.lang.Double.doubleToLongBits(getBestCost())
        != java.lang.Double.doubleToLongBits(
            other.getBestCost())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + T_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTMs());
    hash = (37 * hash) + BEST_COST_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getBestCost()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.aps.grpc.proto.ConvergencePoint parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aps.grpc.proto.ConvergencePoint parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aps.grpc.proto.ConvergencePoint parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aps.grpc.proto.ConvergencePoint parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aps.grpc.proto.ConvergencePoint parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aps.grpc.proto.ConvergencePoint parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aps.grpc.proto.ConvergencePoint parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aps.grpc.proto.ConvergencePoint parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.aps.grpc.proto.ConvergencePoint parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.aps.grpc.proto.ConvergencePoint parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aps.grpc.proto.ConvergencePoint parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aps.grpc.proto.ConvergencePoint parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.aps.grpc.proto.ConvergencePoint prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code aps.v1.ConvergencePoint}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:aps.v1.ConvergencePoint)
      com.aps.grpc.proto.ConvergencePointOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_ConvergencePoint_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_ConvergencePoint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aps.grpc.proto.ConvergencePoint.class, com.aps.grpc.proto.ConvergencePoint.Builder.class);
    }

    // Construct using com.aps.grpc.proto.ConvergencePoint.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      tMs_ = 0L;
      bestCost_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_ConvergencePoint_descriptor;
    }

    @java.lang.Override
    public com.aps.grpc.proto.ConvergencePoint getDefaultInstanceForType() {
      return com.aps.grpc.proto.ConvergencePoint.getDefaultInstance();
    }

    @java.lang.Override
    public com.aps.grpc.proto.ConvergencePoint build() {
      com.aps.grpc.proto.ConvergencePoint result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.aps.grpc.proto.ConvergencePoint buildPartial() {
      com.aps.grpc.proto.ConvergencePoint result = new com.aps.grpc.proto.ConvergencePoint(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.aps.grpc.proto.ConvergencePoint result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.tMs_ = tMs_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.bestCost_ = bestCost_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.aps.grpc.proto.ConvergencePoint) {
        return mergeFrom((com.aps.grpc.proto.ConvergencePoint)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.aps.grpc.proto.ConvergencePoint other) {
      if (other == com.aps.grpc.proto.ConvergencePoint.getDefaultInstance()) return this;
      if (other.getTMs() != 0L) {
        setTMs(other.getTMs());
      }
      if (other.getBestCost() != 0D) {
        setBestCost(other.getBestCost());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              tMs_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 17: {
              bestCost_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long tMs_ ;
    /**
     * <pre>
     * 时间点（毫秒）
     * </pre>
     *
     * <code>int64 t_ms = 1;</code>
     * @return The tMs.
     */
    @java.lang.Override
    public long getTMs() {
      return tMs_;
    }
    /**
     * <pre>
     * 时间点（毫秒）
     * </pre>
     *
     * <code>int64 t_ms = 1;</code>
     * @param value The tMs to set.
     * @return This builder for chaining.
     */
    public Builder setTMs(long value) {

      tMs_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 时间点（毫秒）
     * </pre>
     *
     * <code>int64 t_ms = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTMs() {
      bitField0_ = (bitField0_ & ~0x00000001);
      tMs_ = 0L;
      onChanged();
      return this;
    }

    private double bestCost_ ;
    /**
     * <pre>
     * 当前最优成本
     * </pre>
     *
     * <code>double best_cost = 2;</code>
     * @return The bestCost.
     */
    @java.lang.Override
    public double getBestCost() {
      return bestCost_;
    }
    /**
     * <pre>
     * 当前最优成本
     * </pre>
     *
     * <code>double best_cost = 2;</code>
     * @param value The bestCost to set.
     * @return This builder for chaining.
     */
    public Builder setBestCost(double value) {

      bestCost_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 当前最优成本
     * </pre>
     *
     * <code>double best_cost = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBestCost() {
      bitField0_ = (bitField0_ & ~0x00000002);
      bestCost_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:aps.v1.ConvergencePoint)
  }

  // @@protoc_insertion_point(class_scope:aps.v1.ConvergencePoint)
  private static final com.aps.grpc.proto.ConvergencePoint DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.aps.grpc.proto.ConvergencePoint();
  }

  public static com.aps.grpc.proto.ConvergencePoint getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ConvergencePoint>
      PARSER = new com.google.protobuf.AbstractParser<ConvergencePoint>() {
    @java.lang.Override
    public ConvergencePoint parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ConvergencePoint> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ConvergencePoint> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.aps.grpc.proto.ConvergencePoint getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

