// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aps.proto

// Protobuf Java Version: 3.25.2
package com.aps.grpc.proto;

public interface ConvergencePointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aps.v1.ConvergencePoint)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 时间点（毫秒）
   * </pre>
   *
   * <code>int64 t_ms = 1;</code>
   * @return The tMs.
   */
  long getTMs();

  /**
   * <pre>
   * 当前最优成本
   * </pre>
   *
   * <code>double best_cost = 2;</code>
   * @return The bestCost.
   */
  double getBestCost();
}
