// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aps.proto

// Protobuf Java Version: 3.25.2
package com.aps.grpc.proto;

public interface GetJobStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aps.v1.GetJobStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 任务ID
   * </pre>
   *
   * <code>string job_id = 1;</code>
   * @return The jobId.
   */
  java.lang.String getJobId();
  /**
   * <pre>
   * 任务ID
   * </pre>
   *
   * <code>string job_id = 1;</code>
   * @return The bytes for jobId.
   */
  com.google.protobuf.ByteString
      getJobIdBytes();
}
