// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aps.proto

// Protobuf Java Version: 3.25.2
package com.aps.grpc.proto;

public interface GetJobStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aps.v1.GetJobStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 任务ID
   * </pre>
   *
   * <code>string job_id = 1;</code>
   * @return The jobId.
   */
  java.lang.String getJobId();
  /**
   * <pre>
   * 任务ID
   * </pre>
   *
   * <code>string job_id = 1;</code>
   * @return The bytes for jobId.
   */
  com.google.protobuf.ByteString
      getJobIdBytes();

  /**
   * <pre>
   * 状态: QUEUED/RUNNING/COMPLETED/FAILED
   * </pre>
   *
   * <code>string status = 2;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <pre>
   * 状态: QUEUED/RUNNING/COMPLETED/FAILED
   * </pre>
   *
   * <code>string status = 2;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <pre>
   * 创建时间（Unix秒）
   * </pre>
   *
   * <code>int64 created_at = 3;</code>
   * @return The createdAt.
   */
  long getCreatedAt();

  /**
   * <pre>
   * 更新时间（Unix秒）
   * </pre>
   *
   * <code>int64 updated_at = 4;</code>
   * @return The updatedAt.
   */
  long getUpdatedAt();

  /**
   * <pre>
   * 求解结果（仅COMPLETED时有值）
   * </pre>
   *
   * <code>.aps.v1.SolveResponse result = 5;</code>
   * @return Whether the result field is set.
   */
  boolean hasResult();
  /**
   * <pre>
   * 求解结果（仅COMPLETED时有值）
   * </pre>
   *
   * <code>.aps.v1.SolveResponse result = 5;</code>
   * @return The result.
   */
  com.aps.grpc.proto.SolveResponse getResult();
  /**
   * <pre>
   * 求解结果（仅COMPLETED时有值）
   * </pre>
   *
   * <code>.aps.v1.SolveResponse result = 5;</code>
   */
  com.aps.grpc.proto.SolveResponseOrBuilder getResultOrBuilder();

  /**
   * <pre>
   * 错误信息（仅FAILED时有值）
   * </pre>
   *
   * <code>string error_message = 6;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <pre>
   * 错误信息（仅FAILED时有值）
   * </pre>
   *
   * <code>string error_message = 6;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <pre>
   * 引擎版本
   * </pre>
   *
   * <code>string engine_version = 7;</code>
   * @return The engineVersion.
   */
  java.lang.String getEngineVersion();
  /**
   * <pre>
   * 引擎版本
   * </pre>
   *
   * <code>string engine_version = 7;</code>
   * @return The bytes for engineVersion.
   */
  com.google.protobuf.ByteString
      getEngineVersionBytes();
}
