// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aps.proto

// Protobuf Java Version: 3.25.2
package com.aps.grpc.proto;

/**
 * Protobuf type {@code aps.v1.GetJobStatusResponse}
 */
public final class GetJobStatusResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:aps.v1.GetJobStatusResponse)
    GetJobStatusResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetJobStatusResponse.newBuilder() to construct.
  private GetJobStatusResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetJobStatusResponse() {
    jobId_ = "";
    status_ = "";
    errorMessage_ = "";
    engineVersion_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetJobStatusResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_GetJobStatusResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_GetJobStatusResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.aps.grpc.proto.GetJobStatusResponse.class, com.aps.grpc.proto.GetJobStatusResponse.Builder.class);
  }

  private int bitField0_;
  public static final int JOB_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object jobId_ = "";
  /**
   * <pre>
   * 任务ID
   * </pre>
   *
   * <code>string job_id = 1;</code>
   * @return The jobId.
   */
  @java.lang.Override
  public java.lang.String getJobId() {
    java.lang.Object ref = jobId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jobId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 任务ID
   * </pre>
   *
   * <code>string job_id = 1;</code>
   * @return The bytes for jobId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJobIdBytes() {
    java.lang.Object ref = jobId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jobId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object status_ = "";
  /**
   * <pre>
   * 状态: QUEUED/RUNNING/COMPLETED/FAILED
   * </pre>
   *
   * <code>string status = 2;</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 状态: QUEUED/RUNNING/COMPLETED/FAILED
   * </pre>
   *
   * <code>string status = 2;</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATED_AT_FIELD_NUMBER = 3;
  private long createdAt_ = 0L;
  /**
   * <pre>
   * 创建时间（Unix秒）
   * </pre>
   *
   * <code>int64 created_at = 3;</code>
   * @return The createdAt.
   */
  @java.lang.Override
  public long getCreatedAt() {
    return createdAt_;
  }

  public static final int UPDATED_AT_FIELD_NUMBER = 4;
  private long updatedAt_ = 0L;
  /**
   * <pre>
   * 更新时间（Unix秒）
   * </pre>
   *
   * <code>int64 updated_at = 4;</code>
   * @return The updatedAt.
   */
  @java.lang.Override
  public long getUpdatedAt() {
    return updatedAt_;
  }

  public static final int RESULT_FIELD_NUMBER = 5;
  private com.aps.grpc.proto.SolveResponse result_;
  /**
   * <pre>
   * 求解结果（仅COMPLETED时有值）
   * </pre>
   *
   * <code>.aps.v1.SolveResponse result = 5;</code>
   * @return Whether the result field is set.
   */
  @java.lang.Override
  public boolean hasResult() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * 求解结果（仅COMPLETED时有值）
   * </pre>
   *
   * <code>.aps.v1.SolveResponse result = 5;</code>
   * @return The result.
   */
  @java.lang.Override
  public com.aps.grpc.proto.SolveResponse getResult() {
    return result_ == null ? com.aps.grpc.proto.SolveResponse.getDefaultInstance() : result_;
  }
  /**
   * <pre>
   * 求解结果（仅COMPLETED时有值）
   * </pre>
   *
   * <code>.aps.v1.SolveResponse result = 5;</code>
   */
  @java.lang.Override
  public com.aps.grpc.proto.SolveResponseOrBuilder getResultOrBuilder() {
    return result_ == null ? com.aps.grpc.proto.SolveResponse.getDefaultInstance() : result_;
  }

  public static final int ERROR_MESSAGE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object errorMessage_ = "";
  /**
   * <pre>
   * 错误信息（仅FAILED时有值）
   * </pre>
   *
   * <code>string error_message = 6;</code>
   * @return The errorMessage.
   */
  @java.lang.Override
  public java.lang.String getErrorMessage() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errorMessage_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 错误信息（仅FAILED时有值）
   * </pre>
   *
   * <code>string error_message = 6;</code>
   * @return The bytes for errorMessage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorMessageBytes() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENGINE_VERSION_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object engineVersion_ = "";
  /**
   * <pre>
   * 引擎版本
   * </pre>
   *
   * <code>string engine_version = 7;</code>
   * @return The engineVersion.
   */
  @java.lang.Override
  public java.lang.String getEngineVersion() {
    java.lang.Object ref = engineVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      engineVersion_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 引擎版本
   * </pre>
   *
   * <code>string engine_version = 7;</code>
   * @return The bytes for engineVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEngineVersionBytes() {
    java.lang.Object ref = engineVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      engineVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(jobId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, jobId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, status_);
    }
    if (createdAt_ != 0L) {
      output.writeInt64(3, createdAt_);
    }
    if (updatedAt_ != 0L) {
      output.writeInt64(4, updatedAt_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(5, getResult());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errorMessage_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, errorMessage_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(engineVersion_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, engineVersion_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(jobId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, jobId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, status_);
    }
    if (createdAt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, createdAt_);
    }
    if (updatedAt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, updatedAt_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getResult());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errorMessage_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, errorMessage_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(engineVersion_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, engineVersion_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.aps.grpc.proto.GetJobStatusResponse)) {
      return super.equals(obj);
    }
    com.aps.grpc.proto.GetJobStatusResponse other = (com.aps.grpc.proto.GetJobStatusResponse) obj;

    if (!getJobId()
        .equals(other.getJobId())) return false;
    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (getCreatedAt()
        != other.getCreatedAt()) return false;
    if (getUpdatedAt()
        != other.getUpdatedAt()) return false;
    if (hasResult() != other.hasResult()) return false;
    if (hasResult()) {
      if (!getResult()
          .equals(other.getResult())) return false;
    }
    if (!getErrorMessage()
        .equals(other.getErrorMessage())) return false;
    if (!getEngineVersion()
        .equals(other.getEngineVersion())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + JOB_ID_FIELD_NUMBER;
    hash = (53 * hash) + getJobId().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreatedAt());
    hash = (37 * hash) + UPDATED_AT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUpdatedAt());
    if (hasResult()) {
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult().hashCode();
    }
    hash = (37 * hash) + ERROR_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorMessage().hashCode();
    hash = (37 * hash) + ENGINE_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getEngineVersion().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.aps.grpc.proto.GetJobStatusResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aps.grpc.proto.GetJobStatusResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aps.grpc.proto.GetJobStatusResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aps.grpc.proto.GetJobStatusResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aps.grpc.proto.GetJobStatusResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aps.grpc.proto.GetJobStatusResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aps.grpc.proto.GetJobStatusResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aps.grpc.proto.GetJobStatusResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.aps.grpc.proto.GetJobStatusResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.aps.grpc.proto.GetJobStatusResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aps.grpc.proto.GetJobStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aps.grpc.proto.GetJobStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.aps.grpc.proto.GetJobStatusResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code aps.v1.GetJobStatusResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:aps.v1.GetJobStatusResponse)
      com.aps.grpc.proto.GetJobStatusResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_GetJobStatusResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_GetJobStatusResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aps.grpc.proto.GetJobStatusResponse.class, com.aps.grpc.proto.GetJobStatusResponse.Builder.class);
    }

    // Construct using com.aps.grpc.proto.GetJobStatusResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getResultFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      jobId_ = "";
      status_ = "";
      createdAt_ = 0L;
      updatedAt_ = 0L;
      result_ = null;
      if (resultBuilder_ != null) {
        resultBuilder_.dispose();
        resultBuilder_ = null;
      }
      errorMessage_ = "";
      engineVersion_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_GetJobStatusResponse_descriptor;
    }

    @java.lang.Override
    public com.aps.grpc.proto.GetJobStatusResponse getDefaultInstanceForType() {
      return com.aps.grpc.proto.GetJobStatusResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.aps.grpc.proto.GetJobStatusResponse build() {
      com.aps.grpc.proto.GetJobStatusResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.aps.grpc.proto.GetJobStatusResponse buildPartial() {
      com.aps.grpc.proto.GetJobStatusResponse result = new com.aps.grpc.proto.GetJobStatusResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.aps.grpc.proto.GetJobStatusResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.jobId_ = jobId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.createdAt_ = createdAt_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.updatedAt_ = updatedAt_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.result_ = resultBuilder_ == null
            ? result_
            : resultBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.errorMessage_ = errorMessage_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.engineVersion_ = engineVersion_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.aps.grpc.proto.GetJobStatusResponse) {
        return mergeFrom((com.aps.grpc.proto.GetJobStatusResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.aps.grpc.proto.GetJobStatusResponse other) {
      if (other == com.aps.grpc.proto.GetJobStatusResponse.getDefaultInstance()) return this;
      if (!other.getJobId().isEmpty()) {
        jobId_ = other.jobId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getCreatedAt() != 0L) {
        setCreatedAt(other.getCreatedAt());
      }
      if (other.getUpdatedAt() != 0L) {
        setUpdatedAt(other.getUpdatedAt());
      }
      if (other.hasResult()) {
        mergeResult(other.getResult());
      }
      if (!other.getErrorMessage().isEmpty()) {
        errorMessage_ = other.errorMessage_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getEngineVersion().isEmpty()) {
        engineVersion_ = other.engineVersion_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              jobId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              status_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              createdAt_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              updatedAt_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              input.readMessage(
                  getResultFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              errorMessage_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              engineVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object jobId_ = "";
    /**
     * <pre>
     * 任务ID
     * </pre>
     *
     * <code>string job_id = 1;</code>
     * @return The jobId.
     */
    public java.lang.String getJobId() {
      java.lang.Object ref = jobId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jobId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 任务ID
     * </pre>
     *
     * <code>string job_id = 1;</code>
     * @return The bytes for jobId.
     */
    public com.google.protobuf.ByteString
        getJobIdBytes() {
      java.lang.Object ref = jobId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jobId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 任务ID
     * </pre>
     *
     * <code>string job_id = 1;</code>
     * @param value The jobId to set.
     * @return This builder for chaining.
     */
    public Builder setJobId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      jobId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 任务ID
     * </pre>
     *
     * <code>string job_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearJobId() {
      jobId_ = getDefaultInstance().getJobId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 任务ID
     * </pre>
     *
     * <code>string job_id = 1;</code>
     * @param value The bytes for jobId to set.
     * @return This builder for chaining.
     */
    public Builder setJobIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      jobId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <pre>
     * 状态: QUEUED/RUNNING/COMPLETED/FAILED
     * </pre>
     *
     * <code>string status = 2;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 状态: QUEUED/RUNNING/COMPLETED/FAILED
     * </pre>
     *
     * <code>string status = 2;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 状态: QUEUED/RUNNING/COMPLETED/FAILED
     * </pre>
     *
     * <code>string status = 2;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      status_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 状态: QUEUED/RUNNING/COMPLETED/FAILED
     * </pre>
     *
     * <code>string status = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      status_ = getDefaultInstance().getStatus();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 状态: QUEUED/RUNNING/COMPLETED/FAILED
     * </pre>
     *
     * <code>string status = 2;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      status_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private long createdAt_ ;
    /**
     * <pre>
     * 创建时间（Unix秒）
     * </pre>
     *
     * <code>int64 created_at = 3;</code>
     * @return The createdAt.
     */
    @java.lang.Override
    public long getCreatedAt() {
      return createdAt_;
    }
    /**
     * <pre>
     * 创建时间（Unix秒）
     * </pre>
     *
     * <code>int64 created_at = 3;</code>
     * @param value The createdAt to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedAt(long value) {

      createdAt_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 创建时间（Unix秒）
     * </pre>
     *
     * <code>int64 created_at = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreatedAt() {
      bitField0_ = (bitField0_ & ~0x00000004);
      createdAt_ = 0L;
      onChanged();
      return this;
    }

    private long updatedAt_ ;
    /**
     * <pre>
     * 更新时间（Unix秒）
     * </pre>
     *
     * <code>int64 updated_at = 4;</code>
     * @return The updatedAt.
     */
    @java.lang.Override
    public long getUpdatedAt() {
      return updatedAt_;
    }
    /**
     * <pre>
     * 更新时间（Unix秒）
     * </pre>
     *
     * <code>int64 updated_at = 4;</code>
     * @param value The updatedAt to set.
     * @return This builder for chaining.
     */
    public Builder setUpdatedAt(long value) {

      updatedAt_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 更新时间（Unix秒）
     * </pre>
     *
     * <code>int64 updated_at = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdatedAt() {
      bitField0_ = (bitField0_ & ~0x00000008);
      updatedAt_ = 0L;
      onChanged();
      return this;
    }

    private com.aps.grpc.proto.SolveResponse result_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.aps.grpc.proto.SolveResponse, com.aps.grpc.proto.SolveResponse.Builder, com.aps.grpc.proto.SolveResponseOrBuilder> resultBuilder_;
    /**
     * <pre>
     * 求解结果（仅COMPLETED时有值）
     * </pre>
     *
     * <code>.aps.v1.SolveResponse result = 5;</code>
     * @return Whether the result field is set.
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * 求解结果（仅COMPLETED时有值）
     * </pre>
     *
     * <code>.aps.v1.SolveResponse result = 5;</code>
     * @return The result.
     */
    public com.aps.grpc.proto.SolveResponse getResult() {
      if (resultBuilder_ == null) {
        return result_ == null ? com.aps.grpc.proto.SolveResponse.getDefaultInstance() : result_;
      } else {
        return resultBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 求解结果（仅COMPLETED时有值）
     * </pre>
     *
     * <code>.aps.v1.SolveResponse result = 5;</code>
     */
    public Builder setResult(com.aps.grpc.proto.SolveResponse value) {
      if (resultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
      } else {
        resultBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 求解结果（仅COMPLETED时有值）
     * </pre>
     *
     * <code>.aps.v1.SolveResponse result = 5;</code>
     */
    public Builder setResult(
        com.aps.grpc.proto.SolveResponse.Builder builderForValue) {
      if (resultBuilder_ == null) {
        result_ = builderForValue.build();
      } else {
        resultBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 求解结果（仅COMPLETED时有值）
     * </pre>
     *
     * <code>.aps.v1.SolveResponse result = 5;</code>
     */
    public Builder mergeResult(com.aps.grpc.proto.SolveResponse value) {
      if (resultBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          result_ != null &&
          result_ != com.aps.grpc.proto.SolveResponse.getDefaultInstance()) {
          getResultBuilder().mergeFrom(value);
        } else {
          result_ = value;
        }
      } else {
        resultBuilder_.mergeFrom(value);
      }
      if (result_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * 求解结果（仅COMPLETED时有值）
     * </pre>
     *
     * <code>.aps.v1.SolveResponse result = 5;</code>
     */
    public Builder clearResult() {
      bitField0_ = (bitField0_ & ~0x00000010);
      result_ = null;
      if (resultBuilder_ != null) {
        resultBuilder_.dispose();
        resultBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 求解结果（仅COMPLETED时有值）
     * </pre>
     *
     * <code>.aps.v1.SolveResponse result = 5;</code>
     */
    public com.aps.grpc.proto.SolveResponse.Builder getResultBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getResultFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 求解结果（仅COMPLETED时有值）
     * </pre>
     *
     * <code>.aps.v1.SolveResponse result = 5;</code>
     */
    public com.aps.grpc.proto.SolveResponseOrBuilder getResultOrBuilder() {
      if (resultBuilder_ != null) {
        return resultBuilder_.getMessageOrBuilder();
      } else {
        return result_ == null ?
            com.aps.grpc.proto.SolveResponse.getDefaultInstance() : result_;
      }
    }
    /**
     * <pre>
     * 求解结果（仅COMPLETED时有值）
     * </pre>
     *
     * <code>.aps.v1.SolveResponse result = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.aps.grpc.proto.SolveResponse, com.aps.grpc.proto.SolveResponse.Builder, com.aps.grpc.proto.SolveResponseOrBuilder> 
        getResultFieldBuilder() {
      if (resultBuilder_ == null) {
        resultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.aps.grpc.proto.SolveResponse, com.aps.grpc.proto.SolveResponse.Builder, com.aps.grpc.proto.SolveResponseOrBuilder>(
                getResult(),
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      return resultBuilder_;
    }

    private java.lang.Object errorMessage_ = "";
    /**
     * <pre>
     * 错误信息（仅FAILED时有值）
     * </pre>
     *
     * <code>string error_message = 6;</code>
     * @return The errorMessage.
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 错误信息（仅FAILED时有值）
     * </pre>
     *
     * <code>string error_message = 6;</code>
     * @return The bytes for errorMessage.
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 错误信息（仅FAILED时有值）
     * </pre>
     *
     * <code>string error_message = 6;</code>
     * @param value The errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      errorMessage_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 错误信息（仅FAILED时有值）
     * </pre>
     *
     * <code>string error_message = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorMessage() {
      errorMessage_ = getDefaultInstance().getErrorMessage();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 错误信息（仅FAILED时有值）
     * </pre>
     *
     * <code>string error_message = 6;</code>
     * @param value The bytes for errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      errorMessage_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object engineVersion_ = "";
    /**
     * <pre>
     * 引擎版本
     * </pre>
     *
     * <code>string engine_version = 7;</code>
     * @return The engineVersion.
     */
    public java.lang.String getEngineVersion() {
      java.lang.Object ref = engineVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        engineVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 引擎版本
     * </pre>
     *
     * <code>string engine_version = 7;</code>
     * @return The bytes for engineVersion.
     */
    public com.google.protobuf.ByteString
        getEngineVersionBytes() {
      java.lang.Object ref = engineVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        engineVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 引擎版本
     * </pre>
     *
     * <code>string engine_version = 7;</code>
     * @param value The engineVersion to set.
     * @return This builder for chaining.
     */
    public Builder setEngineVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      engineVersion_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 引擎版本
     * </pre>
     *
     * <code>string engine_version = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearEngineVersion() {
      engineVersion_ = getDefaultInstance().getEngineVersion();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 引擎版本
     * </pre>
     *
     * <code>string engine_version = 7;</code>
     * @param value The bytes for engineVersion to set.
     * @return This builder for chaining.
     */
    public Builder setEngineVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      engineVersion_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:aps.v1.GetJobStatusResponse)
  }

  // @@protoc_insertion_point(class_scope:aps.v1.GetJobStatusResponse)
  private static final com.aps.grpc.proto.GetJobStatusResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.aps.grpc.proto.GetJobStatusResponse();
  }

  public static com.aps.grpc.proto.GetJobStatusResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetJobStatusResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetJobStatusResponse>() {
    @java.lang.Override
    public GetJobStatusResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetJobStatusResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetJobStatusResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.aps.grpc.proto.GetJobStatusResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

