// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aps.proto

// Protobuf Java Version: 3.25.2
package com.aps.grpc.proto;

/**
 * Protobuf type {@code aps.v1.Job}
 */
public final class Job extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:aps.v1.Job)
    JobOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Job.newBuilder() to construct.
  private Job(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Job() {
    vin_ = "";
    moldCode_ = "";
    weldingFixture_ = "";
    color_ = "";
    config_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Job();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_Job_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_Job_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.aps.grpc.proto.Job.class, com.aps.grpc.proto.Job.Builder.class);
  }

  public static final int VIN_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object vin_ = "";
  /**
   * <pre>
   * 车辆识别码/订单号
   * </pre>
   *
   * <code>string vin = 1;</code>
   * @return The vin.
   */
  @java.lang.Override
  public java.lang.String getVin() {
    java.lang.Object ref = vin_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      vin_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 车辆识别码/订单号
   * </pre>
   *
   * <code>string vin = 1;</code>
   * @return The bytes for vin.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVinBytes() {
    java.lang.Object ref = vin_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      vin_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DUE_EPOCH_MS_FIELD_NUMBER = 2;
  private long dueEpochMs_ = 0L;
  /**
   * <pre>
   * 交期（毫秒时间戳）
   * </pre>
   *
   * <code>int64 due_epoch_ms = 2;</code>
   * @return The dueEpochMs.
   */
  @java.lang.Override
  public long getDueEpochMs() {
    return dueEpochMs_;
  }

  public static final int STAMPING_MINUTES_FIELD_NUMBER = 3;
  private int stampingMinutes_ = 0;
  /**
   * <pre>
   * 冲压工时（分钟）
   * </pre>
   *
   * <code>int32 stamping_minutes = 3;</code>
   * @return The stampingMinutes.
   */
  @java.lang.Override
  public int getStampingMinutes() {
    return stampingMinutes_;
  }

  public static final int WELDING_MINUTES_FIELD_NUMBER = 4;
  private int weldingMinutes_ = 0;
  /**
   * <pre>
   * 焊装工时（分钟）
   * </pre>
   *
   * <code>int32 welding_minutes = 4;</code>
   * @return The weldingMinutes.
   */
  @java.lang.Override
  public int getWeldingMinutes() {
    return weldingMinutes_;
  }

  public static final int PAINTING_MINUTES_FIELD_NUMBER = 5;
  private int paintingMinutes_ = 0;
  /**
   * <pre>
   * 涂装工时（分钟）
   * </pre>
   *
   * <code>int32 painting_minutes = 5;</code>
   * @return The paintingMinutes.
   */
  @java.lang.Override
  public int getPaintingMinutes() {
    return paintingMinutes_;
  }

  public static final int ASSEMBLE_MINUTES_FIELD_NUMBER = 6;
  private int assembleMinutes_ = 0;
  /**
   * <pre>
   * 总装工时（分钟）
   * </pre>
   *
   * <code>int32 assemble_minutes = 6;</code>
   * @return The assembleMinutes.
   */
  @java.lang.Override
  public int getAssembleMinutes() {
    return assembleMinutes_;
  }

  public static final int MOLD_CODE_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object moldCode_ = "";
  /**
   * <pre>
   * 模具编码（冲压换型键）
   * </pre>
   *
   * <code>string mold_code = 7;</code>
   * @return The moldCode.
   */
  @java.lang.Override
  public java.lang.String getMoldCode() {
    java.lang.Object ref = moldCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      moldCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 模具编码（冲压换型键）
   * </pre>
   *
   * <code>string mold_code = 7;</code>
   * @return The bytes for moldCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMoldCodeBytes() {
    java.lang.Object ref = moldCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      moldCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WELDING_FIXTURE_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object weldingFixture_ = "";
  /**
   * <pre>
   * 焊装夹具（焊装换型键）
   * </pre>
   *
   * <code>string welding_fixture = 8;</code>
   * @return The weldingFixture.
   */
  @java.lang.Override
  public java.lang.String getWeldingFixture() {
    java.lang.Object ref = weldingFixture_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      weldingFixture_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 焊装夹具（焊装换型键）
   * </pre>
   *
   * <code>string welding_fixture = 8;</code>
   * @return The bytes for weldingFixture.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWeldingFixtureBytes() {
    java.lang.Object ref = weldingFixture_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      weldingFixture_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COLOR_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object color_ = "";
  /**
   * <pre>
   * 颜色编码（涂装换型键）
   * </pre>
   *
   * <code>string color = 9;</code>
   * @return The color.
   */
  @java.lang.Override
  public java.lang.String getColor() {
    java.lang.Object ref = color_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      color_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 颜色编码（涂装换型键）
   * </pre>
   *
   * <code>string color = 9;</code>
   * @return The bytes for color.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getColorBytes() {
    java.lang.Object ref = color_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      color_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONFIG_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object config_ = "";
  /**
   * <pre>
   * 配置编码（总装换型键）
   * </pre>
   *
   * <code>string config = 10;</code>
   * @return The config.
   */
  @java.lang.Override
  public java.lang.String getConfig() {
    java.lang.Object ref = config_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      config_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 配置编码（总装换型键）
   * </pre>
   *
   * <code>string config = 10;</code>
   * @return The bytes for config.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConfigBytes() {
    java.lang.Object ref = config_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      config_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENERGY_SCORE_FIELD_NUMBER = 11;
  private double energyScore_ = 0D;
  /**
   * <pre>
   * 能耗分值
   * </pre>
   *
   * <code>double energy_score = 11;</code>
   * @return The energyScore.
   */
  @java.lang.Override
  public double getEnergyScore() {
    return energyScore_;
  }

  public static final int EMISSION_SCORE_FIELD_NUMBER = 12;
  private double emissionScore_ = 0D;
  /**
   * <pre>
   * 排放分值
   * </pre>
   *
   * <code>double emission_score = 12;</code>
   * @return The emissionScore.
   */
  @java.lang.Override
  public double getEmissionScore() {
    return emissionScore_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(vin_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, vin_);
    }
    if (dueEpochMs_ != 0L) {
      output.writeInt64(2, dueEpochMs_);
    }
    if (stampingMinutes_ != 0) {
      output.writeInt32(3, stampingMinutes_);
    }
    if (weldingMinutes_ != 0) {
      output.writeInt32(4, weldingMinutes_);
    }
    if (paintingMinutes_ != 0) {
      output.writeInt32(5, paintingMinutes_);
    }
    if (assembleMinutes_ != 0) {
      output.writeInt32(6, assembleMinutes_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(moldCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, moldCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(weldingFixture_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, weldingFixture_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(color_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, color_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(config_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, config_);
    }
    if (java.lang.Double.doubleToRawLongBits(energyScore_) != 0) {
      output.writeDouble(11, energyScore_);
    }
    if (java.lang.Double.doubleToRawLongBits(emissionScore_) != 0) {
      output.writeDouble(12, emissionScore_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(vin_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, vin_);
    }
    if (dueEpochMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, dueEpochMs_);
    }
    if (stampingMinutes_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, stampingMinutes_);
    }
    if (weldingMinutes_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, weldingMinutes_);
    }
    if (paintingMinutes_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, paintingMinutes_);
    }
    if (assembleMinutes_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, assembleMinutes_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(moldCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, moldCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(weldingFixture_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, weldingFixture_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(color_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, color_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(config_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, config_);
    }
    if (java.lang.Double.doubleToRawLongBits(energyScore_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(11, energyScore_);
    }
    if (java.lang.Double.doubleToRawLongBits(emissionScore_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(12, emissionScore_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.aps.grpc.proto.Job)) {
      return super.equals(obj);
    }
    com.aps.grpc.proto.Job other = (com.aps.grpc.proto.Job) obj;

    if (!getVin()
        .equals(other.getVin())) return false;
    if (getDueEpochMs()
        != other.getDueEpochMs()) return false;
    if (getStampingMinutes()
        != other.getStampingMinutes()) return false;
    if (getWeldingMinutes()
        != other.getWeldingMinutes()) return false;
    if (getPaintingMinutes()
        != other.getPaintingMinutes()) return false;
    if (getAssembleMinutes()
        != other.getAssembleMinutes()) return false;
    if (!getMoldCode()
        .equals(other.getMoldCode())) return false;
    if (!getWeldingFixture()
        .equals(other.getWeldingFixture())) return false;
    if (!getColor()
        .equals(other.getColor())) return false;
    if (!getConfig()
        .equals(other.getConfig())) return false;
    if (java.lang.Double.doubleToLongBits(getEnergyScore())
        != java.lang.Double.doubleToLongBits(
            other.getEnergyScore())) return false;
    if (java.lang.Double.doubleToLongBits(getEmissionScore())
        != java.lang.Double.doubleToLongBits(
            other.getEmissionScore())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VIN_FIELD_NUMBER;
    hash = (53 * hash) + getVin().hashCode();
    hash = (37 * hash) + DUE_EPOCH_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDueEpochMs());
    hash = (37 * hash) + STAMPING_MINUTES_FIELD_NUMBER;
    hash = (53 * hash) + getStampingMinutes();
    hash = (37 * hash) + WELDING_MINUTES_FIELD_NUMBER;
    hash = (53 * hash) + getWeldingMinutes();
    hash = (37 * hash) + PAINTING_MINUTES_FIELD_NUMBER;
    hash = (53 * hash) + getPaintingMinutes();
    hash = (37 * hash) + ASSEMBLE_MINUTES_FIELD_NUMBER;
    hash = (53 * hash) + getAssembleMinutes();
    hash = (37 * hash) + MOLD_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getMoldCode().hashCode();
    hash = (37 * hash) + WELDING_FIXTURE_FIELD_NUMBER;
    hash = (53 * hash) + getWeldingFixture().hashCode();
    hash = (37 * hash) + COLOR_FIELD_NUMBER;
    hash = (53 * hash) + getColor().hashCode();
    hash = (37 * hash) + CONFIG_FIELD_NUMBER;
    hash = (53 * hash) + getConfig().hashCode();
    hash = (37 * hash) + ENERGY_SCORE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getEnergyScore()));
    hash = (37 * hash) + EMISSION_SCORE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getEmissionScore()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.aps.grpc.proto.Job parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aps.grpc.proto.Job parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aps.grpc.proto.Job parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aps.grpc.proto.Job parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aps.grpc.proto.Job parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aps.grpc.proto.Job parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aps.grpc.proto.Job parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aps.grpc.proto.Job parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.aps.grpc.proto.Job parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.aps.grpc.proto.Job parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aps.grpc.proto.Job parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aps.grpc.proto.Job parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.aps.grpc.proto.Job prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code aps.v1.Job}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:aps.v1.Job)
      com.aps.grpc.proto.JobOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_Job_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_Job_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aps.grpc.proto.Job.class, com.aps.grpc.proto.Job.Builder.class);
    }

    // Construct using com.aps.grpc.proto.Job.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      vin_ = "";
      dueEpochMs_ = 0L;
      stampingMinutes_ = 0;
      weldingMinutes_ = 0;
      paintingMinutes_ = 0;
      assembleMinutes_ = 0;
      moldCode_ = "";
      weldingFixture_ = "";
      color_ = "";
      config_ = "";
      energyScore_ = 0D;
      emissionScore_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_Job_descriptor;
    }

    @java.lang.Override
    public com.aps.grpc.proto.Job getDefaultInstanceForType() {
      return com.aps.grpc.proto.Job.getDefaultInstance();
    }

    @java.lang.Override
    public com.aps.grpc.proto.Job build() {
      com.aps.grpc.proto.Job result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.aps.grpc.proto.Job buildPartial() {
      com.aps.grpc.proto.Job result = new com.aps.grpc.proto.Job(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.aps.grpc.proto.Job result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.vin_ = vin_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.dueEpochMs_ = dueEpochMs_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.stampingMinutes_ = stampingMinutes_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.weldingMinutes_ = weldingMinutes_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.paintingMinutes_ = paintingMinutes_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.assembleMinutes_ = assembleMinutes_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.moldCode_ = moldCode_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.weldingFixture_ = weldingFixture_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.color_ = color_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.config_ = config_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.energyScore_ = energyScore_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.emissionScore_ = emissionScore_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.aps.grpc.proto.Job) {
        return mergeFrom((com.aps.grpc.proto.Job)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.aps.grpc.proto.Job other) {
      if (other == com.aps.grpc.proto.Job.getDefaultInstance()) return this;
      if (!other.getVin().isEmpty()) {
        vin_ = other.vin_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getDueEpochMs() != 0L) {
        setDueEpochMs(other.getDueEpochMs());
      }
      if (other.getStampingMinutes() != 0) {
        setStampingMinutes(other.getStampingMinutes());
      }
      if (other.getWeldingMinutes() != 0) {
        setWeldingMinutes(other.getWeldingMinutes());
      }
      if (other.getPaintingMinutes() != 0) {
        setPaintingMinutes(other.getPaintingMinutes());
      }
      if (other.getAssembleMinutes() != 0) {
        setAssembleMinutes(other.getAssembleMinutes());
      }
      if (!other.getMoldCode().isEmpty()) {
        moldCode_ = other.moldCode_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getWeldingFixture().isEmpty()) {
        weldingFixture_ = other.weldingFixture_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getColor().isEmpty()) {
        color_ = other.color_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (!other.getConfig().isEmpty()) {
        config_ = other.config_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (other.getEnergyScore() != 0D) {
        setEnergyScore(other.getEnergyScore());
      }
      if (other.getEmissionScore() != 0D) {
        setEmissionScore(other.getEmissionScore());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              vin_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              dueEpochMs_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              stampingMinutes_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              weldingMinutes_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              paintingMinutes_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              assembleMinutes_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              moldCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              weldingFixture_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              color_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              config_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 89: {
              energyScore_ = input.readDouble();
              bitField0_ |= 0x00000400;
              break;
            } // case 89
            case 97: {
              emissionScore_ = input.readDouble();
              bitField0_ |= 0x00000800;
              break;
            } // case 97
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object vin_ = "";
    /**
     * <pre>
     * 车辆识别码/订单号
     * </pre>
     *
     * <code>string vin = 1;</code>
     * @return The vin.
     */
    public java.lang.String getVin() {
      java.lang.Object ref = vin_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vin_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 车辆识别码/订单号
     * </pre>
     *
     * <code>string vin = 1;</code>
     * @return The bytes for vin.
     */
    public com.google.protobuf.ByteString
        getVinBytes() {
      java.lang.Object ref = vin_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 车辆识别码/订单号
     * </pre>
     *
     * <code>string vin = 1;</code>
     * @param value The vin to set.
     * @return This builder for chaining.
     */
    public Builder setVin(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      vin_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 车辆识别码/订单号
     * </pre>
     *
     * <code>string vin = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVin() {
      vin_ = getDefaultInstance().getVin();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 车辆识别码/订单号
     * </pre>
     *
     * <code>string vin = 1;</code>
     * @param value The bytes for vin to set.
     * @return This builder for chaining.
     */
    public Builder setVinBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      vin_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private long dueEpochMs_ ;
    /**
     * <pre>
     * 交期（毫秒时间戳）
     * </pre>
     *
     * <code>int64 due_epoch_ms = 2;</code>
     * @return The dueEpochMs.
     */
    @java.lang.Override
    public long getDueEpochMs() {
      return dueEpochMs_;
    }
    /**
     * <pre>
     * 交期（毫秒时间戳）
     * </pre>
     *
     * <code>int64 due_epoch_ms = 2;</code>
     * @param value The dueEpochMs to set.
     * @return This builder for chaining.
     */
    public Builder setDueEpochMs(long value) {

      dueEpochMs_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 交期（毫秒时间戳）
     * </pre>
     *
     * <code>int64 due_epoch_ms = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDueEpochMs() {
      bitField0_ = (bitField0_ & ~0x00000002);
      dueEpochMs_ = 0L;
      onChanged();
      return this;
    }

    private int stampingMinutes_ ;
    /**
     * <pre>
     * 冲压工时（分钟）
     * </pre>
     *
     * <code>int32 stamping_minutes = 3;</code>
     * @return The stampingMinutes.
     */
    @java.lang.Override
    public int getStampingMinutes() {
      return stampingMinutes_;
    }
    /**
     * <pre>
     * 冲压工时（分钟）
     * </pre>
     *
     * <code>int32 stamping_minutes = 3;</code>
     * @param value The stampingMinutes to set.
     * @return This builder for chaining.
     */
    public Builder setStampingMinutes(int value) {

      stampingMinutes_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 冲压工时（分钟）
     * </pre>
     *
     * <code>int32 stamping_minutes = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStampingMinutes() {
      bitField0_ = (bitField0_ & ~0x00000004);
      stampingMinutes_ = 0;
      onChanged();
      return this;
    }

    private int weldingMinutes_ ;
    /**
     * <pre>
     * 焊装工时（分钟）
     * </pre>
     *
     * <code>int32 welding_minutes = 4;</code>
     * @return The weldingMinutes.
     */
    @java.lang.Override
    public int getWeldingMinutes() {
      return weldingMinutes_;
    }
    /**
     * <pre>
     * 焊装工时（分钟）
     * </pre>
     *
     * <code>int32 welding_minutes = 4;</code>
     * @param value The weldingMinutes to set.
     * @return This builder for chaining.
     */
    public Builder setWeldingMinutes(int value) {

      weldingMinutes_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 焊装工时（分钟）
     * </pre>
     *
     * <code>int32 welding_minutes = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearWeldingMinutes() {
      bitField0_ = (bitField0_ & ~0x00000008);
      weldingMinutes_ = 0;
      onChanged();
      return this;
    }

    private int paintingMinutes_ ;
    /**
     * <pre>
     * 涂装工时（分钟）
     * </pre>
     *
     * <code>int32 painting_minutes = 5;</code>
     * @return The paintingMinutes.
     */
    @java.lang.Override
    public int getPaintingMinutes() {
      return paintingMinutes_;
    }
    /**
     * <pre>
     * 涂装工时（分钟）
     * </pre>
     *
     * <code>int32 painting_minutes = 5;</code>
     * @param value The paintingMinutes to set.
     * @return This builder for chaining.
     */
    public Builder setPaintingMinutes(int value) {

      paintingMinutes_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 涂装工时（分钟）
     * </pre>
     *
     * <code>int32 painting_minutes = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPaintingMinutes() {
      bitField0_ = (bitField0_ & ~0x00000010);
      paintingMinutes_ = 0;
      onChanged();
      return this;
    }

    private int assembleMinutes_ ;
    /**
     * <pre>
     * 总装工时（分钟）
     * </pre>
     *
     * <code>int32 assemble_minutes = 6;</code>
     * @return The assembleMinutes.
     */
    @java.lang.Override
    public int getAssembleMinutes() {
      return assembleMinutes_;
    }
    /**
     * <pre>
     * 总装工时（分钟）
     * </pre>
     *
     * <code>int32 assemble_minutes = 6;</code>
     * @param value The assembleMinutes to set.
     * @return This builder for chaining.
     */
    public Builder setAssembleMinutes(int value) {

      assembleMinutes_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 总装工时（分钟）
     * </pre>
     *
     * <code>int32 assemble_minutes = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearAssembleMinutes() {
      bitField0_ = (bitField0_ & ~0x00000020);
      assembleMinutes_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object moldCode_ = "";
    /**
     * <pre>
     * 模具编码（冲压换型键）
     * </pre>
     *
     * <code>string mold_code = 7;</code>
     * @return The moldCode.
     */
    public java.lang.String getMoldCode() {
      java.lang.Object ref = moldCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        moldCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 模具编码（冲压换型键）
     * </pre>
     *
     * <code>string mold_code = 7;</code>
     * @return The bytes for moldCode.
     */
    public com.google.protobuf.ByteString
        getMoldCodeBytes() {
      java.lang.Object ref = moldCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        moldCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 模具编码（冲压换型键）
     * </pre>
     *
     * <code>string mold_code = 7;</code>
     * @param value The moldCode to set.
     * @return This builder for chaining.
     */
    public Builder setMoldCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      moldCode_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 模具编码（冲压换型键）
     * </pre>
     *
     * <code>string mold_code = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearMoldCode() {
      moldCode_ = getDefaultInstance().getMoldCode();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 模具编码（冲压换型键）
     * </pre>
     *
     * <code>string mold_code = 7;</code>
     * @param value The bytes for moldCode to set.
     * @return This builder for chaining.
     */
    public Builder setMoldCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      moldCode_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object weldingFixture_ = "";
    /**
     * <pre>
     * 焊装夹具（焊装换型键）
     * </pre>
     *
     * <code>string welding_fixture = 8;</code>
     * @return The weldingFixture.
     */
    public java.lang.String getWeldingFixture() {
      java.lang.Object ref = weldingFixture_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        weldingFixture_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 焊装夹具（焊装换型键）
     * </pre>
     *
     * <code>string welding_fixture = 8;</code>
     * @return The bytes for weldingFixture.
     */
    public com.google.protobuf.ByteString
        getWeldingFixtureBytes() {
      java.lang.Object ref = weldingFixture_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        weldingFixture_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 焊装夹具（焊装换型键）
     * </pre>
     *
     * <code>string welding_fixture = 8;</code>
     * @param value The weldingFixture to set.
     * @return This builder for chaining.
     */
    public Builder setWeldingFixture(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      weldingFixture_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 焊装夹具（焊装换型键）
     * </pre>
     *
     * <code>string welding_fixture = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearWeldingFixture() {
      weldingFixture_ = getDefaultInstance().getWeldingFixture();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 焊装夹具（焊装换型键）
     * </pre>
     *
     * <code>string welding_fixture = 8;</code>
     * @param value The bytes for weldingFixture to set.
     * @return This builder for chaining.
     */
    public Builder setWeldingFixtureBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      weldingFixture_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object color_ = "";
    /**
     * <pre>
     * 颜色编码（涂装换型键）
     * </pre>
     *
     * <code>string color = 9;</code>
     * @return The color.
     */
    public java.lang.String getColor() {
      java.lang.Object ref = color_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        color_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 颜色编码（涂装换型键）
     * </pre>
     *
     * <code>string color = 9;</code>
     * @return The bytes for color.
     */
    public com.google.protobuf.ByteString
        getColorBytes() {
      java.lang.Object ref = color_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        color_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 颜色编码（涂装换型键）
     * </pre>
     *
     * <code>string color = 9;</code>
     * @param value The color to set.
     * @return This builder for chaining.
     */
    public Builder setColor(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      color_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 颜色编码（涂装换型键）
     * </pre>
     *
     * <code>string color = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearColor() {
      color_ = getDefaultInstance().getColor();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 颜色编码（涂装换型键）
     * </pre>
     *
     * <code>string color = 9;</code>
     * @param value The bytes for color to set.
     * @return This builder for chaining.
     */
    public Builder setColorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      color_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object config_ = "";
    /**
     * <pre>
     * 配置编码（总装换型键）
     * </pre>
     *
     * <code>string config = 10;</code>
     * @return The config.
     */
    public java.lang.String getConfig() {
      java.lang.Object ref = config_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        config_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 配置编码（总装换型键）
     * </pre>
     *
     * <code>string config = 10;</code>
     * @return The bytes for config.
     */
    public com.google.protobuf.ByteString
        getConfigBytes() {
      java.lang.Object ref = config_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        config_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 配置编码（总装换型键）
     * </pre>
     *
     * <code>string config = 10;</code>
     * @param value The config to set.
     * @return This builder for chaining.
     */
    public Builder setConfig(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      config_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 配置编码（总装换型键）
     * </pre>
     *
     * <code>string config = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearConfig() {
      config_ = getDefaultInstance().getConfig();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 配置编码（总装换型键）
     * </pre>
     *
     * <code>string config = 10;</code>
     * @param value The bytes for config to set.
     * @return This builder for chaining.
     */
    public Builder setConfigBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      config_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private double energyScore_ ;
    /**
     * <pre>
     * 能耗分值
     * </pre>
     *
     * <code>double energy_score = 11;</code>
     * @return The energyScore.
     */
    @java.lang.Override
    public double getEnergyScore() {
      return energyScore_;
    }
    /**
     * <pre>
     * 能耗分值
     * </pre>
     *
     * <code>double energy_score = 11;</code>
     * @param value The energyScore to set.
     * @return This builder for chaining.
     */
    public Builder setEnergyScore(double value) {

      energyScore_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 能耗分值
     * </pre>
     *
     * <code>double energy_score = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnergyScore() {
      bitField0_ = (bitField0_ & ~0x00000400);
      energyScore_ = 0D;
      onChanged();
      return this;
    }

    private double emissionScore_ ;
    /**
     * <pre>
     * 排放分值
     * </pre>
     *
     * <code>double emission_score = 12;</code>
     * @return The emissionScore.
     */
    @java.lang.Override
    public double getEmissionScore() {
      return emissionScore_;
    }
    /**
     * <pre>
     * 排放分值
     * </pre>
     *
     * <code>double emission_score = 12;</code>
     * @param value The emissionScore to set.
     * @return This builder for chaining.
     */
    public Builder setEmissionScore(double value) {

      emissionScore_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 排放分值
     * </pre>
     *
     * <code>double emission_score = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmissionScore() {
      bitField0_ = (bitField0_ & ~0x00000800);
      emissionScore_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:aps.v1.Job)
  }

  // @@protoc_insertion_point(class_scope:aps.v1.Job)
  private static final com.aps.grpc.proto.Job DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.aps.grpc.proto.Job();
  }

  public static com.aps.grpc.proto.Job getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Job>
      PARSER = new com.google.protobuf.AbstractParser<Job>() {
    @java.lang.Override
    public Job parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Job> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Job> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.aps.grpc.proto.Job getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

