// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aps.proto

// Protobuf Java Version: 3.25.2
package com.aps.grpc.proto;

public interface JobInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aps.v1.JobInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 任务ID
   * </pre>
   *
   * <code>string job_id = 1;</code>
   * @return The jobId.
   */
  java.lang.String getJobId();
  /**
   * <pre>
   * 任务ID
   * </pre>
   *
   * <code>string job_id = 1;</code>
   * @return The bytes for jobId.
   */
  com.google.protobuf.ByteString
      getJobIdBytes();

  /**
   * <pre>
   * 状态
   * </pre>
   *
   * <code>string status = 2;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <pre>
   * 状态
   * </pre>
   *
   * <code>string status = 2;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <pre>
   * 创建时间（Unix秒）
   * </pre>
   *
   * <code>int64 created_at = 3;</code>
   * @return The createdAt.
   */
  long getCreatedAt();

  /**
   * <pre>
   * 更新时间（Unix秒）
   * </pre>
   *
   * <code>int64 updated_at = 4;</code>
   * @return The updatedAt.
   */
  long getUpdatedAt();
}
