// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aps.proto

// Protobuf Java Version: 3.25.2
package com.aps.grpc.proto;

public interface JobOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aps.v1.Job)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 车辆识别码/订单号
   * </pre>
   *
   * <code>string vin = 1;</code>
   * @return The vin.
   */
  java.lang.String getVin();
  /**
   * <pre>
   * 车辆识别码/订单号
   * </pre>
   *
   * <code>string vin = 1;</code>
   * @return The bytes for vin.
   */
  com.google.protobuf.ByteString
      getVinBytes();

  /**
   * <pre>
   * 交期（毫秒时间戳）
   * </pre>
   *
   * <code>int64 due_epoch_ms = 2;</code>
   * @return The dueEpochMs.
   */
  long getDueEpochMs();

  /**
   * <pre>
   * 冲压工时（分钟）
   * </pre>
   *
   * <code>int32 stamping_minutes = 3;</code>
   * @return The stampingMinutes.
   */
  int getStampingMinutes();

  /**
   * <pre>
   * 焊装工时（分钟）
   * </pre>
   *
   * <code>int32 welding_minutes = 4;</code>
   * @return The weldingMinutes.
   */
  int getWeldingMinutes();

  /**
   * <pre>
   * 涂装工时（分钟）
   * </pre>
   *
   * <code>int32 painting_minutes = 5;</code>
   * @return The paintingMinutes.
   */
  int getPaintingMinutes();

  /**
   * <pre>
   * 总装工时（分钟）
   * </pre>
   *
   * <code>int32 assemble_minutes = 6;</code>
   * @return The assembleMinutes.
   */
  int getAssembleMinutes();

  /**
   * <pre>
   * 模具编码（冲压换型键）
   * </pre>
   *
   * <code>string mold_code = 7;</code>
   * @return The moldCode.
   */
  java.lang.String getMoldCode();
  /**
   * <pre>
   * 模具编码（冲压换型键）
   * </pre>
   *
   * <code>string mold_code = 7;</code>
   * @return The bytes for moldCode.
   */
  com.google.protobuf.ByteString
      getMoldCodeBytes();

  /**
   * <pre>
   * 焊装夹具（焊装换型键）
   * </pre>
   *
   * <code>string welding_fixture = 8;</code>
   * @return The weldingFixture.
   */
  java.lang.String getWeldingFixture();
  /**
   * <pre>
   * 焊装夹具（焊装换型键）
   * </pre>
   *
   * <code>string welding_fixture = 8;</code>
   * @return The bytes for weldingFixture.
   */
  com.google.protobuf.ByteString
      getWeldingFixtureBytes();

  /**
   * <pre>
   * 颜色编码（涂装换型键）
   * </pre>
   *
   * <code>string color = 9;</code>
   * @return The color.
   */
  java.lang.String getColor();
  /**
   * <pre>
   * 颜色编码（涂装换型键）
   * </pre>
   *
   * <code>string color = 9;</code>
   * @return The bytes for color.
   */
  com.google.protobuf.ByteString
      getColorBytes();

  /**
   * <pre>
   * 配置编码（总装换型键）
   * </pre>
   *
   * <code>string config = 10;</code>
   * @return The config.
   */
  java.lang.String getConfig();
  /**
   * <pre>
   * 配置编码（总装换型键）
   * </pre>
   *
   * <code>string config = 10;</code>
   * @return The bytes for config.
   */
  com.google.protobuf.ByteString
      getConfigBytes();

  /**
   * <pre>
   * 能耗分值
   * </pre>
   *
   * <code>double energy_score = 11;</code>
   * @return The energyScore.
   */
  double getEnergyScore();

  /**
   * <pre>
   * 排放分值
   * </pre>
   *
   * <code>double emission_score = 12;</code>
   * @return The emissionScore.
   */
  double getEmissionScore();
}
