// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aps.proto

// Protobuf Java Version: 3.25.2
package com.aps.grpc.proto;

public interface KpiSummaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aps.v1.KpiSummary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 总成本（目标函数值）
   * </pre>
   *
   * <code>double cost = 1;</code>
   * @return The cost.
   */
  double getCost();

  /**
   * <pre>
   * 总延迟时间（分钟）
   * </pre>
   *
   * <code>int64 total_tardiness_min = 2;</code>
   * @return The totalTardinessMin.
   */
  long getTotalTardinessMin();

  /**
   * <pre>
   * 最大延迟时间（分钟）
   * </pre>
   *
   * <code>int64 max_tardiness_min = 3;</code>
   * @return The maxTardinessMin.
   */
  long getMaxTardinessMin();

  /**
   * <pre>
   * 颜色切换次数
   * </pre>
   *
   * <code>int32 color_changes = 4;</code>
   * @return The colorChanges.
   */
  int getColorChanges();

  /**
   * <pre>
   * 配置切换次数
   * </pre>
   *
   * <code>int32 config_changes = 5;</code>
   * @return The configChanges.
   */
  int getConfigChanges();

  /**
   * <pre>
   * 能耗超限总量
   * </pre>
   *
   * <code>double energy_excess = 6;</code>
   * @return The energyExcess.
   */
  double getEnergyExcess();

  /**
   * <pre>
   * 排放超限总量
   * </pre>
   *
   * <code>double emission_excess = 7;</code>
   * @return The emissionExcess.
   */
  double getEmissionExcess();

  /**
   * <pre>
   * 物料短缺总量
   * </pre>
   *
   * <code>double material_shortage = 8;</code>
   * @return The materialShortage.
   */
  double getMaterialShortage();

  /**
   * <pre>
   * 求解耗时（毫秒）
   * </pre>
   *
   * <code>int64 elapsed_ms = 9;</code>
   * @return The elapsedMs.
   */
  long getElapsedMs();
}
