// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aps.proto

// Protobuf Java Version: 3.25.2
package com.aps.grpc.proto;

/**
 * Protobuf type {@code aps.v1.KpiSummary}
 */
public final class KpiSummary extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:aps.v1.KpiSummary)
    KpiSummaryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use KpiSummary.newBuilder() to construct.
  private KpiSummary(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private KpiSummary() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new KpiSummary();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_KpiSummary_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_KpiSummary_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.aps.grpc.proto.KpiSummary.class, com.aps.grpc.proto.KpiSummary.Builder.class);
  }

  public static final int COST_FIELD_NUMBER = 1;
  private double cost_ = 0D;
  /**
   * <pre>
   * 总成本（目标函数值）
   * </pre>
   *
   * <code>double cost = 1;</code>
   * @return The cost.
   */
  @java.lang.Override
  public double getCost() {
    return cost_;
  }

  public static final int TOTAL_TARDINESS_MIN_FIELD_NUMBER = 2;
  private long totalTardinessMin_ = 0L;
  /**
   * <pre>
   * 总延迟时间（分钟）
   * </pre>
   *
   * <code>int64 total_tardiness_min = 2;</code>
   * @return The totalTardinessMin.
   */
  @java.lang.Override
  public long getTotalTardinessMin() {
    return totalTardinessMin_;
  }

  public static final int MAX_TARDINESS_MIN_FIELD_NUMBER = 3;
  private long maxTardinessMin_ = 0L;
  /**
   * <pre>
   * 最大延迟时间（分钟）
   * </pre>
   *
   * <code>int64 max_tardiness_min = 3;</code>
   * @return The maxTardinessMin.
   */
  @java.lang.Override
  public long getMaxTardinessMin() {
    return maxTardinessMin_;
  }

  public static final int COLOR_CHANGES_FIELD_NUMBER = 4;
  private int colorChanges_ = 0;
  /**
   * <pre>
   * 颜色切换次数
   * </pre>
   *
   * <code>int32 color_changes = 4;</code>
   * @return The colorChanges.
   */
  @java.lang.Override
  public int getColorChanges() {
    return colorChanges_;
  }

  public static final int CONFIG_CHANGES_FIELD_NUMBER = 5;
  private int configChanges_ = 0;
  /**
   * <pre>
   * 配置切换次数
   * </pre>
   *
   * <code>int32 config_changes = 5;</code>
   * @return The configChanges.
   */
  @java.lang.Override
  public int getConfigChanges() {
    return configChanges_;
  }

  public static final int ENERGY_EXCESS_FIELD_NUMBER = 6;
  private double energyExcess_ = 0D;
  /**
   * <pre>
   * 能耗超限总量
   * </pre>
   *
   * <code>double energy_excess = 6;</code>
   * @return The energyExcess.
   */
  @java.lang.Override
  public double getEnergyExcess() {
    return energyExcess_;
  }

  public static final int EMISSION_EXCESS_FIELD_NUMBER = 7;
  private double emissionExcess_ = 0D;
  /**
   * <pre>
   * 排放超限总量
   * </pre>
   *
   * <code>double emission_excess = 7;</code>
   * @return The emissionExcess.
   */
  @java.lang.Override
  public double getEmissionExcess() {
    return emissionExcess_;
  }

  public static final int MATERIAL_SHORTAGE_FIELD_NUMBER = 8;
  private double materialShortage_ = 0D;
  /**
   * <pre>
   * 物料短缺总量
   * </pre>
   *
   * <code>double material_shortage = 8;</code>
   * @return The materialShortage.
   */
  @java.lang.Override
  public double getMaterialShortage() {
    return materialShortage_;
  }

  public static final int ELAPSED_MS_FIELD_NUMBER = 9;
  private long elapsedMs_ = 0L;
  /**
   * <pre>
   * 求解耗时（毫秒）
   * </pre>
   *
   * <code>int64 elapsed_ms = 9;</code>
   * @return The elapsedMs.
   */
  @java.lang.Override
  public long getElapsedMs() {
    return elapsedMs_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Double.doubleToRawLongBits(cost_) != 0) {
      output.writeDouble(1, cost_);
    }
    if (totalTardinessMin_ != 0L) {
      output.writeInt64(2, totalTardinessMin_);
    }
    if (maxTardinessMin_ != 0L) {
      output.writeInt64(3, maxTardinessMin_);
    }
    if (colorChanges_ != 0) {
      output.writeInt32(4, colorChanges_);
    }
    if (configChanges_ != 0) {
      output.writeInt32(5, configChanges_);
    }
    if (java.lang.Double.doubleToRawLongBits(energyExcess_) != 0) {
      output.writeDouble(6, energyExcess_);
    }
    if (java.lang.Double.doubleToRawLongBits(emissionExcess_) != 0) {
      output.writeDouble(7, emissionExcess_);
    }
    if (java.lang.Double.doubleToRawLongBits(materialShortage_) != 0) {
      output.writeDouble(8, materialShortage_);
    }
    if (elapsedMs_ != 0L) {
      output.writeInt64(9, elapsedMs_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Double.doubleToRawLongBits(cost_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, cost_);
    }
    if (totalTardinessMin_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, totalTardinessMin_);
    }
    if (maxTardinessMin_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, maxTardinessMin_);
    }
    if (colorChanges_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, colorChanges_);
    }
    if (configChanges_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, configChanges_);
    }
    if (java.lang.Double.doubleToRawLongBits(energyExcess_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, energyExcess_);
    }
    if (java.lang.Double.doubleToRawLongBits(emissionExcess_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, emissionExcess_);
    }
    if (java.lang.Double.doubleToRawLongBits(materialShortage_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(8, materialShortage_);
    }
    if (elapsedMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, elapsedMs_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.aps.grpc.proto.KpiSummary)) {
      return super.equals(obj);
    }
    com.aps.grpc.proto.KpiSummary other = (com.aps.grpc.proto.KpiSummary) obj;

    if (java.lang.Double.doubleToLongBits(getCost())
        != java.lang.Double.doubleToLongBits(
            other.getCost())) return false;
    if (getTotalTardinessMin()
        != other.getTotalTardinessMin()) return false;
    if (getMaxTardinessMin()
        != other.getMaxTardinessMin()) return false;
    if (getColorChanges()
        != other.getColorChanges()) return false;
    if (getConfigChanges()
        != other.getConfigChanges()) return false;
    if (java.lang.Double.doubleToLongBits(getEnergyExcess())
        != java.lang.Double.doubleToLongBits(
            other.getEnergyExcess())) return false;
    if (java.lang.Double.doubleToLongBits(getEmissionExcess())
        != java.lang.Double.doubleToLongBits(
            other.getEmissionExcess())) return false;
    if (java.lang.Double.doubleToLongBits(getMaterialShortage())
        != java.lang.Double.doubleToLongBits(
            other.getMaterialShortage())) return false;
    if (getElapsedMs()
        != other.getElapsedMs()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COST_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCost()));
    hash = (37 * hash) + TOTAL_TARDINESS_MIN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalTardinessMin());
    hash = (37 * hash) + MAX_TARDINESS_MIN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMaxTardinessMin());
    hash = (37 * hash) + COLOR_CHANGES_FIELD_NUMBER;
    hash = (53 * hash) + getColorChanges();
    hash = (37 * hash) + CONFIG_CHANGES_FIELD_NUMBER;
    hash = (53 * hash) + getConfigChanges();
    hash = (37 * hash) + ENERGY_EXCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getEnergyExcess()));
    hash = (37 * hash) + EMISSION_EXCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getEmissionExcess()));
    hash = (37 * hash) + MATERIAL_SHORTAGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMaterialShortage()));
    hash = (37 * hash) + ELAPSED_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getElapsedMs());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.aps.grpc.proto.KpiSummary parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aps.grpc.proto.KpiSummary parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aps.grpc.proto.KpiSummary parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aps.grpc.proto.KpiSummary parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aps.grpc.proto.KpiSummary parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aps.grpc.proto.KpiSummary parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aps.grpc.proto.KpiSummary parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aps.grpc.proto.KpiSummary parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.aps.grpc.proto.KpiSummary parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.aps.grpc.proto.KpiSummary parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aps.grpc.proto.KpiSummary parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aps.grpc.proto.KpiSummary parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.aps.grpc.proto.KpiSummary prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code aps.v1.KpiSummary}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:aps.v1.KpiSummary)
      com.aps.grpc.proto.KpiSummaryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_KpiSummary_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_KpiSummary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aps.grpc.proto.KpiSummary.class, com.aps.grpc.proto.KpiSummary.Builder.class);
    }

    // Construct using com.aps.grpc.proto.KpiSummary.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      cost_ = 0D;
      totalTardinessMin_ = 0L;
      maxTardinessMin_ = 0L;
      colorChanges_ = 0;
      configChanges_ = 0;
      energyExcess_ = 0D;
      emissionExcess_ = 0D;
      materialShortage_ = 0D;
      elapsedMs_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_KpiSummary_descriptor;
    }

    @java.lang.Override
    public com.aps.grpc.proto.KpiSummary getDefaultInstanceForType() {
      return com.aps.grpc.proto.KpiSummary.getDefaultInstance();
    }

    @java.lang.Override
    public com.aps.grpc.proto.KpiSummary build() {
      com.aps.grpc.proto.KpiSummary result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.aps.grpc.proto.KpiSummary buildPartial() {
      com.aps.grpc.proto.KpiSummary result = new com.aps.grpc.proto.KpiSummary(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.aps.grpc.proto.KpiSummary result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.cost_ = cost_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.totalTardinessMin_ = totalTardinessMin_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.maxTardinessMin_ = maxTardinessMin_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.colorChanges_ = colorChanges_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.configChanges_ = configChanges_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.energyExcess_ = energyExcess_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.emissionExcess_ = emissionExcess_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.materialShortage_ = materialShortage_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.elapsedMs_ = elapsedMs_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.aps.grpc.proto.KpiSummary) {
        return mergeFrom((com.aps.grpc.proto.KpiSummary)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.aps.grpc.proto.KpiSummary other) {
      if (other == com.aps.grpc.proto.KpiSummary.getDefaultInstance()) return this;
      if (other.getCost() != 0D) {
        setCost(other.getCost());
      }
      if (other.getTotalTardinessMin() != 0L) {
        setTotalTardinessMin(other.getTotalTardinessMin());
      }
      if (other.getMaxTardinessMin() != 0L) {
        setMaxTardinessMin(other.getMaxTardinessMin());
      }
      if (other.getColorChanges() != 0) {
        setColorChanges(other.getColorChanges());
      }
      if (other.getConfigChanges() != 0) {
        setConfigChanges(other.getConfigChanges());
      }
      if (other.getEnergyExcess() != 0D) {
        setEnergyExcess(other.getEnergyExcess());
      }
      if (other.getEmissionExcess() != 0D) {
        setEmissionExcess(other.getEmissionExcess());
      }
      if (other.getMaterialShortage() != 0D) {
        setMaterialShortage(other.getMaterialShortage());
      }
      if (other.getElapsedMs() != 0L) {
        setElapsedMs(other.getElapsedMs());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              cost_ = input.readDouble();
              bitField0_ |= 0x00000001;
              break;
            } // case 9
            case 16: {
              totalTardinessMin_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              maxTardinessMin_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              colorChanges_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              configChanges_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 49: {
              energyExcess_ = input.readDouble();
              bitField0_ |= 0x00000020;
              break;
            } // case 49
            case 57: {
              emissionExcess_ = input.readDouble();
              bitField0_ |= 0x00000040;
              break;
            } // case 57
            case 65: {
              materialShortage_ = input.readDouble();
              bitField0_ |= 0x00000080;
              break;
            } // case 65
            case 72: {
              elapsedMs_ = input.readInt64();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private double cost_ ;
    /**
     * <pre>
     * 总成本（目标函数值）
     * </pre>
     *
     * <code>double cost = 1;</code>
     * @return The cost.
     */
    @java.lang.Override
    public double getCost() {
      return cost_;
    }
    /**
     * <pre>
     * 总成本（目标函数值）
     * </pre>
     *
     * <code>double cost = 1;</code>
     * @param value The cost to set.
     * @return This builder for chaining.
     */
    public Builder setCost(double value) {

      cost_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 总成本（目标函数值）
     * </pre>
     *
     * <code>double cost = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCost() {
      bitField0_ = (bitField0_ & ~0x00000001);
      cost_ = 0D;
      onChanged();
      return this;
    }

    private long totalTardinessMin_ ;
    /**
     * <pre>
     * 总延迟时间（分钟）
     * </pre>
     *
     * <code>int64 total_tardiness_min = 2;</code>
     * @return The totalTardinessMin.
     */
    @java.lang.Override
    public long getTotalTardinessMin() {
      return totalTardinessMin_;
    }
    /**
     * <pre>
     * 总延迟时间（分钟）
     * </pre>
     *
     * <code>int64 total_tardiness_min = 2;</code>
     * @param value The totalTardinessMin to set.
     * @return This builder for chaining.
     */
    public Builder setTotalTardinessMin(long value) {

      totalTardinessMin_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 总延迟时间（分钟）
     * </pre>
     *
     * <code>int64 total_tardiness_min = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalTardinessMin() {
      bitField0_ = (bitField0_ & ~0x00000002);
      totalTardinessMin_ = 0L;
      onChanged();
      return this;
    }

    private long maxTardinessMin_ ;
    /**
     * <pre>
     * 最大延迟时间（分钟）
     * </pre>
     *
     * <code>int64 max_tardiness_min = 3;</code>
     * @return The maxTardinessMin.
     */
    @java.lang.Override
    public long getMaxTardinessMin() {
      return maxTardinessMin_;
    }
    /**
     * <pre>
     * 最大延迟时间（分钟）
     * </pre>
     *
     * <code>int64 max_tardiness_min = 3;</code>
     * @param value The maxTardinessMin to set.
     * @return This builder for chaining.
     */
    public Builder setMaxTardinessMin(long value) {

      maxTardinessMin_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 最大延迟时间（分钟）
     * </pre>
     *
     * <code>int64 max_tardiness_min = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxTardinessMin() {
      bitField0_ = (bitField0_ & ~0x00000004);
      maxTardinessMin_ = 0L;
      onChanged();
      return this;
    }

    private int colorChanges_ ;
    /**
     * <pre>
     * 颜色切换次数
     * </pre>
     *
     * <code>int32 color_changes = 4;</code>
     * @return The colorChanges.
     */
    @java.lang.Override
    public int getColorChanges() {
      return colorChanges_;
    }
    /**
     * <pre>
     * 颜色切换次数
     * </pre>
     *
     * <code>int32 color_changes = 4;</code>
     * @param value The colorChanges to set.
     * @return This builder for chaining.
     */
    public Builder setColorChanges(int value) {

      colorChanges_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 颜色切换次数
     * </pre>
     *
     * <code>int32 color_changes = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearColorChanges() {
      bitField0_ = (bitField0_ & ~0x00000008);
      colorChanges_ = 0;
      onChanged();
      return this;
    }

    private int configChanges_ ;
    /**
     * <pre>
     * 配置切换次数
     * </pre>
     *
     * <code>int32 config_changes = 5;</code>
     * @return The configChanges.
     */
    @java.lang.Override
    public int getConfigChanges() {
      return configChanges_;
    }
    /**
     * <pre>
     * 配置切换次数
     * </pre>
     *
     * <code>int32 config_changes = 5;</code>
     * @param value The configChanges to set.
     * @return This builder for chaining.
     */
    public Builder setConfigChanges(int value) {

      configChanges_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 配置切换次数
     * </pre>
     *
     * <code>int32 config_changes = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearConfigChanges() {
      bitField0_ = (bitField0_ & ~0x00000010);
      configChanges_ = 0;
      onChanged();
      return this;
    }

    private double energyExcess_ ;
    /**
     * <pre>
     * 能耗超限总量
     * </pre>
     *
     * <code>double energy_excess = 6;</code>
     * @return The energyExcess.
     */
    @java.lang.Override
    public double getEnergyExcess() {
      return energyExcess_;
    }
    /**
     * <pre>
     * 能耗超限总量
     * </pre>
     *
     * <code>double energy_excess = 6;</code>
     * @param value The energyExcess to set.
     * @return This builder for chaining.
     */
    public Builder setEnergyExcess(double value) {

      energyExcess_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 能耗超限总量
     * </pre>
     *
     * <code>double energy_excess = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnergyExcess() {
      bitField0_ = (bitField0_ & ~0x00000020);
      energyExcess_ = 0D;
      onChanged();
      return this;
    }

    private double emissionExcess_ ;
    /**
     * <pre>
     * 排放超限总量
     * </pre>
     *
     * <code>double emission_excess = 7;</code>
     * @return The emissionExcess.
     */
    @java.lang.Override
    public double getEmissionExcess() {
      return emissionExcess_;
    }
    /**
     * <pre>
     * 排放超限总量
     * </pre>
     *
     * <code>double emission_excess = 7;</code>
     * @param value The emissionExcess to set.
     * @return This builder for chaining.
     */
    public Builder setEmissionExcess(double value) {

      emissionExcess_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 排放超限总量
     * </pre>
     *
     * <code>double emission_excess = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmissionExcess() {
      bitField0_ = (bitField0_ & ~0x00000040);
      emissionExcess_ = 0D;
      onChanged();
      return this;
    }

    private double materialShortage_ ;
    /**
     * <pre>
     * 物料短缺总量
     * </pre>
     *
     * <code>double material_shortage = 8;</code>
     * @return The materialShortage.
     */
    @java.lang.Override
    public double getMaterialShortage() {
      return materialShortage_;
    }
    /**
     * <pre>
     * 物料短缺总量
     * </pre>
     *
     * <code>double material_shortage = 8;</code>
     * @param value The materialShortage to set.
     * @return This builder for chaining.
     */
    public Builder setMaterialShortage(double value) {

      materialShortage_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 物料短缺总量
     * </pre>
     *
     * <code>double material_shortage = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaterialShortage() {
      bitField0_ = (bitField0_ & ~0x00000080);
      materialShortage_ = 0D;
      onChanged();
      return this;
    }

    private long elapsedMs_ ;
    /**
     * <pre>
     * 求解耗时（毫秒）
     * </pre>
     *
     * <code>int64 elapsed_ms = 9;</code>
     * @return The elapsedMs.
     */
    @java.lang.Override
    public long getElapsedMs() {
      return elapsedMs_;
    }
    /**
     * <pre>
     * 求解耗时（毫秒）
     * </pre>
     *
     * <code>int64 elapsed_ms = 9;</code>
     * @param value The elapsedMs to set.
     * @return This builder for chaining.
     */
    public Builder setElapsedMs(long value) {

      elapsedMs_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 求解耗时（毫秒）
     * </pre>
     *
     * <code>int64 elapsed_ms = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearElapsedMs() {
      bitField0_ = (bitField0_ & ~0x00000100);
      elapsedMs_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:aps.v1.KpiSummary)
  }

  // @@protoc_insertion_point(class_scope:aps.v1.KpiSummary)
  private static final com.aps.grpc.proto.KpiSummary DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.aps.grpc.proto.KpiSummary();
  }

  public static com.aps.grpc.proto.KpiSummary getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<KpiSummary>
      PARSER = new com.google.protobuf.AbstractParser<KpiSummary>() {
    @java.lang.Override
    public KpiSummary parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<KpiSummary> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<KpiSummary> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.aps.grpc.proto.KpiSummary getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

