// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aps.proto

// Protobuf Java Version: 3.25.2
package com.aps.grpc.proto;

/**
 * Protobuf type {@code aps.v1.Limits}
 */
public final class Limits extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:aps.v1.Limits)
    LimitsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Limits.newBuilder() to construct.
  private Limits(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Limits() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Limits();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_Limits_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_Limits_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.aps.grpc.proto.Limits.class, com.aps.grpc.proto.Limits.Builder.class);
  }

  public static final int MAX_ENERGY_PER_SHIFT_FIELD_NUMBER = 1;
  private double maxEnergyPerShift_ = 0D;
  /**
   * <pre>
   * 班次能耗上限
   * </pre>
   *
   * <code>double max_energy_per_shift = 1;</code>
   * @return The maxEnergyPerShift.
   */
  @java.lang.Override
  public double getMaxEnergyPerShift() {
    return maxEnergyPerShift_;
  }

  public static final int MAX_EMISSION_PER_SHIFT_FIELD_NUMBER = 2;
  private double maxEmissionPerShift_ = 0D;
  /**
   * <pre>
   * 班次排放上限
   * </pre>
   *
   * <code>double max_emission_per_shift = 2;</code>
   * @return The maxEmissionPerShift.
   */
  @java.lang.Override
  public double getMaxEmissionPerShift() {
    return maxEmissionPerShift_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Double.doubleToRawLongBits(maxEnergyPerShift_) != 0) {
      output.writeDouble(1, maxEnergyPerShift_);
    }
    if (java.lang.Double.doubleToRawLongBits(maxEmissionPerShift_) != 0) {
      output.writeDouble(2, maxEmissionPerShift_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Double.doubleToRawLongBits(maxEnergyPerShift_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, maxEnergyPerShift_);
    }
    if (java.lang.Double.doubleToRawLongBits(maxEmissionPerShift_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, maxEmissionPerShift_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.aps.grpc.proto.Limits)) {
      return super.equals(obj);
    }
    com.aps.grpc.proto.Limits other = (com.aps.grpc.proto.Limits) obj;

    if (java.lang.Double.doubleToLongBits(getMaxEnergyPerShift())
        != java.lang.Double.doubleToLongBits(
            other.getMaxEnergyPerShift())) return false;
    if (java.lang.Double.doubleToLongBits(getMaxEmissionPerShift())
        != java.lang.Double.doubleToLongBits(
            other.getMaxEmissionPerShift())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MAX_ENERGY_PER_SHIFT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMaxEnergyPerShift()));
    hash = (37 * hash) + MAX_EMISSION_PER_SHIFT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMaxEmissionPerShift()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.aps.grpc.proto.Limits parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aps.grpc.proto.Limits parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aps.grpc.proto.Limits parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aps.grpc.proto.Limits parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aps.grpc.proto.Limits parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aps.grpc.proto.Limits parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aps.grpc.proto.Limits parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aps.grpc.proto.Limits parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.aps.grpc.proto.Limits parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.aps.grpc.proto.Limits parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aps.grpc.proto.Limits parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aps.grpc.proto.Limits parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.aps.grpc.proto.Limits prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code aps.v1.Limits}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:aps.v1.Limits)
      com.aps.grpc.proto.LimitsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_Limits_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_Limits_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aps.grpc.proto.Limits.class, com.aps.grpc.proto.Limits.Builder.class);
    }

    // Construct using com.aps.grpc.proto.Limits.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      maxEnergyPerShift_ = 0D;
      maxEmissionPerShift_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_Limits_descriptor;
    }

    @java.lang.Override
    public com.aps.grpc.proto.Limits getDefaultInstanceForType() {
      return com.aps.grpc.proto.Limits.getDefaultInstance();
    }

    @java.lang.Override
    public com.aps.grpc.proto.Limits build() {
      com.aps.grpc.proto.Limits result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.aps.grpc.proto.Limits buildPartial() {
      com.aps.grpc.proto.Limits result = new com.aps.grpc.proto.Limits(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.aps.grpc.proto.Limits result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.maxEnergyPerShift_ = maxEnergyPerShift_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.maxEmissionPerShift_ = maxEmissionPerShift_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.aps.grpc.proto.Limits) {
        return mergeFrom((com.aps.grpc.proto.Limits)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.aps.grpc.proto.Limits other) {
      if (other == com.aps.grpc.proto.Limits.getDefaultInstance()) return this;
      if (other.getMaxEnergyPerShift() != 0D) {
        setMaxEnergyPerShift(other.getMaxEnergyPerShift());
      }
      if (other.getMaxEmissionPerShift() != 0D) {
        setMaxEmissionPerShift(other.getMaxEmissionPerShift());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              maxEnergyPerShift_ = input.readDouble();
              bitField0_ |= 0x00000001;
              break;
            } // case 9
            case 17: {
              maxEmissionPerShift_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private double maxEnergyPerShift_ ;
    /**
     * <pre>
     * 班次能耗上限
     * </pre>
     *
     * <code>double max_energy_per_shift = 1;</code>
     * @return The maxEnergyPerShift.
     */
    @java.lang.Override
    public double getMaxEnergyPerShift() {
      return maxEnergyPerShift_;
    }
    /**
     * <pre>
     * 班次能耗上限
     * </pre>
     *
     * <code>double max_energy_per_shift = 1;</code>
     * @param value The maxEnergyPerShift to set.
     * @return This builder for chaining.
     */
    public Builder setMaxEnergyPerShift(double value) {

      maxEnergyPerShift_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 班次能耗上限
     * </pre>
     *
     * <code>double max_energy_per_shift = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxEnergyPerShift() {
      bitField0_ = (bitField0_ & ~0x00000001);
      maxEnergyPerShift_ = 0D;
      onChanged();
      return this;
    }

    private double maxEmissionPerShift_ ;
    /**
     * <pre>
     * 班次排放上限
     * </pre>
     *
     * <code>double max_emission_per_shift = 2;</code>
     * @return The maxEmissionPerShift.
     */
    @java.lang.Override
    public double getMaxEmissionPerShift() {
      return maxEmissionPerShift_;
    }
    /**
     * <pre>
     * 班次排放上限
     * </pre>
     *
     * <code>double max_emission_per_shift = 2;</code>
     * @param value The maxEmissionPerShift to set.
     * @return This builder for chaining.
     */
    public Builder setMaxEmissionPerShift(double value) {

      maxEmissionPerShift_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 班次排放上限
     * </pre>
     *
     * <code>double max_emission_per_shift = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxEmissionPerShift() {
      bitField0_ = (bitField0_ & ~0x00000002);
      maxEmissionPerShift_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:aps.v1.Limits)
  }

  // @@protoc_insertion_point(class_scope:aps.v1.Limits)
  private static final com.aps.grpc.proto.Limits DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.aps.grpc.proto.Limits();
  }

  public static com.aps.grpc.proto.Limits getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Limits>
      PARSER = new com.google.protobuf.AbstractParser<Limits>() {
    @java.lang.Override
    public Limits parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Limits> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Limits> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.aps.grpc.proto.Limits getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

