// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aps.proto

// Protobuf Java Version: 3.25.2
package com.aps.grpc.proto;

public interface LimitsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aps.v1.Limits)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 班次能耗上限
   * </pre>
   *
   * <code>double max_energy_per_shift = 1;</code>
   * @return The maxEnergyPerShift.
   */
  double getMaxEnergyPerShift();

  /**
   * <pre>
   * 班次排放上限
   * </pre>
   *
   * <code>double max_emission_per_shift = 2;</code>
   * @return The maxEmissionPerShift.
   */
  double getMaxEmissionPerShift();
}
