// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aps.proto

// Protobuf Java Version: 3.25.2
package com.aps.grpc.proto;

public interface ListJobsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aps.v1.ListJobsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 任务信息列表
   * </pre>
   *
   * <code>repeated .aps.v1.JobInfo jobs = 1;</code>
   */
  java.util.List<com.aps.grpc.proto.JobInfo> 
      getJobsList();
  /**
   * <pre>
   * 任务信息列表
   * </pre>
   *
   * <code>repeated .aps.v1.JobInfo jobs = 1;</code>
   */
  com.aps.grpc.proto.JobInfo getJobs(int index);
  /**
   * <pre>
   * 任务信息列表
   * </pre>
   *
   * <code>repeated .aps.v1.JobInfo jobs = 1;</code>
   */
  int getJobsCount();
  /**
   * <pre>
   * 任务信息列表
   * </pre>
   *
   * <code>repeated .aps.v1.JobInfo jobs = 1;</code>
   */
  java.util.List<? extends com.aps.grpc.proto.JobInfoOrBuilder> 
      getJobsOrBuilderList();
  /**
   * <pre>
   * 任务信息列表
   * </pre>
   *
   * <code>repeated .aps.v1.JobInfo jobs = 1;</code>
   */
  com.aps.grpc.proto.JobInfoOrBuilder getJobsOrBuilder(
      int index);
}
