// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aps.proto

// Protobuf Java Version: 3.25.2
package com.aps.grpc.proto;

public interface ListJobsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aps.v1.ListJobsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 返回数量限制（0表示不限制）
   * </pre>
   *
   * <code>int32 limit = 1;</code>
   * @return The limit.
   */
  int getLimit();
}
