// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aps.proto

// Protobuf Java Version: 3.25.2
package com.aps.grpc.proto;

/**
 * Protobuf type {@code aps.v1.ScheduleItem}
 */
public final class ScheduleItem extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:aps.v1.ScheduleItem)
    ScheduleItemOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ScheduleItem.newBuilder() to construct.
  private ScheduleItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ScheduleItem() {
    vin_ = "";
    color_ = "";
    config_ = "";
    shiftId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ScheduleItem();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_ScheduleItem_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_ScheduleItem_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.aps.grpc.proto.ScheduleItem.class, com.aps.grpc.proto.ScheduleItem.Builder.class);
  }

  public static final int SEQ_FIELD_NUMBER = 1;
  private int seq_ = 0;
  /**
   * <pre>
   * 全局顺序号
   * </pre>
   *
   * <code>int32 seq = 1;</code>
   * @return The seq.
   */
  @java.lang.Override
  public int getSeq() {
    return seq_;
  }

  public static final int VIN_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object vin_ = "";
  /**
   * <pre>
   * 车辆识别码
   * </pre>
   *
   * <code>string vin = 2;</code>
   * @return The vin.
   */
  @java.lang.Override
  public java.lang.String getVin() {
    java.lang.Object ref = vin_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      vin_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 车辆识别码
   * </pre>
   *
   * <code>string vin = 2;</code>
   * @return The bytes for vin.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVinBytes() {
    java.lang.Object ref = vin_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      vin_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROCESS_TYPE_FIELD_NUMBER = 3;
  private int processType_ = 0;
  /**
   * <pre>
   * 工艺类型（1冲压/2焊装/3涂装/4总装）
   * </pre>
   *
   * <code>int32 process_type = 3;</code>
   * @return The processType.
   */
  @java.lang.Override
  public int getProcessType() {
    return processType_;
  }

  public static final int LINE_ID_FIELD_NUMBER = 4;
  private long lineId_ = 0L;
  /**
   * <pre>
   * 产线ID
   * </pre>
   *
   * <code>int64 line_id = 4;</code>
   * @return The lineId.
   */
  @java.lang.Override
  public long getLineId() {
    return lineId_;
  }

  public static final int SEQ_IN_SHIFT_FIELD_NUMBER = 5;
  private int seqInShift_ = 0;
  /**
   * <pre>
   * 班次内顺序
   * </pre>
   *
   * <code>int32 seq_in_shift = 5;</code>
   * @return The seqInShift.
   */
  @java.lang.Override
  public int getSeqInShift() {
    return seqInShift_;
  }

  public static final int START_EPOCH_MS_FIELD_NUMBER = 6;
  private long startEpochMs_ = 0L;
  /**
   * <pre>
   * 开始时间（毫秒时间戳）
   * </pre>
   *
   * <code>int64 start_epoch_ms = 6;</code>
   * @return The startEpochMs.
   */
  @java.lang.Override
  public long getStartEpochMs() {
    return startEpochMs_;
  }

  public static final int END_EPOCH_MS_FIELD_NUMBER = 7;
  private long endEpochMs_ = 0L;
  /**
   * <pre>
   * 结束时间（毫秒时间戳）
   * </pre>
   *
   * <code>int64 end_epoch_ms = 7;</code>
   * @return The endEpochMs.
   */
  @java.lang.Override
  public long getEndEpochMs() {
    return endEpochMs_;
  }

  public static final int DUE_EPOCH_MS_FIELD_NUMBER = 8;
  private long dueEpochMs_ = 0L;
  /**
   * <pre>
   * 交期（毫秒时间戳）
   * </pre>
   *
   * <code>int64 due_epoch_ms = 8;</code>
   * @return The dueEpochMs.
   */
  @java.lang.Override
  public long getDueEpochMs() {
    return dueEpochMs_;
  }

  public static final int TARDINESS_MIN_FIELD_NUMBER = 9;
  private long tardinessMin_ = 0L;
  /**
   * <pre>
   * 延迟时间（分钟）
   * </pre>
   *
   * <code>int64 tardiness_min = 9;</code>
   * @return The tardinessMin.
   */
  @java.lang.Override
  public long getTardinessMin() {
    return tardinessMin_;
  }

  public static final int COLOR_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object color_ = "";
  /**
   * <pre>
   * 颜色编码
   * </pre>
   *
   * <code>string color = 10;</code>
   * @return The color.
   */
  @java.lang.Override
  public java.lang.String getColor() {
    java.lang.Object ref = color_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      color_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 颜色编码
   * </pre>
   *
   * <code>string color = 10;</code>
   * @return The bytes for color.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getColorBytes() {
    java.lang.Object ref = color_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      color_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONFIG_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object config_ = "";
  /**
   * <pre>
   * 配置编码
   * </pre>
   *
   * <code>string config = 11;</code>
   * @return The config.
   */
  @java.lang.Override
  public java.lang.String getConfig() {
    java.lang.Object ref = config_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      config_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 配置编码
   * </pre>
   *
   * <code>string config = 11;</code>
   * @return The bytes for config.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConfigBytes() {
    java.lang.Object ref = config_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      config_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SHIFT_ID_FIELD_NUMBER = 12;
  @SuppressWarnings("serial")
  private volatile java.lang.Object shiftId_ = "";
  /**
   * <pre>
   * 班次ID
   * </pre>
   *
   * <code>string shift_id = 12;</code>
   * @return The shiftId.
   */
  @java.lang.Override
  public java.lang.String getShiftId() {
    java.lang.Object ref = shiftId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      shiftId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 班次ID
   * </pre>
   *
   * <code>string shift_id = 12;</code>
   * @return The bytes for shiftId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getShiftIdBytes() {
    java.lang.Object ref = shiftId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      shiftId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (seq_ != 0) {
      output.writeInt32(1, seq_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(vin_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, vin_);
    }
    if (processType_ != 0) {
      output.writeInt32(3, processType_);
    }
    if (lineId_ != 0L) {
      output.writeInt64(4, lineId_);
    }
    if (seqInShift_ != 0) {
      output.writeInt32(5, seqInShift_);
    }
    if (startEpochMs_ != 0L) {
      output.writeInt64(6, startEpochMs_);
    }
    if (endEpochMs_ != 0L) {
      output.writeInt64(7, endEpochMs_);
    }
    if (dueEpochMs_ != 0L) {
      output.writeInt64(8, dueEpochMs_);
    }
    if (tardinessMin_ != 0L) {
      output.writeInt64(9, tardinessMin_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(color_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, color_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(config_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, config_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(shiftId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, shiftId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (seq_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, seq_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(vin_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, vin_);
    }
    if (processType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, processType_);
    }
    if (lineId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, lineId_);
    }
    if (seqInShift_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, seqInShift_);
    }
    if (startEpochMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, startEpochMs_);
    }
    if (endEpochMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, endEpochMs_);
    }
    if (dueEpochMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, dueEpochMs_);
    }
    if (tardinessMin_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, tardinessMin_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(color_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, color_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(config_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, config_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(shiftId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, shiftId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.aps.grpc.proto.ScheduleItem)) {
      return super.equals(obj);
    }
    com.aps.grpc.proto.ScheduleItem other = (com.aps.grpc.proto.ScheduleItem) obj;

    if (getSeq()
        != other.getSeq()) return false;
    if (!getVin()
        .equals(other.getVin())) return false;
    if (getProcessType()
        != other.getProcessType()) return false;
    if (getLineId()
        != other.getLineId()) return false;
    if (getSeqInShift()
        != other.getSeqInShift()) return false;
    if (getStartEpochMs()
        != other.getStartEpochMs()) return false;
    if (getEndEpochMs()
        != other.getEndEpochMs()) return false;
    if (getDueEpochMs()
        != other.getDueEpochMs()) return false;
    if (getTardinessMin()
        != other.getTardinessMin()) return false;
    if (!getColor()
        .equals(other.getColor())) return false;
    if (!getConfig()
        .equals(other.getConfig())) return false;
    if (!getShiftId()
        .equals(other.getShiftId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SEQ_FIELD_NUMBER;
    hash = (53 * hash) + getSeq();
    hash = (37 * hash) + VIN_FIELD_NUMBER;
    hash = (53 * hash) + getVin().hashCode();
    hash = (37 * hash) + PROCESS_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getProcessType();
    hash = (37 * hash) + LINE_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLineId());
    hash = (37 * hash) + SEQ_IN_SHIFT_FIELD_NUMBER;
    hash = (53 * hash) + getSeqInShift();
    hash = (37 * hash) + START_EPOCH_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartEpochMs());
    hash = (37 * hash) + END_EPOCH_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEndEpochMs());
    hash = (37 * hash) + DUE_EPOCH_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDueEpochMs());
    hash = (37 * hash) + TARDINESS_MIN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTardinessMin());
    hash = (37 * hash) + COLOR_FIELD_NUMBER;
    hash = (53 * hash) + getColor().hashCode();
    hash = (37 * hash) + CONFIG_FIELD_NUMBER;
    hash = (53 * hash) + getConfig().hashCode();
    hash = (37 * hash) + SHIFT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getShiftId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.aps.grpc.proto.ScheduleItem parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aps.grpc.proto.ScheduleItem parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aps.grpc.proto.ScheduleItem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aps.grpc.proto.ScheduleItem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aps.grpc.proto.ScheduleItem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aps.grpc.proto.ScheduleItem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aps.grpc.proto.ScheduleItem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aps.grpc.proto.ScheduleItem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.aps.grpc.proto.ScheduleItem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.aps.grpc.proto.ScheduleItem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aps.grpc.proto.ScheduleItem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aps.grpc.proto.ScheduleItem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.aps.grpc.proto.ScheduleItem prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code aps.v1.ScheduleItem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:aps.v1.ScheduleItem)
      com.aps.grpc.proto.ScheduleItemOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_ScheduleItem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_ScheduleItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aps.grpc.proto.ScheduleItem.class, com.aps.grpc.proto.ScheduleItem.Builder.class);
    }

    // Construct using com.aps.grpc.proto.ScheduleItem.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      seq_ = 0;
      vin_ = "";
      processType_ = 0;
      lineId_ = 0L;
      seqInShift_ = 0;
      startEpochMs_ = 0L;
      endEpochMs_ = 0L;
      dueEpochMs_ = 0L;
      tardinessMin_ = 0L;
      color_ = "";
      config_ = "";
      shiftId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_ScheduleItem_descriptor;
    }

    @java.lang.Override
    public com.aps.grpc.proto.ScheduleItem getDefaultInstanceForType() {
      return com.aps.grpc.proto.ScheduleItem.getDefaultInstance();
    }

    @java.lang.Override
    public com.aps.grpc.proto.ScheduleItem build() {
      com.aps.grpc.proto.ScheduleItem result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.aps.grpc.proto.ScheduleItem buildPartial() {
      com.aps.grpc.proto.ScheduleItem result = new com.aps.grpc.proto.ScheduleItem(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.aps.grpc.proto.ScheduleItem result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.seq_ = seq_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.vin_ = vin_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.processType_ = processType_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.lineId_ = lineId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.seqInShift_ = seqInShift_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.startEpochMs_ = startEpochMs_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.endEpochMs_ = endEpochMs_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.dueEpochMs_ = dueEpochMs_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.tardinessMin_ = tardinessMin_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.color_ = color_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.config_ = config_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.shiftId_ = shiftId_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.aps.grpc.proto.ScheduleItem) {
        return mergeFrom((com.aps.grpc.proto.ScheduleItem)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.aps.grpc.proto.ScheduleItem other) {
      if (other == com.aps.grpc.proto.ScheduleItem.getDefaultInstance()) return this;
      if (other.getSeq() != 0) {
        setSeq(other.getSeq());
      }
      if (!other.getVin().isEmpty()) {
        vin_ = other.vin_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getProcessType() != 0) {
        setProcessType(other.getProcessType());
      }
      if (other.getLineId() != 0L) {
        setLineId(other.getLineId());
      }
      if (other.getSeqInShift() != 0) {
        setSeqInShift(other.getSeqInShift());
      }
      if (other.getStartEpochMs() != 0L) {
        setStartEpochMs(other.getStartEpochMs());
      }
      if (other.getEndEpochMs() != 0L) {
        setEndEpochMs(other.getEndEpochMs());
      }
      if (other.getDueEpochMs() != 0L) {
        setDueEpochMs(other.getDueEpochMs());
      }
      if (other.getTardinessMin() != 0L) {
        setTardinessMin(other.getTardinessMin());
      }
      if (!other.getColor().isEmpty()) {
        color_ = other.color_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (!other.getConfig().isEmpty()) {
        config_ = other.config_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      if (!other.getShiftId().isEmpty()) {
        shiftId_ = other.shiftId_;
        bitField0_ |= 0x00000800;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              seq_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              vin_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              processType_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              lineId_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              seqInShift_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              startEpochMs_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              endEpochMs_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              dueEpochMs_ = input.readInt64();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              tardinessMin_ = input.readInt64();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 82: {
              color_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              config_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            case 98: {
              shiftId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000800;
              break;
            } // case 98
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int seq_ ;
    /**
     * <pre>
     * 全局顺序号
     * </pre>
     *
     * <code>int32 seq = 1;</code>
     * @return The seq.
     */
    @java.lang.Override
    public int getSeq() {
      return seq_;
    }
    /**
     * <pre>
     * 全局顺序号
     * </pre>
     *
     * <code>int32 seq = 1;</code>
     * @param value The seq to set.
     * @return This builder for chaining.
     */
    public Builder setSeq(int value) {

      seq_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 全局顺序号
     * </pre>
     *
     * <code>int32 seq = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeq() {
      bitField0_ = (bitField0_ & ~0x00000001);
      seq_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object vin_ = "";
    /**
     * <pre>
     * 车辆识别码
     * </pre>
     *
     * <code>string vin = 2;</code>
     * @return The vin.
     */
    public java.lang.String getVin() {
      java.lang.Object ref = vin_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vin_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 车辆识别码
     * </pre>
     *
     * <code>string vin = 2;</code>
     * @return The bytes for vin.
     */
    public com.google.protobuf.ByteString
        getVinBytes() {
      java.lang.Object ref = vin_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 车辆识别码
     * </pre>
     *
     * <code>string vin = 2;</code>
     * @param value The vin to set.
     * @return This builder for chaining.
     */
    public Builder setVin(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      vin_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 车辆识别码
     * </pre>
     *
     * <code>string vin = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVin() {
      vin_ = getDefaultInstance().getVin();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 车辆识别码
     * </pre>
     *
     * <code>string vin = 2;</code>
     * @param value The bytes for vin to set.
     * @return This builder for chaining.
     */
    public Builder setVinBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      vin_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int processType_ ;
    /**
     * <pre>
     * 工艺类型（1冲压/2焊装/3涂装/4总装）
     * </pre>
     *
     * <code>int32 process_type = 3;</code>
     * @return The processType.
     */
    @java.lang.Override
    public int getProcessType() {
      return processType_;
    }
    /**
     * <pre>
     * 工艺类型（1冲压/2焊装/3涂装/4总装）
     * </pre>
     *
     * <code>int32 process_type = 3;</code>
     * @param value The processType to set.
     * @return This builder for chaining.
     */
    public Builder setProcessType(int value) {

      processType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 工艺类型（1冲压/2焊装/3涂装/4总装）
     * </pre>
     *
     * <code>int32 process_type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearProcessType() {
      bitField0_ = (bitField0_ & ~0x00000004);
      processType_ = 0;
      onChanged();
      return this;
    }

    private long lineId_ ;
    /**
     * <pre>
     * 产线ID
     * </pre>
     *
     * <code>int64 line_id = 4;</code>
     * @return The lineId.
     */
    @java.lang.Override
    public long getLineId() {
      return lineId_;
    }
    /**
     * <pre>
     * 产线ID
     * </pre>
     *
     * <code>int64 line_id = 4;</code>
     * @param value The lineId to set.
     * @return This builder for chaining.
     */
    public Builder setLineId(long value) {

      lineId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 产线ID
     * </pre>
     *
     * <code>int64 line_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLineId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      lineId_ = 0L;
      onChanged();
      return this;
    }

    private int seqInShift_ ;
    /**
     * <pre>
     * 班次内顺序
     * </pre>
     *
     * <code>int32 seq_in_shift = 5;</code>
     * @return The seqInShift.
     */
    @java.lang.Override
    public int getSeqInShift() {
      return seqInShift_;
    }
    /**
     * <pre>
     * 班次内顺序
     * </pre>
     *
     * <code>int32 seq_in_shift = 5;</code>
     * @param value The seqInShift to set.
     * @return This builder for chaining.
     */
    public Builder setSeqInShift(int value) {

      seqInShift_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 班次内顺序
     * </pre>
     *
     * <code>int32 seq_in_shift = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeqInShift() {
      bitField0_ = (bitField0_ & ~0x00000010);
      seqInShift_ = 0;
      onChanged();
      return this;
    }

    private long startEpochMs_ ;
    /**
     * <pre>
     * 开始时间（毫秒时间戳）
     * </pre>
     *
     * <code>int64 start_epoch_ms = 6;</code>
     * @return The startEpochMs.
     */
    @java.lang.Override
    public long getStartEpochMs() {
      return startEpochMs_;
    }
    /**
     * <pre>
     * 开始时间（毫秒时间戳）
     * </pre>
     *
     * <code>int64 start_epoch_ms = 6;</code>
     * @param value The startEpochMs to set.
     * @return This builder for chaining.
     */
    public Builder setStartEpochMs(long value) {

      startEpochMs_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 开始时间（毫秒时间戳）
     * </pre>
     *
     * <code>int64 start_epoch_ms = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartEpochMs() {
      bitField0_ = (bitField0_ & ~0x00000020);
      startEpochMs_ = 0L;
      onChanged();
      return this;
    }

    private long endEpochMs_ ;
    /**
     * <pre>
     * 结束时间（毫秒时间戳）
     * </pre>
     *
     * <code>int64 end_epoch_ms = 7;</code>
     * @return The endEpochMs.
     */
    @java.lang.Override
    public long getEndEpochMs() {
      return endEpochMs_;
    }
    /**
     * <pre>
     * 结束时间（毫秒时间戳）
     * </pre>
     *
     * <code>int64 end_epoch_ms = 7;</code>
     * @param value The endEpochMs to set.
     * @return This builder for chaining.
     */
    public Builder setEndEpochMs(long value) {

      endEpochMs_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 结束时间（毫秒时间戳）
     * </pre>
     *
     * <code>int64 end_epoch_ms = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndEpochMs() {
      bitField0_ = (bitField0_ & ~0x00000040);
      endEpochMs_ = 0L;
      onChanged();
      return this;
    }

    private long dueEpochMs_ ;
    /**
     * <pre>
     * 交期（毫秒时间戳）
     * </pre>
     *
     * <code>int64 due_epoch_ms = 8;</code>
     * @return The dueEpochMs.
     */
    @java.lang.Override
    public long getDueEpochMs() {
      return dueEpochMs_;
    }
    /**
     * <pre>
     * 交期（毫秒时间戳）
     * </pre>
     *
     * <code>int64 due_epoch_ms = 8;</code>
     * @param value The dueEpochMs to set.
     * @return This builder for chaining.
     */
    public Builder setDueEpochMs(long value) {

      dueEpochMs_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 交期（毫秒时间戳）
     * </pre>
     *
     * <code>int64 due_epoch_ms = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearDueEpochMs() {
      bitField0_ = (bitField0_ & ~0x00000080);
      dueEpochMs_ = 0L;
      onChanged();
      return this;
    }

    private long tardinessMin_ ;
    /**
     * <pre>
     * 延迟时间（分钟）
     * </pre>
     *
     * <code>int64 tardiness_min = 9;</code>
     * @return The tardinessMin.
     */
    @java.lang.Override
    public long getTardinessMin() {
      return tardinessMin_;
    }
    /**
     * <pre>
     * 延迟时间（分钟）
     * </pre>
     *
     * <code>int64 tardiness_min = 9;</code>
     * @param value The tardinessMin to set.
     * @return This builder for chaining.
     */
    public Builder setTardinessMin(long value) {

      tardinessMin_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 延迟时间（分钟）
     * </pre>
     *
     * <code>int64 tardiness_min = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearTardinessMin() {
      bitField0_ = (bitField0_ & ~0x00000100);
      tardinessMin_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object color_ = "";
    /**
     * <pre>
     * 颜色编码
     * </pre>
     *
     * <code>string color = 10;</code>
     * @return The color.
     */
    public java.lang.String getColor() {
      java.lang.Object ref = color_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        color_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 颜色编码
     * </pre>
     *
     * <code>string color = 10;</code>
     * @return The bytes for color.
     */
    public com.google.protobuf.ByteString
        getColorBytes() {
      java.lang.Object ref = color_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        color_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 颜色编码
     * </pre>
     *
     * <code>string color = 10;</code>
     * @param value The color to set.
     * @return This builder for chaining.
     */
    public Builder setColor(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      color_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 颜色编码
     * </pre>
     *
     * <code>string color = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearColor() {
      color_ = getDefaultInstance().getColor();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 颜色编码
     * </pre>
     *
     * <code>string color = 10;</code>
     * @param value The bytes for color to set.
     * @return This builder for chaining.
     */
    public Builder setColorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      color_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private java.lang.Object config_ = "";
    /**
     * <pre>
     * 配置编码
     * </pre>
     *
     * <code>string config = 11;</code>
     * @return The config.
     */
    public java.lang.String getConfig() {
      java.lang.Object ref = config_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        config_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 配置编码
     * </pre>
     *
     * <code>string config = 11;</code>
     * @return The bytes for config.
     */
    public com.google.protobuf.ByteString
        getConfigBytes() {
      java.lang.Object ref = config_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        config_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 配置编码
     * </pre>
     *
     * <code>string config = 11;</code>
     * @param value The config to set.
     * @return This builder for chaining.
     */
    public Builder setConfig(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      config_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 配置编码
     * </pre>
     *
     * <code>string config = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearConfig() {
      config_ = getDefaultInstance().getConfig();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 配置编码
     * </pre>
     *
     * <code>string config = 11;</code>
     * @param value The bytes for config to set.
     * @return This builder for chaining.
     */
    public Builder setConfigBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      config_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    private java.lang.Object shiftId_ = "";
    /**
     * <pre>
     * 班次ID
     * </pre>
     *
     * <code>string shift_id = 12;</code>
     * @return The shiftId.
     */
    public java.lang.String getShiftId() {
      java.lang.Object ref = shiftId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        shiftId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 班次ID
     * </pre>
     *
     * <code>string shift_id = 12;</code>
     * @return The bytes for shiftId.
     */
    public com.google.protobuf.ByteString
        getShiftIdBytes() {
      java.lang.Object ref = shiftId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        shiftId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 班次ID
     * </pre>
     *
     * <code>string shift_id = 12;</code>
     * @param value The shiftId to set.
     * @return This builder for chaining.
     */
    public Builder setShiftId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      shiftId_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 班次ID
     * </pre>
     *
     * <code>string shift_id = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearShiftId() {
      shiftId_ = getDefaultInstance().getShiftId();
      bitField0_ = (bitField0_ & ~0x00000800);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 班次ID
     * </pre>
     *
     * <code>string shift_id = 12;</code>
     * @param value The bytes for shiftId to set.
     * @return This builder for chaining.
     */
    public Builder setShiftIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      shiftId_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:aps.v1.ScheduleItem)
  }

  // @@protoc_insertion_point(class_scope:aps.v1.ScheduleItem)
  private static final com.aps.grpc.proto.ScheduleItem DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.aps.grpc.proto.ScheduleItem();
  }

  public static com.aps.grpc.proto.ScheduleItem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ScheduleItem>
      PARSER = new com.google.protobuf.AbstractParser<ScheduleItem>() {
    @java.lang.Override
    public ScheduleItem parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ScheduleItem> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ScheduleItem> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.aps.grpc.proto.ScheduleItem getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

