// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aps.proto

// Protobuf Java Version: 3.25.2
package com.aps.grpc.proto;

public interface ScheduleItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aps.v1.ScheduleItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 全局顺序号
   * </pre>
   *
   * <code>int32 seq = 1;</code>
   * @return The seq.
   */
  int getSeq();

  /**
   * <pre>
   * 车辆识别码
   * </pre>
   *
   * <code>string vin = 2;</code>
   * @return The vin.
   */
  java.lang.String getVin();
  /**
   * <pre>
   * 车辆识别码
   * </pre>
   *
   * <code>string vin = 2;</code>
   * @return The bytes for vin.
   */
  com.google.protobuf.ByteString
      getVinBytes();

  /**
   * <pre>
   * 工艺类型（1冲压/2焊装/3涂装/4总装）
   * </pre>
   *
   * <code>int32 process_type = 3;</code>
   * @return The processType.
   */
  int getProcessType();

  /**
   * <pre>
   * 产线ID
   * </pre>
   *
   * <code>int64 line_id = 4;</code>
   * @return The lineId.
   */
  long getLineId();

  /**
   * <pre>
   * 班次内顺序
   * </pre>
   *
   * <code>int32 seq_in_shift = 5;</code>
   * @return The seqInShift.
   */
  int getSeqInShift();

  /**
   * <pre>
   * 开始时间（毫秒时间戳）
   * </pre>
   *
   * <code>int64 start_epoch_ms = 6;</code>
   * @return The startEpochMs.
   */
  long getStartEpochMs();

  /**
   * <pre>
   * 结束时间（毫秒时间戳）
   * </pre>
   *
   * <code>int64 end_epoch_ms = 7;</code>
   * @return The endEpochMs.
   */
  long getEndEpochMs();

  /**
   * <pre>
   * 交期（毫秒时间戳）
   * </pre>
   *
   * <code>int64 due_epoch_ms = 8;</code>
   * @return The dueEpochMs.
   */
  long getDueEpochMs();

  /**
   * <pre>
   * 延迟时间（分钟）
   * </pre>
   *
   * <code>int64 tardiness_min = 9;</code>
   * @return The tardinessMin.
   */
  long getTardinessMin();

  /**
   * <pre>
   * 颜色编码
   * </pre>
   *
   * <code>string color = 10;</code>
   * @return The color.
   */
  java.lang.String getColor();
  /**
   * <pre>
   * 颜色编码
   * </pre>
   *
   * <code>string color = 10;</code>
   * @return The bytes for color.
   */
  com.google.protobuf.ByteString
      getColorBytes();

  /**
   * <pre>
   * 配置编码
   * </pre>
   *
   * <code>string config = 11;</code>
   * @return The config.
   */
  java.lang.String getConfig();
  /**
   * <pre>
   * 配置编码
   * </pre>
   *
   * <code>string config = 11;</code>
   * @return The bytes for config.
   */
  com.google.protobuf.ByteString
      getConfigBytes();

  /**
   * <pre>
   * 班次ID
   * </pre>
   *
   * <code>string shift_id = 12;</code>
   * @return The shiftId.
   */
  java.lang.String getShiftId();
  /**
   * <pre>
   * 班次ID
   * </pre>
   *
   * <code>string shift_id = 12;</code>
   * @return The bytes for shiftId.
   */
  com.google.protobuf.ByteString
      getShiftIdBytes();
}
