// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aps.proto

// Protobuf Java Version: 3.25.2
package com.aps.grpc.proto;

/**
 * Protobuf type {@code aps.v1.ShiftViolation}
 */
public final class ShiftViolation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:aps.v1.ShiftViolation)
    ShiftViolationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ShiftViolation.newBuilder() to construct.
  private ShiftViolation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ShiftViolation() {
    shiftId_ = "";
    vtype_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ShiftViolation();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_ShiftViolation_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_ShiftViolation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.aps.grpc.proto.ShiftViolation.class, com.aps.grpc.proto.ShiftViolation.Builder.class);
  }

  public static final int SHIFT_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object shiftId_ = "";
  /**
   * <pre>
   * 班次ID
   * </pre>
   *
   * <code>string shift_id = 1;</code>
   * @return The shiftId.
   */
  @java.lang.Override
  public java.lang.String getShiftId() {
    java.lang.Object ref = shiftId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      shiftId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 班次ID
   * </pre>
   *
   * <code>string shift_id = 1;</code>
   * @return The bytes for shiftId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getShiftIdBytes() {
    java.lang.Object ref = shiftId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      shiftId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VTYPE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object vtype_ = "";
  /**
   * <pre>
   * 违反类型（ENERGY/EMISSION/MATERIAL）
   * </pre>
   *
   * <code>string vtype = 2;</code>
   * @return The vtype.
   */
  @java.lang.Override
  public java.lang.String getVtype() {
    java.lang.Object ref = vtype_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      vtype_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 违反类型（ENERGY/EMISSION/MATERIAL）
   * </pre>
   *
   * <code>string vtype = 2;</code>
   * @return The bytes for vtype.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVtypeBytes() {
    java.lang.Object ref = vtype_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      vtype_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXCESS_FIELD_NUMBER = 3;
  private double excess_ = 0D;
  /**
   * <pre>
   * 超限量
   * </pre>
   *
   * <code>double excess = 3;</code>
   * @return The excess.
   */
  @java.lang.Override
  public double getExcess() {
    return excess_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(shiftId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, shiftId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(vtype_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, vtype_);
    }
    if (java.lang.Double.doubleToRawLongBits(excess_) != 0) {
      output.writeDouble(3, excess_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(shiftId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, shiftId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(vtype_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, vtype_);
    }
    if (java.lang.Double.doubleToRawLongBits(excess_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, excess_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.aps.grpc.proto.ShiftViolation)) {
      return super.equals(obj);
    }
    com.aps.grpc.proto.ShiftViolation other = (com.aps.grpc.proto.ShiftViolation) obj;

    if (!getShiftId()
        .equals(other.getShiftId())) return false;
    if (!getVtype()
        .equals(other.getVtype())) return false;
    if (java.lang.Double.doubleToLongBits(getExcess())
        != java.lang.Double.doubleToLongBits(
            other.getExcess())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SHIFT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getShiftId().hashCode();
    hash = (37 * hash) + VTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getVtype().hashCode();
    hash = (37 * hash) + EXCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getExcess()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.aps.grpc.proto.ShiftViolation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aps.grpc.proto.ShiftViolation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aps.grpc.proto.ShiftViolation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aps.grpc.proto.ShiftViolation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aps.grpc.proto.ShiftViolation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aps.grpc.proto.ShiftViolation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aps.grpc.proto.ShiftViolation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aps.grpc.proto.ShiftViolation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.aps.grpc.proto.ShiftViolation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.aps.grpc.proto.ShiftViolation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aps.grpc.proto.ShiftViolation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aps.grpc.proto.ShiftViolation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.aps.grpc.proto.ShiftViolation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code aps.v1.ShiftViolation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:aps.v1.ShiftViolation)
      com.aps.grpc.proto.ShiftViolationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_ShiftViolation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_ShiftViolation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aps.grpc.proto.ShiftViolation.class, com.aps.grpc.proto.ShiftViolation.Builder.class);
    }

    // Construct using com.aps.grpc.proto.ShiftViolation.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      shiftId_ = "";
      vtype_ = "";
      excess_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_ShiftViolation_descriptor;
    }

    @java.lang.Override
    public com.aps.grpc.proto.ShiftViolation getDefaultInstanceForType() {
      return com.aps.grpc.proto.ShiftViolation.getDefaultInstance();
    }

    @java.lang.Override
    public com.aps.grpc.proto.ShiftViolation build() {
      com.aps.grpc.proto.ShiftViolation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.aps.grpc.proto.ShiftViolation buildPartial() {
      com.aps.grpc.proto.ShiftViolation result = new com.aps.grpc.proto.ShiftViolation(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.aps.grpc.proto.ShiftViolation result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.shiftId_ = shiftId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.vtype_ = vtype_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.excess_ = excess_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.aps.grpc.proto.ShiftViolation) {
        return mergeFrom((com.aps.grpc.proto.ShiftViolation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.aps.grpc.proto.ShiftViolation other) {
      if (other == com.aps.grpc.proto.ShiftViolation.getDefaultInstance()) return this;
      if (!other.getShiftId().isEmpty()) {
        shiftId_ = other.shiftId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getVtype().isEmpty()) {
        vtype_ = other.vtype_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getExcess() != 0D) {
        setExcess(other.getExcess());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              shiftId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              vtype_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 25: {
              excess_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object shiftId_ = "";
    /**
     * <pre>
     * 班次ID
     * </pre>
     *
     * <code>string shift_id = 1;</code>
     * @return The shiftId.
     */
    public java.lang.String getShiftId() {
      java.lang.Object ref = shiftId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        shiftId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 班次ID
     * </pre>
     *
     * <code>string shift_id = 1;</code>
     * @return The bytes for shiftId.
     */
    public com.google.protobuf.ByteString
        getShiftIdBytes() {
      java.lang.Object ref = shiftId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        shiftId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 班次ID
     * </pre>
     *
     * <code>string shift_id = 1;</code>
     * @param value The shiftId to set.
     * @return This builder for chaining.
     */
    public Builder setShiftId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      shiftId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 班次ID
     * </pre>
     *
     * <code>string shift_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearShiftId() {
      shiftId_ = getDefaultInstance().getShiftId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 班次ID
     * </pre>
     *
     * <code>string shift_id = 1;</code>
     * @param value The bytes for shiftId to set.
     * @return This builder for chaining.
     */
    public Builder setShiftIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      shiftId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object vtype_ = "";
    /**
     * <pre>
     * 违反类型（ENERGY/EMISSION/MATERIAL）
     * </pre>
     *
     * <code>string vtype = 2;</code>
     * @return The vtype.
     */
    public java.lang.String getVtype() {
      java.lang.Object ref = vtype_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vtype_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 违反类型（ENERGY/EMISSION/MATERIAL）
     * </pre>
     *
     * <code>string vtype = 2;</code>
     * @return The bytes for vtype.
     */
    public com.google.protobuf.ByteString
        getVtypeBytes() {
      java.lang.Object ref = vtype_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vtype_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 违反类型（ENERGY/EMISSION/MATERIAL）
     * </pre>
     *
     * <code>string vtype = 2;</code>
     * @param value The vtype to set.
     * @return This builder for chaining.
     */
    public Builder setVtype(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      vtype_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 违反类型（ENERGY/EMISSION/MATERIAL）
     * </pre>
     *
     * <code>string vtype = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVtype() {
      vtype_ = getDefaultInstance().getVtype();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 违反类型（ENERGY/EMISSION/MATERIAL）
     * </pre>
     *
     * <code>string vtype = 2;</code>
     * @param value The bytes for vtype to set.
     * @return This builder for chaining.
     */
    public Builder setVtypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      vtype_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private double excess_ ;
    /**
     * <pre>
     * 超限量
     * </pre>
     *
     * <code>double excess = 3;</code>
     * @return The excess.
     */
    @java.lang.Override
    public double getExcess() {
      return excess_;
    }
    /**
     * <pre>
     * 超限量
     * </pre>
     *
     * <code>double excess = 3;</code>
     * @param value The excess to set.
     * @return This builder for chaining.
     */
    public Builder setExcess(double value) {

      excess_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 超限量
     * </pre>
     *
     * <code>double excess = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearExcess() {
      bitField0_ = (bitField0_ & ~0x00000004);
      excess_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:aps.v1.ShiftViolation)
  }

  // @@protoc_insertion_point(class_scope:aps.v1.ShiftViolation)
  private static final com.aps.grpc.proto.ShiftViolation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.aps.grpc.proto.ShiftViolation();
  }

  public static com.aps.grpc.proto.ShiftViolation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ShiftViolation>
      PARSER = new com.google.protobuf.AbstractParser<ShiftViolation>() {
    @java.lang.Override
    public ShiftViolation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ShiftViolation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ShiftViolation> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.aps.grpc.proto.ShiftViolation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

