// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aps.proto

// Protobuf Java Version: 3.25.2
package com.aps.grpc.proto;

public interface ShiftViolationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aps.v1.ShiftViolation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 班次ID
   * </pre>
   *
   * <code>string shift_id = 1;</code>
   * @return The shiftId.
   */
  java.lang.String getShiftId();
  /**
   * <pre>
   * 班次ID
   * </pre>
   *
   * <code>string shift_id = 1;</code>
   * @return The bytes for shiftId.
   */
  com.google.protobuf.ByteString
      getShiftIdBytes();

  /**
   * <pre>
   * 违反类型（ENERGY/EMISSION/MATERIAL）
   * </pre>
   *
   * <code>string vtype = 2;</code>
   * @return The vtype.
   */
  java.lang.String getVtype();
  /**
   * <pre>
   * 违反类型（ENERGY/EMISSION/MATERIAL）
   * </pre>
   *
   * <code>string vtype = 2;</code>
   * @return The bytes for vtype.
   */
  com.google.protobuf.ByteString
      getVtypeBytes();

  /**
   * <pre>
   * 超限量
   * </pre>
   *
   * <code>double excess = 3;</code>
   * @return The excess.
   */
  double getExcess();
}
