// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aps.proto

// Protobuf Java Version: 3.25.2
package com.aps.grpc.proto;

public interface SolveRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aps.v1.SolveRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 请求唯一标识
   * </pre>
   *
   * <code>string request_id = 1;</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <pre>
   * 请求唯一标识
   * </pre>
   *
   * <code>string request_id = 1;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <pre>
   * 排产起始时间（毫秒时间戳）
   * </pre>
   *
   * <code>int64 plan_start_epoch_ms = 2;</code>
   * @return The planStartEpochMs.
   */
  long getPlanStartEpochMs();

  /**
   * <pre>
   * 待排产订单列表
   * </pre>
   *
   * <code>repeated .aps.v1.Job jobs = 3;</code>
   */
  java.util.List<com.aps.grpc.proto.Job> 
      getJobsList();
  /**
   * <pre>
   * 待排产订单列表
   * </pre>
   *
   * <code>repeated .aps.v1.Job jobs = 3;</code>
   */
  com.aps.grpc.proto.Job getJobs(int index);
  /**
   * <pre>
   * 待排产订单列表
   * </pre>
   *
   * <code>repeated .aps.v1.Job jobs = 3;</code>
   */
  int getJobsCount();
  /**
   * <pre>
   * 待排产订单列表
   * </pre>
   *
   * <code>repeated .aps.v1.Job jobs = 3;</code>
   */
  java.util.List<? extends com.aps.grpc.proto.JobOrBuilder> 
      getJobsOrBuilderList();
  /**
   * <pre>
   * 待排产订单列表
   * </pre>
   *
   * <code>repeated .aps.v1.Job jobs = 3;</code>
   */
  com.aps.grpc.proto.JobOrBuilder getJobsOrBuilder(
      int index);

  /**
   * <pre>
   * 求解参数
   * </pre>
   *
   * <code>.aps.v1.SolveParams params = 4;</code>
   * @return Whether the params field is set.
   */
  boolean hasParams();
  /**
   * <pre>
   * 求解参数
   * </pre>
   *
   * <code>.aps.v1.SolveParams params = 4;</code>
   * @return The params.
   */
  com.aps.grpc.proto.SolveParams getParams();
  /**
   * <pre>
   * 求解参数
   * </pre>
   *
   * <code>.aps.v1.SolveParams params = 4;</code>
   */
  com.aps.grpc.proto.SolveParamsOrBuilder getParamsOrBuilder();
}
