// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aps.proto

// Protobuf Java Version: 3.25.2
package com.aps.grpc.proto;

public interface SolveResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aps.v1.SolveResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 请求ID（回显）
   * </pre>
   *
   * <code>string request_id = 1;</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <pre>
   * 请求ID（回显）
   * </pre>
   *
   * <code>string request_id = 1;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <pre>
   * 优化方案KPI
   * </pre>
   *
   * <code>.aps.v1.KpiSummary summary = 2;</code>
   * @return Whether the summary field is set.
   */
  boolean hasSummary();
  /**
   * <pre>
   * 优化方案KPI
   * </pre>
   *
   * <code>.aps.v1.KpiSummary summary = 2;</code>
   * @return The summary.
   */
  com.aps.grpc.proto.KpiSummary getSummary();
  /**
   * <pre>
   * 优化方案KPI
   * </pre>
   *
   * <code>.aps.v1.KpiSummary summary = 2;</code>
   */
  com.aps.grpc.proto.KpiSummaryOrBuilder getSummaryOrBuilder();

  /**
   * <pre>
   * 基准方案KPI
   * </pre>
   *
   * <code>.aps.v1.KpiSummary baseline_summary = 3;</code>
   * @return Whether the baselineSummary field is set.
   */
  boolean hasBaselineSummary();
  /**
   * <pre>
   * 基准方案KPI
   * </pre>
   *
   * <code>.aps.v1.KpiSummary baseline_summary = 3;</code>
   * @return The baselineSummary.
   */
  com.aps.grpc.proto.KpiSummary getBaselineSummary();
  /**
   * <pre>
   * 基准方案KPI
   * </pre>
   *
   * <code>.aps.v1.KpiSummary baseline_summary = 3;</code>
   */
  com.aps.grpc.proto.KpiSummaryOrBuilder getBaselineSummaryOrBuilder();

  /**
   * <pre>
   * 排产顺序（VIN列表）
   * </pre>
   *
   * <code>repeated string order = 4;</code>
   * @return A list containing the order.
   */
  java.util.List<java.lang.String>
      getOrderList();
  /**
   * <pre>
   * 排产顺序（VIN列表）
   * </pre>
   *
   * <code>repeated string order = 4;</code>
   * @return The count of order.
   */
  int getOrderCount();
  /**
   * <pre>
   * 排产顺序（VIN列表）
   * </pre>
   *
   * <code>repeated string order = 4;</code>
   * @param index The index of the element to return.
   * @return The order at the given index.
   */
  java.lang.String getOrder(int index);
  /**
   * <pre>
   * 排产顺序（VIN列表）
   * </pre>
   *
   * <code>repeated string order = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the order at the given index.
   */
  com.google.protobuf.ByteString
      getOrderBytes(int index);

  /**
   * <pre>
   * 简化调度表
   * </pre>
   *
   * <code>repeated .aps.v1.ScheduleItem schedule = 5;</code>
   */
  java.util.List<com.aps.grpc.proto.ScheduleItem> 
      getScheduleList();
  /**
   * <pre>
   * 简化调度表
   * </pre>
   *
   * <code>repeated .aps.v1.ScheduleItem schedule = 5;</code>
   */
  com.aps.grpc.proto.ScheduleItem getSchedule(int index);
  /**
   * <pre>
   * 简化调度表
   * </pre>
   *
   * <code>repeated .aps.v1.ScheduleItem schedule = 5;</code>
   */
  int getScheduleCount();
  /**
   * <pre>
   * 简化调度表
   * </pre>
   *
   * <code>repeated .aps.v1.ScheduleItem schedule = 5;</code>
   */
  java.util.List<? extends com.aps.grpc.proto.ScheduleItemOrBuilder> 
      getScheduleOrBuilderList();
  /**
   * <pre>
   * 简化调度表
   * </pre>
   *
   * <code>repeated .aps.v1.ScheduleItem schedule = 5;</code>
   */
  com.aps.grpc.proto.ScheduleItemOrBuilder getScheduleOrBuilder(
      int index);

  /**
   * <pre>
   * 详细调度表
   * </pre>
   *
   * <code>repeated .aps.v1.ScheduleItem detailed_schedule = 6;</code>
   */
  java.util.List<com.aps.grpc.proto.ScheduleItem> 
      getDetailedScheduleList();
  /**
   * <pre>
   * 详细调度表
   * </pre>
   *
   * <code>repeated .aps.v1.ScheduleItem detailed_schedule = 6;</code>
   */
  com.aps.grpc.proto.ScheduleItem getDetailedSchedule(int index);
  /**
   * <pre>
   * 详细调度表
   * </pre>
   *
   * <code>repeated .aps.v1.ScheduleItem detailed_schedule = 6;</code>
   */
  int getDetailedScheduleCount();
  /**
   * <pre>
   * 详细调度表
   * </pre>
   *
   * <code>repeated .aps.v1.ScheduleItem detailed_schedule = 6;</code>
   */
  java.util.List<? extends com.aps.grpc.proto.ScheduleItemOrBuilder> 
      getDetailedScheduleOrBuilderList();
  /**
   * <pre>
   * 详细调度表
   * </pre>
   *
   * <code>repeated .aps.v1.ScheduleItem detailed_schedule = 6;</code>
   */
  com.aps.grpc.proto.ScheduleItemOrBuilder getDetailedScheduleOrBuilder(
      int index);

  /**
   * <pre>
   * 约束违反列表
   * </pre>
   *
   * <code>repeated .aps.v1.ShiftViolation violations = 7;</code>
   */
  java.util.List<com.aps.grpc.proto.ShiftViolation> 
      getViolationsList();
  /**
   * <pre>
   * 约束违反列表
   * </pre>
   *
   * <code>repeated .aps.v1.ShiftViolation violations = 7;</code>
   */
  com.aps.grpc.proto.ShiftViolation getViolations(int index);
  /**
   * <pre>
   * 约束违反列表
   * </pre>
   *
   * <code>repeated .aps.v1.ShiftViolation violations = 7;</code>
   */
  int getViolationsCount();
  /**
   * <pre>
   * 约束违反列表
   * </pre>
   *
   * <code>repeated .aps.v1.ShiftViolation violations = 7;</code>
   */
  java.util.List<? extends com.aps.grpc.proto.ShiftViolationOrBuilder> 
      getViolationsOrBuilderList();
  /**
   * <pre>
   * 约束违反列表
   * </pre>
   *
   * <code>repeated .aps.v1.ShiftViolation violations = 7;</code>
   */
  com.aps.grpc.proto.ShiftViolationOrBuilder getViolationsOrBuilder(
      int index);

  /**
   * <pre>
   * 收敛曲线
   * </pre>
   *
   * <code>repeated .aps.v1.ConvergencePoint convergence = 8;</code>
   */
  java.util.List<com.aps.grpc.proto.ConvergencePoint> 
      getConvergenceList();
  /**
   * <pre>
   * 收敛曲线
   * </pre>
   *
   * <code>repeated .aps.v1.ConvergencePoint convergence = 8;</code>
   */
  com.aps.grpc.proto.ConvergencePoint getConvergence(int index);
  /**
   * <pre>
   * 收敛曲线
   * </pre>
   *
   * <code>repeated .aps.v1.ConvergencePoint convergence = 8;</code>
   */
  int getConvergenceCount();
  /**
   * <pre>
   * 收敛曲线
   * </pre>
   *
   * <code>repeated .aps.v1.ConvergencePoint convergence = 8;</code>
   */
  java.util.List<? extends com.aps.grpc.proto.ConvergencePointOrBuilder> 
      getConvergenceOrBuilderList();
  /**
   * <pre>
   * 收敛曲线
   * </pre>
   *
   * <code>repeated .aps.v1.ConvergencePoint convergence = 8;</code>
   */
  com.aps.grpc.proto.ConvergencePointOrBuilder getConvergenceOrBuilder(
      int index);

  /**
   * <pre>
   * 引擎版本号
   * </pre>
   *
   * <code>string engine_version = 9;</code>
   * @return The engineVersion.
   */
  java.lang.String getEngineVersion();
  /**
   * <pre>
   * 引擎版本号
   * </pre>
   *
   * <code>string engine_version = 9;</code>
   * @return The bytes for engineVersion.
   */
  com.google.protobuf.ByteString
      getEngineVersionBytes();

  /**
   * <pre>
   * 警告信息
   * </pre>
   *
   * <code>repeated string warnings = 10;</code>
   * @return A list containing the warnings.
   */
  java.util.List<java.lang.String>
      getWarningsList();
  /**
   * <pre>
   * 警告信息
   * </pre>
   *
   * <code>repeated string warnings = 10;</code>
   * @return The count of warnings.
   */
  int getWarningsCount();
  /**
   * <pre>
   * 警告信息
   * </pre>
   *
   * <code>repeated string warnings = 10;</code>
   * @param index The index of the element to return.
   * @return The warnings at the given index.
   */
  java.lang.String getWarnings(int index);
  /**
   * <pre>
   * 警告信息
   * </pre>
   *
   * <code>repeated string warnings = 10;</code>
   * @param index The index of the value to return.
   * @return The bytes of the warnings at the given index.
   */
  com.google.protobuf.ByteString
      getWarningsBytes(int index);
}
