// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aps.proto

// Protobuf Java Version: 3.25.2
package com.aps.grpc.proto;

/**
 * Protobuf type {@code aps.v1.SolveParams}
 */
public final class SolveParams extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:aps.v1.SolveParams)
    SolveParamsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SolveParams.newBuilder() to construct.
  private SolveParams(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SolveParams() {
    algorithm_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SolveParams();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_SolveParams_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_SolveParams_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.aps.grpc.proto.SolveParams.class, com.aps.grpc.proto.SolveParams.Builder.class);
  }

  private int bitField0_;
  public static final int ALGORITHM_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object algorithm_ = "";
  /**
   * <pre>
   * 算法选择: baseline/sa/hybrid
   * </pre>
   *
   * <code>string algorithm = 1;</code>
   * @return The algorithm.
   */
  @java.lang.Override
  public java.lang.String getAlgorithm() {
    java.lang.Object ref = algorithm_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      algorithm_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 算法选择: baseline/sa/hybrid
   * </pre>
   *
   * <code>string algorithm = 1;</code>
   * @return The bytes for algorithm.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAlgorithmBytes() {
    java.lang.Object ref = algorithm_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      algorithm_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIME_BUDGET_SEC_FIELD_NUMBER = 2;
  private int timeBudgetSec_ = 0;
  /**
   * <pre>
   * 求解时间预算（秒）
   * </pre>
   *
   * <code>int32 time_budget_sec = 2;</code>
   * @return The timeBudgetSec.
   */
  @java.lang.Override
  public int getTimeBudgetSec() {
    return timeBudgetSec_;
  }

  public static final int SEED_FIELD_NUMBER = 3;
  private long seed_ = 0L;
  /**
   * <pre>
   * 随机种子
   * </pre>
   *
   * <code>int64 seed = 3;</code>
   * @return The seed.
   */
  @java.lang.Override
  public long getSeed() {
    return seed_;
  }

  public static final int WEIGHTS_FIELD_NUMBER = 4;
  private com.aps.grpc.proto.Weights weights_;
  /**
   * <pre>
   * 目标权重
   * </pre>
   *
   * <code>.aps.v1.Weights weights = 4;</code>
   * @return Whether the weights field is set.
   */
  @java.lang.Override
  public boolean hasWeights() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * 目标权重
   * </pre>
   *
   * <code>.aps.v1.Weights weights = 4;</code>
   * @return The weights.
   */
  @java.lang.Override
  public com.aps.grpc.proto.Weights getWeights() {
    return weights_ == null ? com.aps.grpc.proto.Weights.getDefaultInstance() : weights_;
  }
  /**
   * <pre>
   * 目标权重
   * </pre>
   *
   * <code>.aps.v1.Weights weights = 4;</code>
   */
  @java.lang.Override
  public com.aps.grpc.proto.WeightsOrBuilder getWeightsOrBuilder() {
    return weights_ == null ? com.aps.grpc.proto.Weights.getDefaultInstance() : weights_;
  }

  public static final int LIMITS_FIELD_NUMBER = 5;
  private com.aps.grpc.proto.Limits limits_;
  /**
   * <pre>
   * 资源限制
   * </pre>
   *
   * <code>.aps.v1.Limits limits = 5;</code>
   * @return Whether the limits field is set.
   */
  @java.lang.Override
  public boolean hasLimits() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * 资源限制
   * </pre>
   *
   * <code>.aps.v1.Limits limits = 5;</code>
   * @return The limits.
   */
  @java.lang.Override
  public com.aps.grpc.proto.Limits getLimits() {
    return limits_ == null ? com.aps.grpc.proto.Limits.getDefaultInstance() : limits_;
  }
  /**
   * <pre>
   * 资源限制
   * </pre>
   *
   * <code>.aps.v1.Limits limits = 5;</code>
   */
  @java.lang.Override
  public com.aps.grpc.proto.LimitsOrBuilder getLimitsOrBuilder() {
    return limits_ == null ? com.aps.grpc.proto.Limits.getDefaultInstance() : limits_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(algorithm_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, algorithm_);
    }
    if (timeBudgetSec_ != 0) {
      output.writeInt32(2, timeBudgetSec_);
    }
    if (seed_ != 0L) {
      output.writeInt64(3, seed_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(4, getWeights());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(5, getLimits());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(algorithm_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, algorithm_);
    }
    if (timeBudgetSec_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, timeBudgetSec_);
    }
    if (seed_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, seed_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getWeights());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getLimits());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.aps.grpc.proto.SolveParams)) {
      return super.equals(obj);
    }
    com.aps.grpc.proto.SolveParams other = (com.aps.grpc.proto.SolveParams) obj;

    if (!getAlgorithm()
        .equals(other.getAlgorithm())) return false;
    if (getTimeBudgetSec()
        != other.getTimeBudgetSec()) return false;
    if (getSeed()
        != other.getSeed()) return false;
    if (hasWeights() != other.hasWeights()) return false;
    if (hasWeights()) {
      if (!getWeights()
          .equals(other.getWeights())) return false;
    }
    if (hasLimits() != other.hasLimits()) return false;
    if (hasLimits()) {
      if (!getLimits()
          .equals(other.getLimits())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ALGORITHM_FIELD_NUMBER;
    hash = (53 * hash) + getAlgorithm().hashCode();
    hash = (37 * hash) + TIME_BUDGET_SEC_FIELD_NUMBER;
    hash = (53 * hash) + getTimeBudgetSec();
    hash = (37 * hash) + SEED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSeed());
    if (hasWeights()) {
      hash = (37 * hash) + WEIGHTS_FIELD_NUMBER;
      hash = (53 * hash) + getWeights().hashCode();
    }
    if (hasLimits()) {
      hash = (37 * hash) + LIMITS_FIELD_NUMBER;
      hash = (53 * hash) + getLimits().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.aps.grpc.proto.SolveParams parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aps.grpc.proto.SolveParams parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aps.grpc.proto.SolveParams parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aps.grpc.proto.SolveParams parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aps.grpc.proto.SolveParams parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aps.grpc.proto.SolveParams parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aps.grpc.proto.SolveParams parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aps.grpc.proto.SolveParams parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.aps.grpc.proto.SolveParams parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.aps.grpc.proto.SolveParams parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aps.grpc.proto.SolveParams parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aps.grpc.proto.SolveParams parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.aps.grpc.proto.SolveParams prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code aps.v1.SolveParams}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:aps.v1.SolveParams)
      com.aps.grpc.proto.SolveParamsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_SolveParams_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_SolveParams_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aps.grpc.proto.SolveParams.class, com.aps.grpc.proto.SolveParams.Builder.class);
    }

    // Construct using com.aps.grpc.proto.SolveParams.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getWeightsFieldBuilder();
        getLimitsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      algorithm_ = "";
      timeBudgetSec_ = 0;
      seed_ = 0L;
      weights_ = null;
      if (weightsBuilder_ != null) {
        weightsBuilder_.dispose();
        weightsBuilder_ = null;
      }
      limits_ = null;
      if (limitsBuilder_ != null) {
        limitsBuilder_.dispose();
        limitsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_SolveParams_descriptor;
    }

    @java.lang.Override
    public com.aps.grpc.proto.SolveParams getDefaultInstanceForType() {
      return com.aps.grpc.proto.SolveParams.getDefaultInstance();
    }

    @java.lang.Override
    public com.aps.grpc.proto.SolveParams build() {
      com.aps.grpc.proto.SolveParams result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.aps.grpc.proto.SolveParams buildPartial() {
      com.aps.grpc.proto.SolveParams result = new com.aps.grpc.proto.SolveParams(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.aps.grpc.proto.SolveParams result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.algorithm_ = algorithm_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.timeBudgetSec_ = timeBudgetSec_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.seed_ = seed_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.weights_ = weightsBuilder_ == null
            ? weights_
            : weightsBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.limits_ = limitsBuilder_ == null
            ? limits_
            : limitsBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.aps.grpc.proto.SolveParams) {
        return mergeFrom((com.aps.grpc.proto.SolveParams)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.aps.grpc.proto.SolveParams other) {
      if (other == com.aps.grpc.proto.SolveParams.getDefaultInstance()) return this;
      if (!other.getAlgorithm().isEmpty()) {
        algorithm_ = other.algorithm_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getTimeBudgetSec() != 0) {
        setTimeBudgetSec(other.getTimeBudgetSec());
      }
      if (other.getSeed() != 0L) {
        setSeed(other.getSeed());
      }
      if (other.hasWeights()) {
        mergeWeights(other.getWeights());
      }
      if (other.hasLimits()) {
        mergeLimits(other.getLimits());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              algorithm_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              timeBudgetSec_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              seed_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              input.readMessage(
                  getWeightsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getLimitsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object algorithm_ = "";
    /**
     * <pre>
     * 算法选择: baseline/sa/hybrid
     * </pre>
     *
     * <code>string algorithm = 1;</code>
     * @return The algorithm.
     */
    public java.lang.String getAlgorithm() {
      java.lang.Object ref = algorithm_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        algorithm_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 算法选择: baseline/sa/hybrid
     * </pre>
     *
     * <code>string algorithm = 1;</code>
     * @return The bytes for algorithm.
     */
    public com.google.protobuf.ByteString
        getAlgorithmBytes() {
      java.lang.Object ref = algorithm_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        algorithm_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 算法选择: baseline/sa/hybrid
     * </pre>
     *
     * <code>string algorithm = 1;</code>
     * @param value The algorithm to set.
     * @return This builder for chaining.
     */
    public Builder setAlgorithm(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      algorithm_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 算法选择: baseline/sa/hybrid
     * </pre>
     *
     * <code>string algorithm = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAlgorithm() {
      algorithm_ = getDefaultInstance().getAlgorithm();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 算法选择: baseline/sa/hybrid
     * </pre>
     *
     * <code>string algorithm = 1;</code>
     * @param value The bytes for algorithm to set.
     * @return This builder for chaining.
     */
    public Builder setAlgorithmBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      algorithm_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int timeBudgetSec_ ;
    /**
     * <pre>
     * 求解时间预算（秒）
     * </pre>
     *
     * <code>int32 time_budget_sec = 2;</code>
     * @return The timeBudgetSec.
     */
    @java.lang.Override
    public int getTimeBudgetSec() {
      return timeBudgetSec_;
    }
    /**
     * <pre>
     * 求解时间预算（秒）
     * </pre>
     *
     * <code>int32 time_budget_sec = 2;</code>
     * @param value The timeBudgetSec to set.
     * @return This builder for chaining.
     */
    public Builder setTimeBudgetSec(int value) {

      timeBudgetSec_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 求解时间预算（秒）
     * </pre>
     *
     * <code>int32 time_budget_sec = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeBudgetSec() {
      bitField0_ = (bitField0_ & ~0x00000002);
      timeBudgetSec_ = 0;
      onChanged();
      return this;
    }

    private long seed_ ;
    /**
     * <pre>
     * 随机种子
     * </pre>
     *
     * <code>int64 seed = 3;</code>
     * @return The seed.
     */
    @java.lang.Override
    public long getSeed() {
      return seed_;
    }
    /**
     * <pre>
     * 随机种子
     * </pre>
     *
     * <code>int64 seed = 3;</code>
     * @param value The seed to set.
     * @return This builder for chaining.
     */
    public Builder setSeed(long value) {

      seed_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 随机种子
     * </pre>
     *
     * <code>int64 seed = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeed() {
      bitField0_ = (bitField0_ & ~0x00000004);
      seed_ = 0L;
      onChanged();
      return this;
    }

    private com.aps.grpc.proto.Weights weights_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.aps.grpc.proto.Weights, com.aps.grpc.proto.Weights.Builder, com.aps.grpc.proto.WeightsOrBuilder> weightsBuilder_;
    /**
     * <pre>
     * 目标权重
     * </pre>
     *
     * <code>.aps.v1.Weights weights = 4;</code>
     * @return Whether the weights field is set.
     */
    public boolean hasWeights() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * 目标权重
     * </pre>
     *
     * <code>.aps.v1.Weights weights = 4;</code>
     * @return The weights.
     */
    public com.aps.grpc.proto.Weights getWeights() {
      if (weightsBuilder_ == null) {
        return weights_ == null ? com.aps.grpc.proto.Weights.getDefaultInstance() : weights_;
      } else {
        return weightsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 目标权重
     * </pre>
     *
     * <code>.aps.v1.Weights weights = 4;</code>
     */
    public Builder setWeights(com.aps.grpc.proto.Weights value) {
      if (weightsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        weights_ = value;
      } else {
        weightsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 目标权重
     * </pre>
     *
     * <code>.aps.v1.Weights weights = 4;</code>
     */
    public Builder setWeights(
        com.aps.grpc.proto.Weights.Builder builderForValue) {
      if (weightsBuilder_ == null) {
        weights_ = builderForValue.build();
      } else {
        weightsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 目标权重
     * </pre>
     *
     * <code>.aps.v1.Weights weights = 4;</code>
     */
    public Builder mergeWeights(com.aps.grpc.proto.Weights value) {
      if (weightsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          weights_ != null &&
          weights_ != com.aps.grpc.proto.Weights.getDefaultInstance()) {
          getWeightsBuilder().mergeFrom(value);
        } else {
          weights_ = value;
        }
      } else {
        weightsBuilder_.mergeFrom(value);
      }
      if (weights_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * 目标权重
     * </pre>
     *
     * <code>.aps.v1.Weights weights = 4;</code>
     */
    public Builder clearWeights() {
      bitField0_ = (bitField0_ & ~0x00000008);
      weights_ = null;
      if (weightsBuilder_ != null) {
        weightsBuilder_.dispose();
        weightsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 目标权重
     * </pre>
     *
     * <code>.aps.v1.Weights weights = 4;</code>
     */
    public com.aps.grpc.proto.Weights.Builder getWeightsBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getWeightsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 目标权重
     * </pre>
     *
     * <code>.aps.v1.Weights weights = 4;</code>
     */
    public com.aps.grpc.proto.WeightsOrBuilder getWeightsOrBuilder() {
      if (weightsBuilder_ != null) {
        return weightsBuilder_.getMessageOrBuilder();
      } else {
        return weights_ == null ?
            com.aps.grpc.proto.Weights.getDefaultInstance() : weights_;
      }
    }
    /**
     * <pre>
     * 目标权重
     * </pre>
     *
     * <code>.aps.v1.Weights weights = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.aps.grpc.proto.Weights, com.aps.grpc.proto.Weights.Builder, com.aps.grpc.proto.WeightsOrBuilder> 
        getWeightsFieldBuilder() {
      if (weightsBuilder_ == null) {
        weightsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.aps.grpc.proto.Weights, com.aps.grpc.proto.Weights.Builder, com.aps.grpc.proto.WeightsOrBuilder>(
                getWeights(),
                getParentForChildren(),
                isClean());
        weights_ = null;
      }
      return weightsBuilder_;
    }

    private com.aps.grpc.proto.Limits limits_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.aps.grpc.proto.Limits, com.aps.grpc.proto.Limits.Builder, com.aps.grpc.proto.LimitsOrBuilder> limitsBuilder_;
    /**
     * <pre>
     * 资源限制
     * </pre>
     *
     * <code>.aps.v1.Limits limits = 5;</code>
     * @return Whether the limits field is set.
     */
    public boolean hasLimits() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * 资源限制
     * </pre>
     *
     * <code>.aps.v1.Limits limits = 5;</code>
     * @return The limits.
     */
    public com.aps.grpc.proto.Limits getLimits() {
      if (limitsBuilder_ == null) {
        return limits_ == null ? com.aps.grpc.proto.Limits.getDefaultInstance() : limits_;
      } else {
        return limitsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 资源限制
     * </pre>
     *
     * <code>.aps.v1.Limits limits = 5;</code>
     */
    public Builder setLimits(com.aps.grpc.proto.Limits value) {
      if (limitsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        limits_ = value;
      } else {
        limitsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 资源限制
     * </pre>
     *
     * <code>.aps.v1.Limits limits = 5;</code>
     */
    public Builder setLimits(
        com.aps.grpc.proto.Limits.Builder builderForValue) {
      if (limitsBuilder_ == null) {
        limits_ = builderForValue.build();
      } else {
        limitsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 资源限制
     * </pre>
     *
     * <code>.aps.v1.Limits limits = 5;</code>
     */
    public Builder mergeLimits(com.aps.grpc.proto.Limits value) {
      if (limitsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          limits_ != null &&
          limits_ != com.aps.grpc.proto.Limits.getDefaultInstance()) {
          getLimitsBuilder().mergeFrom(value);
        } else {
          limits_ = value;
        }
      } else {
        limitsBuilder_.mergeFrom(value);
      }
      if (limits_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * 资源限制
     * </pre>
     *
     * <code>.aps.v1.Limits limits = 5;</code>
     */
    public Builder clearLimits() {
      bitField0_ = (bitField0_ & ~0x00000010);
      limits_ = null;
      if (limitsBuilder_ != null) {
        limitsBuilder_.dispose();
        limitsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 资源限制
     * </pre>
     *
     * <code>.aps.v1.Limits limits = 5;</code>
     */
    public com.aps.grpc.proto.Limits.Builder getLimitsBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getLimitsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 资源限制
     * </pre>
     *
     * <code>.aps.v1.Limits limits = 5;</code>
     */
    public com.aps.grpc.proto.LimitsOrBuilder getLimitsOrBuilder() {
      if (limitsBuilder_ != null) {
        return limitsBuilder_.getMessageOrBuilder();
      } else {
        return limits_ == null ?
            com.aps.grpc.proto.Limits.getDefaultInstance() : limits_;
      }
    }
    /**
     * <pre>
     * 资源限制
     * </pre>
     *
     * <code>.aps.v1.Limits limits = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.aps.grpc.proto.Limits, com.aps.grpc.proto.Limits.Builder, com.aps.grpc.proto.LimitsOrBuilder> 
        getLimitsFieldBuilder() {
      if (limitsBuilder_ == null) {
        limitsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.aps.grpc.proto.Limits, com.aps.grpc.proto.Limits.Builder, com.aps.grpc.proto.LimitsOrBuilder>(
                getLimits(),
                getParentForChildren(),
                isClean());
        limits_ = null;
      }
      return limitsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:aps.v1.SolveParams)
  }

  // @@protoc_insertion_point(class_scope:aps.v1.SolveParams)
  private static final com.aps.grpc.proto.SolveParams DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.aps.grpc.proto.SolveParams();
  }

  public static com.aps.grpc.proto.SolveParams getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SolveParams>
      PARSER = new com.google.protobuf.AbstractParser<SolveParams>() {
    @java.lang.Override
    public SolveParams parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SolveParams> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SolveParams> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.aps.grpc.proto.SolveParams getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

