// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aps.proto

// Protobuf Java Version: 3.25.2
package com.aps.grpc.proto;

/**
 * Protobuf type {@code aps.v1.SolveRequest}
 */
public final class SolveRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:aps.v1.SolveRequest)
    SolveRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SolveRequest.newBuilder() to construct.
  private SolveRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SolveRequest() {
    requestId_ = "";
    jobs_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SolveRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_SolveRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_SolveRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.aps.grpc.proto.SolveRequest.class, com.aps.grpc.proto.SolveRequest.Builder.class);
  }

  private int bitField0_;
  public static final int REQUEST_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object requestId_ = "";
  /**
   * <pre>
   * 请求唯一标识
   * </pre>
   *
   * <code>string request_id = 1;</code>
   * @return The requestId.
   */
  @java.lang.Override
  public java.lang.String getRequestId() {
    java.lang.Object ref = requestId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requestId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 请求唯一标识
   * </pre>
   *
   * <code>string request_id = 1;</code>
   * @return The bytes for requestId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRequestIdBytes() {
    java.lang.Object ref = requestId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLAN_START_EPOCH_MS_FIELD_NUMBER = 2;
  private long planStartEpochMs_ = 0L;
  /**
   * <pre>
   * 排产起始时间（毫秒时间戳）
   * </pre>
   *
   * <code>int64 plan_start_epoch_ms = 2;</code>
   * @return The planStartEpochMs.
   */
  @java.lang.Override
  public long getPlanStartEpochMs() {
    return planStartEpochMs_;
  }

  public static final int JOBS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.aps.grpc.proto.Job> jobs_;
  /**
   * <pre>
   * 待排产订单列表
   * </pre>
   *
   * <code>repeated .aps.v1.Job jobs = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.aps.grpc.proto.Job> getJobsList() {
    return jobs_;
  }
  /**
   * <pre>
   * 待排产订单列表
   * </pre>
   *
   * <code>repeated .aps.v1.Job jobs = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.aps.grpc.proto.JobOrBuilder> 
      getJobsOrBuilderList() {
    return jobs_;
  }
  /**
   * <pre>
   * 待排产订单列表
   * </pre>
   *
   * <code>repeated .aps.v1.Job jobs = 3;</code>
   */
  @java.lang.Override
  public int getJobsCount() {
    return jobs_.size();
  }
  /**
   * <pre>
   * 待排产订单列表
   * </pre>
   *
   * <code>repeated .aps.v1.Job jobs = 3;</code>
   */
  @java.lang.Override
  public com.aps.grpc.proto.Job getJobs(int index) {
    return jobs_.get(index);
  }
  /**
   * <pre>
   * 待排产订单列表
   * </pre>
   *
   * <code>repeated .aps.v1.Job jobs = 3;</code>
   */
  @java.lang.Override
  public com.aps.grpc.proto.JobOrBuilder getJobsOrBuilder(
      int index) {
    return jobs_.get(index);
  }

  public static final int PARAMS_FIELD_NUMBER = 4;
  private com.aps.grpc.proto.SolveParams params_;
  /**
   * <pre>
   * 求解参数
   * </pre>
   *
   * <code>.aps.v1.SolveParams params = 4;</code>
   * @return Whether the params field is set.
   */
  @java.lang.Override
  public boolean hasParams() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * 求解参数
   * </pre>
   *
   * <code>.aps.v1.SolveParams params = 4;</code>
   * @return The params.
   */
  @java.lang.Override
  public com.aps.grpc.proto.SolveParams getParams() {
    return params_ == null ? com.aps.grpc.proto.SolveParams.getDefaultInstance() : params_;
  }
  /**
   * <pre>
   * 求解参数
   * </pre>
   *
   * <code>.aps.v1.SolveParams params = 4;</code>
   */
  @java.lang.Override
  public com.aps.grpc.proto.SolveParamsOrBuilder getParamsOrBuilder() {
    return params_ == null ? com.aps.grpc.proto.SolveParams.getDefaultInstance() : params_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestId_);
    }
    if (planStartEpochMs_ != 0L) {
      output.writeInt64(2, planStartEpochMs_);
    }
    for (int i = 0; i < jobs_.size(); i++) {
      output.writeMessage(3, jobs_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(4, getParams());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestId_);
    }
    if (planStartEpochMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, planStartEpochMs_);
    }
    for (int i = 0; i < jobs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, jobs_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getParams());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.aps.grpc.proto.SolveRequest)) {
      return super.equals(obj);
    }
    com.aps.grpc.proto.SolveRequest other = (com.aps.grpc.proto.SolveRequest) obj;

    if (!getRequestId()
        .equals(other.getRequestId())) return false;
    if (getPlanStartEpochMs()
        != other.getPlanStartEpochMs()) return false;
    if (!getJobsList()
        .equals(other.getJobsList())) return false;
    if (hasParams() != other.hasParams()) return false;
    if (hasParams()) {
      if (!getParams()
          .equals(other.getParams())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRequestId().hashCode();
    hash = (37 * hash) + PLAN_START_EPOCH_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPlanStartEpochMs());
    if (getJobsCount() > 0) {
      hash = (37 * hash) + JOBS_FIELD_NUMBER;
      hash = (53 * hash) + getJobsList().hashCode();
    }
    if (hasParams()) {
      hash = (37 * hash) + PARAMS_FIELD_NUMBER;
      hash = (53 * hash) + getParams().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.aps.grpc.proto.SolveRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aps.grpc.proto.SolveRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aps.grpc.proto.SolveRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aps.grpc.proto.SolveRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aps.grpc.proto.SolveRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aps.grpc.proto.SolveRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aps.grpc.proto.SolveRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aps.grpc.proto.SolveRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.aps.grpc.proto.SolveRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.aps.grpc.proto.SolveRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aps.grpc.proto.SolveRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aps.grpc.proto.SolveRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.aps.grpc.proto.SolveRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code aps.v1.SolveRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:aps.v1.SolveRequest)
      com.aps.grpc.proto.SolveRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_SolveRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_SolveRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aps.grpc.proto.SolveRequest.class, com.aps.grpc.proto.SolveRequest.Builder.class);
    }

    // Construct using com.aps.grpc.proto.SolveRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getJobsFieldBuilder();
        getParamsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      requestId_ = "";
      planStartEpochMs_ = 0L;
      if (jobsBuilder_ == null) {
        jobs_ = java.util.Collections.emptyList();
      } else {
        jobs_ = null;
        jobsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      params_ = null;
      if (paramsBuilder_ != null) {
        paramsBuilder_.dispose();
        paramsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_SolveRequest_descriptor;
    }

    @java.lang.Override
    public com.aps.grpc.proto.SolveRequest getDefaultInstanceForType() {
      return com.aps.grpc.proto.SolveRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.aps.grpc.proto.SolveRequest build() {
      com.aps.grpc.proto.SolveRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.aps.grpc.proto.SolveRequest buildPartial() {
      com.aps.grpc.proto.SolveRequest result = new com.aps.grpc.proto.SolveRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.aps.grpc.proto.SolveRequest result) {
      if (jobsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          jobs_ = java.util.Collections.unmodifiableList(jobs_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.jobs_ = jobs_;
      } else {
        result.jobs_ = jobsBuilder_.build();
      }
    }

    private void buildPartial0(com.aps.grpc.proto.SolveRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.requestId_ = requestId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.planStartEpochMs_ = planStartEpochMs_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.params_ = paramsBuilder_ == null
            ? params_
            : paramsBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.aps.grpc.proto.SolveRequest) {
        return mergeFrom((com.aps.grpc.proto.SolveRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.aps.grpc.proto.SolveRequest other) {
      if (other == com.aps.grpc.proto.SolveRequest.getDefaultInstance()) return this;
      if (!other.getRequestId().isEmpty()) {
        requestId_ = other.requestId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getPlanStartEpochMs() != 0L) {
        setPlanStartEpochMs(other.getPlanStartEpochMs());
      }
      if (jobsBuilder_ == null) {
        if (!other.jobs_.isEmpty()) {
          if (jobs_.isEmpty()) {
            jobs_ = other.jobs_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureJobsIsMutable();
            jobs_.addAll(other.jobs_);
          }
          onChanged();
        }
      } else {
        if (!other.jobs_.isEmpty()) {
          if (jobsBuilder_.isEmpty()) {
            jobsBuilder_.dispose();
            jobsBuilder_ = null;
            jobs_ = other.jobs_;
            bitField0_ = (bitField0_ & ~0x00000004);
            jobsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getJobsFieldBuilder() : null;
          } else {
            jobsBuilder_.addAllMessages(other.jobs_);
          }
        }
      }
      if (other.hasParams()) {
        mergeParams(other.getParams());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              requestId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              planStartEpochMs_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              com.aps.grpc.proto.Job m =
                  input.readMessage(
                      com.aps.grpc.proto.Job.parser(),
                      extensionRegistry);
              if (jobsBuilder_ == null) {
                ensureJobsIsMutable();
                jobs_.add(m);
              } else {
                jobsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getParamsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object requestId_ = "";
    /**
     * <pre>
     * 请求唯一标识
     * </pre>
     *
     * <code>string request_id = 1;</code>
     * @return The requestId.
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 请求唯一标识
     * </pre>
     *
     * <code>string request_id = 1;</code>
     * @return The bytes for requestId.
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 请求唯一标识
     * </pre>
     *
     * <code>string request_id = 1;</code>
     * @param value The requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      requestId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 请求唯一标识
     * </pre>
     *
     * <code>string request_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestId() {
      requestId_ = getDefaultInstance().getRequestId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 请求唯一标识
     * </pre>
     *
     * <code>string request_id = 1;</code>
     * @param value The bytes for requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      requestId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private long planStartEpochMs_ ;
    /**
     * <pre>
     * 排产起始时间（毫秒时间戳）
     * </pre>
     *
     * <code>int64 plan_start_epoch_ms = 2;</code>
     * @return The planStartEpochMs.
     */
    @java.lang.Override
    public long getPlanStartEpochMs() {
      return planStartEpochMs_;
    }
    /**
     * <pre>
     * 排产起始时间（毫秒时间戳）
     * </pre>
     *
     * <code>int64 plan_start_epoch_ms = 2;</code>
     * @param value The planStartEpochMs to set.
     * @return This builder for chaining.
     */
    public Builder setPlanStartEpochMs(long value) {

      planStartEpochMs_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 排产起始时间（毫秒时间戳）
     * </pre>
     *
     * <code>int64 plan_start_epoch_ms = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlanStartEpochMs() {
      bitField0_ = (bitField0_ & ~0x00000002);
      planStartEpochMs_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<com.aps.grpc.proto.Job> jobs_ =
      java.util.Collections.emptyList();
    private void ensureJobsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        jobs_ = new java.util.ArrayList<com.aps.grpc.proto.Job>(jobs_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.aps.grpc.proto.Job, com.aps.grpc.proto.Job.Builder, com.aps.grpc.proto.JobOrBuilder> jobsBuilder_;

    /**
     * <pre>
     * 待排产订单列表
     * </pre>
     *
     * <code>repeated .aps.v1.Job jobs = 3;</code>
     */
    public java.util.List<com.aps.grpc.proto.Job> getJobsList() {
      if (jobsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(jobs_);
      } else {
        return jobsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 待排产订单列表
     * </pre>
     *
     * <code>repeated .aps.v1.Job jobs = 3;</code>
     */
    public int getJobsCount() {
      if (jobsBuilder_ == null) {
        return jobs_.size();
      } else {
        return jobsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 待排产订单列表
     * </pre>
     *
     * <code>repeated .aps.v1.Job jobs = 3;</code>
     */
    public com.aps.grpc.proto.Job getJobs(int index) {
      if (jobsBuilder_ == null) {
        return jobs_.get(index);
      } else {
        return jobsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 待排产订单列表
     * </pre>
     *
     * <code>repeated .aps.v1.Job jobs = 3;</code>
     */
    public Builder setJobs(
        int index, com.aps.grpc.proto.Job value) {
      if (jobsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobsIsMutable();
        jobs_.set(index, value);
        onChanged();
      } else {
        jobsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 待排产订单列表
     * </pre>
     *
     * <code>repeated .aps.v1.Job jobs = 3;</code>
     */
    public Builder setJobs(
        int index, com.aps.grpc.proto.Job.Builder builderForValue) {
      if (jobsBuilder_ == null) {
        ensureJobsIsMutable();
        jobs_.set(index, builderForValue.build());
        onChanged();
      } else {
        jobsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 待排产订单列表
     * </pre>
     *
     * <code>repeated .aps.v1.Job jobs = 3;</code>
     */
    public Builder addJobs(com.aps.grpc.proto.Job value) {
      if (jobsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobsIsMutable();
        jobs_.add(value);
        onChanged();
      } else {
        jobsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 待排产订单列表
     * </pre>
     *
     * <code>repeated .aps.v1.Job jobs = 3;</code>
     */
    public Builder addJobs(
        int index, com.aps.grpc.proto.Job value) {
      if (jobsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobsIsMutable();
        jobs_.add(index, value);
        onChanged();
      } else {
        jobsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 待排产订单列表
     * </pre>
     *
     * <code>repeated .aps.v1.Job jobs = 3;</code>
     */
    public Builder addJobs(
        com.aps.grpc.proto.Job.Builder builderForValue) {
      if (jobsBuilder_ == null) {
        ensureJobsIsMutable();
        jobs_.add(builderForValue.build());
        onChanged();
      } else {
        jobsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 待排产订单列表
     * </pre>
     *
     * <code>repeated .aps.v1.Job jobs = 3;</code>
     */
    public Builder addJobs(
        int index, com.aps.grpc.proto.Job.Builder builderForValue) {
      if (jobsBuilder_ == null) {
        ensureJobsIsMutable();
        jobs_.add(index, builderForValue.build());
        onChanged();
      } else {
        jobsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 待排产订单列表
     * </pre>
     *
     * <code>repeated .aps.v1.Job jobs = 3;</code>
     */
    public Builder addAllJobs(
        java.lang.Iterable<? extends com.aps.grpc.proto.Job> values) {
      if (jobsBuilder_ == null) {
        ensureJobsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, jobs_);
        onChanged();
      } else {
        jobsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 待排产订单列表
     * </pre>
     *
     * <code>repeated .aps.v1.Job jobs = 3;</code>
     */
    public Builder clearJobs() {
      if (jobsBuilder_ == null) {
        jobs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        jobsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 待排产订单列表
     * </pre>
     *
     * <code>repeated .aps.v1.Job jobs = 3;</code>
     */
    public Builder removeJobs(int index) {
      if (jobsBuilder_ == null) {
        ensureJobsIsMutable();
        jobs_.remove(index);
        onChanged();
      } else {
        jobsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 待排产订单列表
     * </pre>
     *
     * <code>repeated .aps.v1.Job jobs = 3;</code>
     */
    public com.aps.grpc.proto.Job.Builder getJobsBuilder(
        int index) {
      return getJobsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 待排产订单列表
     * </pre>
     *
     * <code>repeated .aps.v1.Job jobs = 3;</code>
     */
    public com.aps.grpc.proto.JobOrBuilder getJobsOrBuilder(
        int index) {
      if (jobsBuilder_ == null) {
        return jobs_.get(index);  } else {
        return jobsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 待排产订单列表
     * </pre>
     *
     * <code>repeated .aps.v1.Job jobs = 3;</code>
     */
    public java.util.List<? extends com.aps.grpc.proto.JobOrBuilder> 
         getJobsOrBuilderList() {
      if (jobsBuilder_ != null) {
        return jobsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(jobs_);
      }
    }
    /**
     * <pre>
     * 待排产订单列表
     * </pre>
     *
     * <code>repeated .aps.v1.Job jobs = 3;</code>
     */
    public com.aps.grpc.proto.Job.Builder addJobsBuilder() {
      return getJobsFieldBuilder().addBuilder(
          com.aps.grpc.proto.Job.getDefaultInstance());
    }
    /**
     * <pre>
     * 待排产订单列表
     * </pre>
     *
     * <code>repeated .aps.v1.Job jobs = 3;</code>
     */
    public com.aps.grpc.proto.Job.Builder addJobsBuilder(
        int index) {
      return getJobsFieldBuilder().addBuilder(
          index, com.aps.grpc.proto.Job.getDefaultInstance());
    }
    /**
     * <pre>
     * 待排产订单列表
     * </pre>
     *
     * <code>repeated .aps.v1.Job jobs = 3;</code>
     */
    public java.util.List<com.aps.grpc.proto.Job.Builder> 
         getJobsBuilderList() {
      return getJobsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.aps.grpc.proto.Job, com.aps.grpc.proto.Job.Builder, com.aps.grpc.proto.JobOrBuilder> 
        getJobsFieldBuilder() {
      if (jobsBuilder_ == null) {
        jobsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.aps.grpc.proto.Job, com.aps.grpc.proto.Job.Builder, com.aps.grpc.proto.JobOrBuilder>(
                jobs_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        jobs_ = null;
      }
      return jobsBuilder_;
    }

    private com.aps.grpc.proto.SolveParams params_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.aps.grpc.proto.SolveParams, com.aps.grpc.proto.SolveParams.Builder, com.aps.grpc.proto.SolveParamsOrBuilder> paramsBuilder_;
    /**
     * <pre>
     * 求解参数
     * </pre>
     *
     * <code>.aps.v1.SolveParams params = 4;</code>
     * @return Whether the params field is set.
     */
    public boolean hasParams() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * 求解参数
     * </pre>
     *
     * <code>.aps.v1.SolveParams params = 4;</code>
     * @return The params.
     */
    public com.aps.grpc.proto.SolveParams getParams() {
      if (paramsBuilder_ == null) {
        return params_ == null ? com.aps.grpc.proto.SolveParams.getDefaultInstance() : params_;
      } else {
        return paramsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 求解参数
     * </pre>
     *
     * <code>.aps.v1.SolveParams params = 4;</code>
     */
    public Builder setParams(com.aps.grpc.proto.SolveParams value) {
      if (paramsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        params_ = value;
      } else {
        paramsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 求解参数
     * </pre>
     *
     * <code>.aps.v1.SolveParams params = 4;</code>
     */
    public Builder setParams(
        com.aps.grpc.proto.SolveParams.Builder builderForValue) {
      if (paramsBuilder_ == null) {
        params_ = builderForValue.build();
      } else {
        paramsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 求解参数
     * </pre>
     *
     * <code>.aps.v1.SolveParams params = 4;</code>
     */
    public Builder mergeParams(com.aps.grpc.proto.SolveParams value) {
      if (paramsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          params_ != null &&
          params_ != com.aps.grpc.proto.SolveParams.getDefaultInstance()) {
          getParamsBuilder().mergeFrom(value);
        } else {
          params_ = value;
        }
      } else {
        paramsBuilder_.mergeFrom(value);
      }
      if (params_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * 求解参数
     * </pre>
     *
     * <code>.aps.v1.SolveParams params = 4;</code>
     */
    public Builder clearParams() {
      bitField0_ = (bitField0_ & ~0x00000008);
      params_ = null;
      if (paramsBuilder_ != null) {
        paramsBuilder_.dispose();
        paramsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 求解参数
     * </pre>
     *
     * <code>.aps.v1.SolveParams params = 4;</code>
     */
    public com.aps.grpc.proto.SolveParams.Builder getParamsBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getParamsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 求解参数
     * </pre>
     *
     * <code>.aps.v1.SolveParams params = 4;</code>
     */
    public com.aps.grpc.proto.SolveParamsOrBuilder getParamsOrBuilder() {
      if (paramsBuilder_ != null) {
        return paramsBuilder_.getMessageOrBuilder();
      } else {
        return params_ == null ?
            com.aps.grpc.proto.SolveParams.getDefaultInstance() : params_;
      }
    }
    /**
     * <pre>
     * 求解参数
     * </pre>
     *
     * <code>.aps.v1.SolveParams params = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.aps.grpc.proto.SolveParams, com.aps.grpc.proto.SolveParams.Builder, com.aps.grpc.proto.SolveParamsOrBuilder> 
        getParamsFieldBuilder() {
      if (paramsBuilder_ == null) {
        paramsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.aps.grpc.proto.SolveParams, com.aps.grpc.proto.SolveParams.Builder, com.aps.grpc.proto.SolveParamsOrBuilder>(
                getParams(),
                getParentForChildren(),
                isClean());
        params_ = null;
      }
      return paramsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:aps.v1.SolveRequest)
  }

  // @@protoc_insertion_point(class_scope:aps.v1.SolveRequest)
  private static final com.aps.grpc.proto.SolveRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.aps.grpc.proto.SolveRequest();
  }

  public static com.aps.grpc.proto.SolveRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SolveRequest>
      PARSER = new com.google.protobuf.AbstractParser<SolveRequest>() {
    @java.lang.Override
    public SolveRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SolveRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SolveRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.aps.grpc.proto.SolveRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

