// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aps.proto

// Protobuf Java Version: 3.25.2
package com.aps.grpc.proto;

public interface SolveParamsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aps.v1.SolveParams)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 算法选择: baseline/sa/hybrid
   * </pre>
   *
   * <code>string algorithm = 1;</code>
   * @return The algorithm.
   */
  java.lang.String getAlgorithm();
  /**
   * <pre>
   * 算法选择: baseline/sa/hybrid
   * </pre>
   *
   * <code>string algorithm = 1;</code>
   * @return The bytes for algorithm.
   */
  com.google.protobuf.ByteString
      getAlgorithmBytes();

  /**
   * <pre>
   * 求解时间预算（秒）
   * </pre>
   *
   * <code>int32 time_budget_sec = 2;</code>
   * @return The timeBudgetSec.
   */
  int getTimeBudgetSec();

  /**
   * <pre>
   * 随机种子
   * </pre>
   *
   * <code>int64 seed = 3;</code>
   * @return The seed.
   */
  long getSeed();

  /**
   * <pre>
   * 目标权重
   * </pre>
   *
   * <code>.aps.v1.Weights weights = 4;</code>
   * @return Whether the weights field is set.
   */
  boolean hasWeights();
  /**
   * <pre>
   * 目标权重
   * </pre>
   *
   * <code>.aps.v1.Weights weights = 4;</code>
   * @return The weights.
   */
  com.aps.grpc.proto.Weights getWeights();
  /**
   * <pre>
   * 目标权重
   * </pre>
   *
   * <code>.aps.v1.Weights weights = 4;</code>
   */
  com.aps.grpc.proto.WeightsOrBuilder getWeightsOrBuilder();

  /**
   * <pre>
   * 资源限制
   * </pre>
   *
   * <code>.aps.v1.Limits limits = 5;</code>
   * @return Whether the limits field is set.
   */
  boolean hasLimits();
  /**
   * <pre>
   * 资源限制
   * </pre>
   *
   * <code>.aps.v1.Limits limits = 5;</code>
   * @return The limits.
   */
  com.aps.grpc.proto.Limits getLimits();
  /**
   * <pre>
   * 资源限制
   * </pre>
   *
   * <code>.aps.v1.Limits limits = 5;</code>
   */
  com.aps.grpc.proto.LimitsOrBuilder getLimitsOrBuilder();
}
