// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aps.proto

// Protobuf Java Version: 3.25.2
package com.aps.grpc.proto;

public interface SubmitJobRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aps.v1.SubmitJobRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 求解请求
   * </pre>
   *
   * <code>.aps.v1.SolveRequest request = 1;</code>
   * @return Whether the request field is set.
   */
  boolean hasRequest();
  /**
   * <pre>
   * 求解请求
   * </pre>
   *
   * <code>.aps.v1.SolveRequest request = 1;</code>
   * @return The request.
   */
  com.aps.grpc.proto.SolveRequest getRequest();
  /**
   * <pre>
   * 求解请求
   * </pre>
   *
   * <code>.aps.v1.SolveRequest request = 1;</code>
   */
  com.aps.grpc.proto.SolveRequestOrBuilder getRequestOrBuilder();
}
