// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aps.proto

// Protobuf Java Version: 3.25.2
package com.aps.grpc.proto;

public interface WeightsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aps.v1.Weights)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 延迟惩罚权重
   * </pre>
   *
   * <code>double tardiness = 1;</code>
   * @return The tardiness.
   */
  double getTardiness();

  /**
   * <pre>
   * 颜色切换权重
   * </pre>
   *
   * <code>double color_change = 2;</code>
   * @return The colorChange.
   */
  double getColorChange();

  /**
   * <pre>
   * 配置切换权重
   * </pre>
   *
   * <code>double config_change = 3;</code>
   * @return The configChange.
   */
  double getConfigChange();

  /**
   * <pre>
   * 能耗超限权重
   * </pre>
   *
   * <code>double energy_excess = 4;</code>
   * @return The energyExcess.
   */
  double getEnergyExcess();

  /**
   * <pre>
   * 排放超限权重
   * </pre>
   *
   * <code>double emission_excess = 5;</code>
   * @return The emissionExcess.
   */
  double getEmissionExcess();

  /**
   * <pre>
   * 物料短缺权重
   * </pre>
   *
   * <code>double material_shortage = 6;</code>
   * @return The materialShortage.
   */
  double getMaterialShortage();
}
