// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aps.proto

// Protobuf Java Version: 3.25.2
package com.aps.grpc.proto;

/**
 * Protobuf type {@code aps.v1.Weights}
 */
public final class Weights extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:aps.v1.Weights)
    WeightsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Weights.newBuilder() to construct.
  private Weights(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Weights() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Weights();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_Weights_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_Weights_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.aps.grpc.proto.Weights.class, com.aps.grpc.proto.Weights.Builder.class);
  }

  public static final int TARDINESS_FIELD_NUMBER = 1;
  private double tardiness_ = 0D;
  /**
   * <pre>
   * 延迟惩罚权重
   * </pre>
   *
   * <code>double tardiness = 1;</code>
   * @return The tardiness.
   */
  @java.lang.Override
  public double getTardiness() {
    return tardiness_;
  }

  public static final int COLOR_CHANGE_FIELD_NUMBER = 2;
  private double colorChange_ = 0D;
  /**
   * <pre>
   * 颜色切换权重
   * </pre>
   *
   * <code>double color_change = 2;</code>
   * @return The colorChange.
   */
  @java.lang.Override
  public double getColorChange() {
    return colorChange_;
  }

  public static final int CONFIG_CHANGE_FIELD_NUMBER = 3;
  private double configChange_ = 0D;
  /**
   * <pre>
   * 配置切换权重
   * </pre>
   *
   * <code>double config_change = 3;</code>
   * @return The configChange.
   */
  @java.lang.Override
  public double getConfigChange() {
    return configChange_;
  }

  public static final int ENERGY_EXCESS_FIELD_NUMBER = 4;
  private double energyExcess_ = 0D;
  /**
   * <pre>
   * 能耗超限权重
   * </pre>
   *
   * <code>double energy_excess = 4;</code>
   * @return The energyExcess.
   */
  @java.lang.Override
  public double getEnergyExcess() {
    return energyExcess_;
  }

  public static final int EMISSION_EXCESS_FIELD_NUMBER = 5;
  private double emissionExcess_ = 0D;
  /**
   * <pre>
   * 排放超限权重
   * </pre>
   *
   * <code>double emission_excess = 5;</code>
   * @return The emissionExcess.
   */
  @java.lang.Override
  public double getEmissionExcess() {
    return emissionExcess_;
  }

  public static final int MATERIAL_SHORTAGE_FIELD_NUMBER = 6;
  private double materialShortage_ = 0D;
  /**
   * <pre>
   * 物料短缺权重
   * </pre>
   *
   * <code>double material_shortage = 6;</code>
   * @return The materialShortage.
   */
  @java.lang.Override
  public double getMaterialShortage() {
    return materialShortage_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Double.doubleToRawLongBits(tardiness_) != 0) {
      output.writeDouble(1, tardiness_);
    }
    if (java.lang.Double.doubleToRawLongBits(colorChange_) != 0) {
      output.writeDouble(2, colorChange_);
    }
    if (java.lang.Double.doubleToRawLongBits(configChange_) != 0) {
      output.writeDouble(3, configChange_);
    }
    if (java.lang.Double.doubleToRawLongBits(energyExcess_) != 0) {
      output.writeDouble(4, energyExcess_);
    }
    if (java.lang.Double.doubleToRawLongBits(emissionExcess_) != 0) {
      output.writeDouble(5, emissionExcess_);
    }
    if (java.lang.Double.doubleToRawLongBits(materialShortage_) != 0) {
      output.writeDouble(6, materialShortage_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Double.doubleToRawLongBits(tardiness_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, tardiness_);
    }
    if (java.lang.Double.doubleToRawLongBits(colorChange_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, colorChange_);
    }
    if (java.lang.Double.doubleToRawLongBits(configChange_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, configChange_);
    }
    if (java.lang.Double.doubleToRawLongBits(energyExcess_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, energyExcess_);
    }
    if (java.lang.Double.doubleToRawLongBits(emissionExcess_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, emissionExcess_);
    }
    if (java.lang.Double.doubleToRawLongBits(materialShortage_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, materialShortage_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.aps.grpc.proto.Weights)) {
      return super.equals(obj);
    }
    com.aps.grpc.proto.Weights other = (com.aps.grpc.proto.Weights) obj;

    if (java.lang.Double.doubleToLongBits(getTardiness())
        != java.lang.Double.doubleToLongBits(
            other.getTardiness())) return false;
    if (java.lang.Double.doubleToLongBits(getColorChange())
        != java.lang.Double.doubleToLongBits(
            other.getColorChange())) return false;
    if (java.lang.Double.doubleToLongBits(getConfigChange())
        != java.lang.Double.doubleToLongBits(
            other.getConfigChange())) return false;
    if (java.lang.Double.doubleToLongBits(getEnergyExcess())
        != java.lang.Double.doubleToLongBits(
            other.getEnergyExcess())) return false;
    if (java.lang.Double.doubleToLongBits(getEmissionExcess())
        != java.lang.Double.doubleToLongBits(
            other.getEmissionExcess())) return false;
    if (java.lang.Double.doubleToLongBits(getMaterialShortage())
        != java.lang.Double.doubleToLongBits(
            other.getMaterialShortage())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TARDINESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTardiness()));
    hash = (37 * hash) + COLOR_CHANGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getColorChange()));
    hash = (37 * hash) + CONFIG_CHANGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getConfigChange()));
    hash = (37 * hash) + ENERGY_EXCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getEnergyExcess()));
    hash = (37 * hash) + EMISSION_EXCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getEmissionExcess()));
    hash = (37 * hash) + MATERIAL_SHORTAGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMaterialShortage()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.aps.grpc.proto.Weights parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aps.grpc.proto.Weights parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aps.grpc.proto.Weights parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aps.grpc.proto.Weights parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aps.grpc.proto.Weights parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aps.grpc.proto.Weights parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aps.grpc.proto.Weights parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aps.grpc.proto.Weights parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.aps.grpc.proto.Weights parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.aps.grpc.proto.Weights parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aps.grpc.proto.Weights parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aps.grpc.proto.Weights parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.aps.grpc.proto.Weights prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code aps.v1.Weights}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:aps.v1.Weights)
      com.aps.grpc.proto.WeightsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_Weights_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_Weights_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aps.grpc.proto.Weights.class, com.aps.grpc.proto.Weights.Builder.class);
    }

    // Construct using com.aps.grpc.proto.Weights.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      tardiness_ = 0D;
      colorChange_ = 0D;
      configChange_ = 0D;
      energyExcess_ = 0D;
      emissionExcess_ = 0D;
      materialShortage_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.aps.grpc.proto.ApsProto.internal_static_aps_v1_Weights_descriptor;
    }

    @java.lang.Override
    public com.aps.grpc.proto.Weights getDefaultInstanceForType() {
      return com.aps.grpc.proto.Weights.getDefaultInstance();
    }

    @java.lang.Override
    public com.aps.grpc.proto.Weights build() {
      com.aps.grpc.proto.Weights result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.aps.grpc.proto.Weights buildPartial() {
      com.aps.grpc.proto.Weights result = new com.aps.grpc.proto.Weights(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.aps.grpc.proto.Weights result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.tardiness_ = tardiness_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.colorChange_ = colorChange_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.configChange_ = configChange_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.energyExcess_ = energyExcess_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.emissionExcess_ = emissionExcess_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.materialShortage_ = materialShortage_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.aps.grpc.proto.Weights) {
        return mergeFrom((com.aps.grpc.proto.Weights)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.aps.grpc.proto.Weights other) {
      if (other == com.aps.grpc.proto.Weights.getDefaultInstance()) return this;
      if (other.getTardiness() != 0D) {
        setTardiness(other.getTardiness());
      }
      if (other.getColorChange() != 0D) {
        setColorChange(other.getColorChange());
      }
      if (other.getConfigChange() != 0D) {
        setConfigChange(other.getConfigChange());
      }
      if (other.getEnergyExcess() != 0D) {
        setEnergyExcess(other.getEnergyExcess());
      }
      if (other.getEmissionExcess() != 0D) {
        setEmissionExcess(other.getEmissionExcess());
      }
      if (other.getMaterialShortage() != 0D) {
        setMaterialShortage(other.getMaterialShortage());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              tardiness_ = input.readDouble();
              bitField0_ |= 0x00000001;
              break;
            } // case 9
            case 17: {
              colorChange_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 25: {
              configChange_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 33: {
              energyExcess_ = input.readDouble();
              bitField0_ |= 0x00000008;
              break;
            } // case 33
            case 41: {
              emissionExcess_ = input.readDouble();
              bitField0_ |= 0x00000010;
              break;
            } // case 41
            case 49: {
              materialShortage_ = input.readDouble();
              bitField0_ |= 0x00000020;
              break;
            } // case 49
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private double tardiness_ ;
    /**
     * <pre>
     * 延迟惩罚权重
     * </pre>
     *
     * <code>double tardiness = 1;</code>
     * @return The tardiness.
     */
    @java.lang.Override
    public double getTardiness() {
      return tardiness_;
    }
    /**
     * <pre>
     * 延迟惩罚权重
     * </pre>
     *
     * <code>double tardiness = 1;</code>
     * @param value The tardiness to set.
     * @return This builder for chaining.
     */
    public Builder setTardiness(double value) {

      tardiness_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 延迟惩罚权重
     * </pre>
     *
     * <code>double tardiness = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTardiness() {
      bitField0_ = (bitField0_ & ~0x00000001);
      tardiness_ = 0D;
      onChanged();
      return this;
    }

    private double colorChange_ ;
    /**
     * <pre>
     * 颜色切换权重
     * </pre>
     *
     * <code>double color_change = 2;</code>
     * @return The colorChange.
     */
    @java.lang.Override
    public double getColorChange() {
      return colorChange_;
    }
    /**
     * <pre>
     * 颜色切换权重
     * </pre>
     *
     * <code>double color_change = 2;</code>
     * @param value The colorChange to set.
     * @return This builder for chaining.
     */
    public Builder setColorChange(double value) {

      colorChange_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 颜色切换权重
     * </pre>
     *
     * <code>double color_change = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearColorChange() {
      bitField0_ = (bitField0_ & ~0x00000002);
      colorChange_ = 0D;
      onChanged();
      return this;
    }

    private double configChange_ ;
    /**
     * <pre>
     * 配置切换权重
     * </pre>
     *
     * <code>double config_change = 3;</code>
     * @return The configChange.
     */
    @java.lang.Override
    public double getConfigChange() {
      return configChange_;
    }
    /**
     * <pre>
     * 配置切换权重
     * </pre>
     *
     * <code>double config_change = 3;</code>
     * @param value The configChange to set.
     * @return This builder for chaining.
     */
    public Builder setConfigChange(double value) {

      configChange_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 配置切换权重
     * </pre>
     *
     * <code>double config_change = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearConfigChange() {
      bitField0_ = (bitField0_ & ~0x00000004);
      configChange_ = 0D;
      onChanged();
      return this;
    }

    private double energyExcess_ ;
    /**
     * <pre>
     * 能耗超限权重
     * </pre>
     *
     * <code>double energy_excess = 4;</code>
     * @return The energyExcess.
     */
    @java.lang.Override
    public double getEnergyExcess() {
      return energyExcess_;
    }
    /**
     * <pre>
     * 能耗超限权重
     * </pre>
     *
     * <code>double energy_excess = 4;</code>
     * @param value The energyExcess to set.
     * @return This builder for chaining.
     */
    public Builder setEnergyExcess(double value) {

      energyExcess_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 能耗超限权重
     * </pre>
     *
     * <code>double energy_excess = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnergyExcess() {
      bitField0_ = (bitField0_ & ~0x00000008);
      energyExcess_ = 0D;
      onChanged();
      return this;
    }

    private double emissionExcess_ ;
    /**
     * <pre>
     * 排放超限权重
     * </pre>
     *
     * <code>double emission_excess = 5;</code>
     * @return The emissionExcess.
     */
    @java.lang.Override
    public double getEmissionExcess() {
      return emissionExcess_;
    }
    /**
     * <pre>
     * 排放超限权重
     * </pre>
     *
     * <code>double emission_excess = 5;</code>
     * @param value The emissionExcess to set.
     * @return This builder for chaining.
     */
    public Builder setEmissionExcess(double value) {

      emissionExcess_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 排放超限权重
     * </pre>
     *
     * <code>double emission_excess = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmissionExcess() {
      bitField0_ = (bitField0_ & ~0x00000010);
      emissionExcess_ = 0D;
      onChanged();
      return this;
    }

    private double materialShortage_ ;
    /**
     * <pre>
     * 物料短缺权重
     * </pre>
     *
     * <code>double material_shortage = 6;</code>
     * @return The materialShortage.
     */
    @java.lang.Override
    public double getMaterialShortage() {
      return materialShortage_;
    }
    /**
     * <pre>
     * 物料短缺权重
     * </pre>
     *
     * <code>double material_shortage = 6;</code>
     * @param value The materialShortage to set.
     * @return This builder for chaining.
     */
    public Builder setMaterialShortage(double value) {

      materialShortage_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 物料短缺权重
     * </pre>
     *
     * <code>double material_shortage = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaterialShortage() {
      bitField0_ = (bitField0_ & ~0x00000020);
      materialShortage_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:aps.v1.Weights)
  }

  // @@protoc_insertion_point(class_scope:aps.v1.Weights)
  private static final com.aps.grpc.proto.Weights DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.aps.grpc.proto.Weights();
  }

  public static com.aps.grpc.proto.Weights getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Weights>
      PARSER = new com.google.protobuf.AbstractParser<Weights>() {
    @java.lang.Override
    public Weights parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Weights> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Weights> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.aps.grpc.proto.Weights getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

